# Temporary Roles Configuration
temporary_roles:
  enabled: true
  default_duration: 4
  max_duration: 24
  min_duration: 1
  
  # Approval settings
  approval:
    required: true
    approver_roles: [admin, maintainer]
    auto_approve_emergency: false
    approval_timeout_minutes: 60
  
  # Notification settings
  notifications:
    on_request: true
    on_approval: true
    on_revocation: true
    on_expiration: true
    channels: [email, slack]
  
  # Security restrictions
  restrictions:
    max_active_roles_per_user: 2
    max_requests_per_day: 5
    cool_down_period_hours: 1
    blackout_periods: []
  
  # Role-specific settings
  role_limits:
    admin:
      max_duration: 8
      approval_required: true
      emergency_only: false
    super_admin:
      max_duration: 4
      approval_required: true
      emergency_only: true
    maintainer:
      max_duration: 12
      approval_required: false
      emergency_only: false
  
  # Audit settings
  audit:
    log_all_requests: true
    log_approvals: true
    log_revocations: true
    log_expirations: true
    retention_days: 90
  
  # Integration
  integration:
    with_incident_system: true
    with_approval_system: true
    with_monitoring: true
